### ISSUE TITLE
(T1) Use Concordium ID to send and receive GTU

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1117]
**Mission:** 
- create or reuse identity (mobile wallet Concordium ID)
- create or reuse accounts A and B (mobile wallet Concordium ID)

**On Concordium ID:**
- transfer 3 GTU from account A to account B
- shield 10 GTU of account A
- transfer 7 GTU from the shielded balance on account A to B
- unshield shielded balance on account B
- check transfers in the respective block on the network dashboard

_Note that all transfers come with a fee to be paid from the general balance, so please make sure, you have enough money on the general balance of the accounts. Otherwise, you might want to create a new account an get a new GTU drop. See [Transfer Fees](https://github.com/Concordium/Testnet3-Challenges/wiki/Transfer-Fees) for more details._

**Submission:** 
- submit account addresses for A and B
- submit device make and model and OS version

**Comment by okannako** [comment]
transfer 3 GTU from account A to account B
![A - B](https://user-images.githubusercontent.com/73176377/97458247-94864080-194b-11eb-9ef5-520a1f6d47df.png)

shield 10 GTU of account A
![10-1](https://user-images.githubusercontent.com/73176377/97458371-af58b500-194b-11eb-9b9c-d2d051ba231b.png)
![10-2](https://user-images.githubusercontent.com/73176377/97458386-b1227880-194b-11eb-9894-2eb1d891282f.png)

transfer 7 GTU from the shielded balance on account A to B
![7 (1)](https://user-images.githubusercontent.com/73176377/97459095-710fc580-194c-11eb-89d7-e111f4ce0aea.png)
![7 (2)](https://user-images.githubusercontent.com/73176377/97459098-72d98900-194c-11eb-92b2-bddf301dbff2.png)
![7 (3)](https://user-images.githubusercontent.com/73176377/97459107-753be300-194c-11eb-8106-701a16adcb7d.png)
![7 (4)](https://user-images.githubusercontent.com/73176377/97459109-766d1000-194c-11eb-886c-eece8f2dd4a9.png)
![7 (5)](https://user-images.githubusercontent.com/73176377/97459111-7705a680-194c-11eb-9bf0-62134fe6f350.png)
![7 (6)](https://user-images.githubusercontent.com/73176377/97459113-7836d380-194c-11eb-9220-fb14840ee90b.png)

Android Oreo Pc - Windows 10

**Comment by popovanton89** [comment]
account addresses for A:  3mYBgAZ5Cq96WjTLbXiPtnFJiJFDKbtpaMg2SBW3UENnkffMS5
account addresses for B:  4c8wsALLGMWmukFaydsrHg9EvXsRoYuYnrKYxU7zmJhqdhuqFJ
xiaomi redmi note 5
Android 9 PKQ1.180904.001

**Comment by yusuftrl** [comment]
account addresses for A:  3zQikkKtFPGPBghRBT76afht8SyHKAvdtYy8JbMUSWvNHyMKAW
account addresses for B: 33G2TsnyKjDqWZCGTZCJaKQfVVsJJJtm1E8toXvy1ocxoBLgMH
HUAWEİ Y6 2019 MRD-LX1
Android 9

**Comment by boss95rnd** [comment]
1) Account name: Real1 (A): 48rfFFyiZJp5owBDi3epPdx6t4rq4PHREdfm1wG8rysLLtuKT7
2) Account name: Real2 (B): 3cBfpoPS6TXgk6niG1iDt2agxvTEYdAtPxkAoGV41auj72uMT7

Device: iPhone XS MAX
Software: IOS 13,7

**Comment by cxs13** [comment]
A: 3QaSAKg1LpmumDiU2BTUp6LBD6rtQ3WfQ2Xw7aPXSvAM8rqESL
 B: 3ggQLW5LJJ2QG3Z1AFKWNVjz1FDRZtKDrzXNUGWxshEEAz7Cj3

Device : Samsung S10
Software: Android 10

**Comment by waitrouz** [comment]
A: 4CxcsPhx7zRX73PmPAdQrj5SozBqfRxT3oTmWR41ZGNqcjMbsW
B: 43jUBpaHqNqUfcfq22oGXnRDbv8rHmDAuQbjDofw2J81g8J4vd
Android 8.1.0
#1274

**Comment by dursunalp** [comment]
ADDRESS -1 :  2wsLwUEDfMsWSFYHskf8pnLsp3NBcr2atJfs34d7dzmaLmSvni
ADDRESS -2 :  36SJtniuNgmR972Pk8xq7w39nxhfcvXvwLCP9k2JVr9LweSvAM 
Device :      İphone XS 
Software:    ios 14

**Comment by ogumogumakyak** [comment]
Account name: Oğuz (A): 38FkQTWvGwqxkGfuxzW2V3NpyLnR2PK1wVX1PPxJ6NS7gnfjd2

Account name: Oguz 2 (B): 4pAMJ5QfadmWdYNUjjyAxYH872ur9fVodiHLsQjxCNJYPoZMjz

Device: İphone 8
Software: ios 14

![image](https://user-images.githubusercontent.com/39438257/97787506-bee23300-1bc3-11eb-9a54-604e83c20bae.png)

![image](https://user-images.githubusercontent.com/39438257/97787513-c9043180-1bc3-11eb-9d24-871de73857d0.png)

![image](https://user-images.githubusercontent.com/39438257/97787520-d3263000-1bc3-11eb-9df6-7df0d5d7b4f5.png)

![image](https://user-images.githubusercontent.com/39438257/97787526-dd482e80-1bc3-11eb-8afc-4ea7c6ddd2bd.png)

**Comment by wormaxe** [comment]
ADDRESS -1 : 3HmrRPwvQMHRZkTk2WqTcxLXh7im21NNaKQT8ikMa3mbV2pmbU
ADDRESS -2 : 4YHQJs6fVGGXddaphUzmCn893rzdWEzz9VC6fpeTNSkBrwwGKz
Device : HUAWEI Y6 MRD-LX1
Software: ANDROID 9
![1](https://user-images.githubusercontent.com/65225577/97787772-4bd9bc00-1bc5-11eb-9ed1-69ca586e3245.jpg)
![2](https://user-images.githubusercontent.com/65225577/97787775-4e3c1600-1bc5-11eb-955e-9e1643dbef53.jpg)
![3](https://user-images.githubusercontent.com/65225577/97787777-51370680-1bc5-11eb-9784-42f396dcee03.jpg)
![4](https://user-images.githubusercontent.com/65225577/97787782-53996080-1bc5-11eb-8af4-59739b094320.jpg)
![5](https://user-images.githubusercontent.com/65225577/97787786-55fbba80-1bc5-11eb-8173-f0176cdca204.jpg)
![6](https://user-images.githubusercontent.com/65225577/97787789-58f6ab00-1bc5-11eb-8f7b-9baa204d538a.jpg)
![7](https://user-images.githubusercontent.com/65225577/97787793-5bf19b80-1bc5-11eb-8103-d20dc81bffac.jpg)
![8](https://user-images.githubusercontent.com/65225577/97787794-5e53f580-1bc5-11eb-9c36-60addbd57d6b.jpg)
![9](https://user-images.githubusercontent.com/65225577/97787799-6318a980-1bc5-11eb-96b9-12f5ed47d45b.jpg)
![10](https://user-images.githubusercontent.com/65225577/97787801-66ac3080-1bc5-11eb-9361-443bcc305ac8.jpg)
![11](https://user-images.githubusercontent.com/65225577/97787805-6a3fb780-1bc5-11eb-8124-a3fa359378ca.jpg)
![12](https://user-images.githubusercontent.com/65225577/97787808-6d3aa800-1bc5-11eb-8af5-eb7ce487d441.jpg)
![13](https://user-images.githubusercontent.com/65225577/97787813-73308900-1bc5-11eb-9e70-6d950e5341a1.jpg)
![14](https://user-images.githubusercontent.com/65225577/97787818-76c41000-1bc5-11eb-8023-4b9dab8599d3.jpg)

**Comment by 0011010000110010** [comment]
Address-1: 4fb6N46rqCnYkkeuhDtHMQHYpZebWixgssfPW2S9vShdTxSEjJ
Address-2: 4TEGMsBuKKLzGP7yqU1c23jmLfvKhbUuzDRSyBoFD713vbA61n
Device: Samsung Galaxy Note 9
Software: Android 10

**Comment by grkm137** [comment]
Adress A: 4iRDqDc2ZYmPBAE3FviZb8opxq761z4Cr4K8yoc2F1v7b7EXbf
Adress B: 4Bw4mPCKsriH768Jjnz8R8incFtmtNGetXbpkB9eeQAxpmBR4z
Device: Iphone X - IOS 14.0.1

**Comment by hande111** [comment]
Adress A: 4QiQxt21ASYmNvMjTeTC7QwxwEDYdQ9kMEzczFa1FnHmd76xUY
Adress B: 4ar8mGVVpUnT2cPx9g7Sxp2cMQ5yNMZGjqKcRJU4R9oQSB21Fj
Device: Iphone 7 Plus - IOS 14.0.1

**Comment by Kkemosabe** [comment]
Adress A: 3ZFGHL45RRMoppP5GJwMRgBxr9KUSXFvmntCBvs4byWKCpnL28
Adress B: 4cbHqKGGDRCj9BFbTfYXSYquHBBZQvxwAGBnpM3ytHRmRpH1WJ
Device: Iphone SE - IOS 13.5.1

**Comment by insomnium7** [comment]
Adres A: 4NNHqvi3mDMGrigFa7doiBzJD5VBVwBUzBYkSQ7gSfVnb7T89r
Adres B: 3VieeftstPKAZfeCeduMMNVMNYLetkQ5LWck1DuZa5CfkJU7Ti

OnePlus 6 Android v10

**Comment by coinalemdar** [comment]
Adress A: 4dCR2q3WJFNEDM6pS6rZvQP8Xpx42PRn1yXzp4t2fGfsutsvB8
Adress B: 4SexWiojCxTLiuttjt6K74utMhEVx4mjzkHoiRZHEoRyQ47oPq

I PHONE 8 PLUS 14.0.1

**Comment by tahacon** [comment]
Account A: 3nbToaUsMsnBbfAtD7UKmLMpCwwuo67bHRYB483xfqt2TkndF4

Account B: 4Qg9bTezgMjvYHDx1n7vqntoyKJo8v31v5HDPcbGAFSeAWUHL7

Device iPhone7 iOS 13.7

**Comment by Aslisa** [comment]
Adress A: 3WYMAVFB9evf7BagUPdACymhGDCsHmKCW71K27GbJhCoSbKdkb
Adress B: 4UuqyUgFp5C7PSmpraK3DbsDCHqdEdEf5s3EZbSASXKqCdYoD7

I PHONE 8 PLUS 14.0.1

**Comment by Aslisa** [comment]
Adress A: 3WYMAVFB9evf7BagUPdACymhGDCsHmKCW71K27GbJhCoSbKdkb
Adress B: 4UuqyUgFp5C7PSmpraK3DbsDCHqdEdEf5s3EZbSASXKqCdYoD7

I PHONE 8 PLUS 14.0.1
there is no search button at ''block explorer, so cannot put ss

**Comment by Maje53** [comment]
Adress A: 4R8LNdSKsPjMyBWBCkmB3g4jziFXbabxF3JijnnXW1fgQDq5Dt
Adress B: 4J83DmwYaWBLoGwZBehUCpq7DHU8s8Pmx51WQP5iiz4uB8gScx

Iphone 8 - iOS 14.1

**Comment by Maje53** [comment]
Adress A: 4R8LNdSKsPjMyBWBCkmB3g4jziFXbabxF3JijnnXW1fgQDq5Dt
Adress B: 4J83DmwYaWBLoGwZBehUCpq7DHU8s8Pmx51WQP5iiz4uB8gScx

Iphone 8 - iOS 14.1
![WhatsApp Image 2020-11-02 at 22 06 25](https://user-images.githubusercontent.com/71787556/97908474-cd615380-1d57-11eb-888b-a0d211a75ad6.jpeg)
![WhatsApp Image 2020-11-02 at 22 06 29](https://user-images.githubusercontent.com/71787556/97908478-ce928080-1d57-11eb-807f-fd694d5e2c6f.jpeg)
![WhatsApp Image 2020-11-02 at 22 06 32](https://user-images.githubusercontent.com/71787556/97908481-cf2b1700-1d57-11eb-9e20-75850e716577.jpeg)

**Comment by Jejda** [comment]
A: 4ad2rca5Dp6Y1KAcww3Jq3ymdNUSb33BcZanRhFReQtuj49UFb
B: 3zuPXVPFgHY3ausafHRs7BRRcLyNwbsVVkD37ZUKouqNYGQYvV
Samsung S9
Android 10

**Comment by wondayer** [comment]
A: 4L6KQrL39LBgAJyTQ191X1nj2J1iKXq4jyFS9G9VQshFiESnWt
B: 4tJp4ennWuQaRQJVm4rB83m24pCVTdwK9BYH88pTMzcuWo4dM2
A Device: Iphone 7P iOS 14.1 
B Device: realme X Android 10

Scan the code with device B. Device A cannot recognize the QR code and has no response.

**Comment by sidoroffalex** [comment]
account addresses for A: 4YchMueKfofRBt7rMQWfjnrvznPnAHCFdYpSMJM6tacXMz9U8c
account addresses for B: 4oii18LLG3iP9ZqbhD3upASQHN7MiWhY2SKu6M4CbGXDRZrR3L
Xiaomi MiA2
Android 10 QKQ1.190910.002 V11.0.15.0.QDIMIXM

**Comment by slon36** [comment]
account addresses for A: 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb
account addresses for B:  4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4
OnePlus 6T
Android 10

**Comment by MVPLA** [comment]
**account addresses for A:** 4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4
**account addresses for B:** 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb
**Device:**       OnePlus 6T
**OS version:** Android 10

**Comment by minivipers** [comment]
Account Address for A (minivipers): 46uYxDUjmLqZ9aHVNDnSUbK1MBmUm2QQubTHASLo4ak2qvpFgQ
Account Address for B (miniconcorde): 3YnrgZPb2hEWhvqaSH8n87HtsyizCcSCCW2DkP8FPHrD4JFsZP
Device : Samsung Note 8 SM-N950F/DS
OS Version: Android 9

**Comment by TravelerAnu** [comment]
Account address for angin : 3jAAeY568MpUu3as3mCe7fKu41eerRQhTm3ffjj4P5V1Ab2sg3
Account address for traveler : 4X6hzSg6XohkvHVyM2x9EKr9LUcbBw3q8E7HkbdwMJtBz1NWHm
Samsung S8+ Android 9

**Comment by SymphonyQntm** [comment]
account addresses for A: 4Pc2BQze9yVra1TWx3gU8D8tAfZ1i3myJ7DAm2U51mnzHP4bkd
account addresses for B: 4BH7FtVh9eLenNNUn9YZdKCLcDqYcmsCWzkSAckw9UDvsK3ebw
Device: Huawei P Smart
OS version: Android 9

**Comment by tugba88** [comment]
account addresses for A: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re
account addresses for B: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
Device: Samsung Galaxy S8
OS version: Android 9

**Comment by edrolu87** [comment]
account addresses for A: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
account addresses for B: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re
Device: Samsung Galaxy S8
OS version: Android 9

**Comment by yenerh** [comment]
account addresses for A: 34XQxo4bNeqtPqRYSfAn1xau6zv4ZnVjEDHyE6TNpqkKcTs9fd
account addresses for B: 4agPVmxSj58C4Z2w3Zi6YYv1F5H1tK3nAMBau8948MUc18WRwv
Device: Xiaomi Redmi Note 8
OS version: Android 10
