### ISSUE TITLE
(T2) Use Concordium Client to send and receive GTU

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1118]
**Mission:**
- create or reuse identity (mobile wallet Concordium ID)
- create or reuse accounts A and B (mobile wallet Concordium ID)
- export identities and accounts from the mobile wallet Concordium ID
- import id and accounts to the Concordium Client

**Using Concordium Client:**
- transfer 3 GTU from account A to account B
- shield 10 GTU of account A
- transfer 7 GTU from the shielded balance on account A to B
- unshield shielded balance on account B
- check transfers in the respective block on the network dashboard

_Note that all transfers come with a fee to be paid from the general balance, so please make sure, you have enough money on the general balance of the accounts. Otherwise, you might want to create a new account an get a new GTU drop. See [Transfer Fees](https://github.com/Concordium/Testnet3-Challenges/wiki/Transfer-Fees) for more details._

**Submission:** 
- submit account addresses for A and B
- submit screenshots of the block explorer on the network dashboard with transfer details (see wiki to find [block explorer](https://github.com/Concordium/Testnet3-Challenges/wiki/Block-Explorer))

**Comment by boss95rnd** [comment]
1) Account: Real1 (A): 48rfFFyiZJp5owBDi3epPdx6t4rq4PHREdfm1wG8rysLLtuKT7
2) Account: Real2 (B): 3cBfpoPS6TXgk6niG1iDt2agxvTEYdAtPxkAoGV41auj72uMT7

<img width="1617" alt="Step 1 and 2" src="https://user-images.githubusercontent.com/72925068/97776532-33d44f00-1b69-11eb-822e-99b8049e3577.png">
<img width="1613" alt="Step 3" src="https://user-images.githubusercontent.com/72925068/97776531-333bb880-1b69-11eb-933c-38cdbc8a9d11.png">
<img width="1627" alt="Step 4" src="https://user-images.githubusercontent.com/72925068/97776530-2fa83180-1b69-11eb-902c-c9957cd3b842.png">

**Comment by dursunalp** [comment]
Account   1  :  2wsLwUEDfMsWSFYHskf8pnLsp3NBcr2atJfs34d7dzmaLmSvni
Account   2  :  36SJtniuNgmR972Pk8xq7w39nxhfcvXvwLCP9k2JVr9LweSvAM
![02e7a176-5772-411d-a6ef-d4287caa45b2](https://user-images.githubusercontent.com/73360909/97802965-fe5a5f00-1c57-11eb-93b4-8d264f130f3b.jpg)

**Comment by insomnium7** [comment]
Adres A: 4NNHqvi3mDMGrigFa7doiBzJD5VBVwBUzBYkSQ7gSfVnb7T89r
Adres B: 3VieeftstPKAZfeCeduMMNVMNYLetkQ5LWck1DuZa5CfkJU7Ti
![concor1](https://user-images.githubusercontent.com/3042763/97808752-b51b0700-1c79-11eb-95f7-6d034ab4ad31.jpg)

![concor2](https://user-images.githubusercontent.com/3042763/97808765-c532e680-1c79-11eb-9ce3-17a9dc0b56a1.jpg)



OnePlus 6 Android v10

**Comment by tahacon** [comment]
Account A: 3nbToaUsMsnBbfAtD7UKmLMpCwwuo67bHRYB483xfqt2TkndF4

Account B: 4Qg9bTezgMjvYHDx1n7vqntoyKJo8v31v5HDPcbGAFSeAWUHL7

Step1:
<img width="1134" alt="1" src="https://user-images.githubusercontent.com/72972420/97809248-dfba8f00-1c7c-11eb-8e80-298506cf5b05.png">

Step2:
<img width="1109" alt="2" src="https://user-images.githubusercontent.com/72972420/97809255-e6e19d00-1c7c-11eb-9594-de657a7e8cf3.png">

Step3:
<img width="1122" alt="3" src="https://user-images.githubusercontent.com/72972420/97809261-eba65100-1c7c-11eb-8e58-b3dd6ce870fd.png">

Step4:
<img width="1108" alt="4" src="https://user-images.githubusercontent.com/72972420/97809266-f06b0500-1c7c-11eb-8a0d-587698e2bf68.png">





Device iPhone7 iOS 13.7

**Comment by coinalemdar** [comment]
Adress A: 4dCR2q3WJFNEDM6pS6rZvQP8Xpx42PRn1yXzp4t2fGfsutsvB8
Adress B: 4SexWiojCxTLiuttjt6K74utMhEVx4mjzkHoiRZHEoRyQ47oPq

I PHONE 8 PLUS 14.0.1

there is no search button at ''block explorer, so cannot put ss

**Comment by dewrin** [comment]
Account 1: 3LgY9wdir7qHJXvRUNtQKgCVw9weqp5reuMBZsGajdgA1Mnu5a
Account 2: 3qTjvCCwLwEbCx3mLAHxa7W1U3AGovt6GohfQ6qBGv3AjWcjdm
![Uploading Screenshot_2020-11-02-06-28-01-782_com.concordium.wallet.jpg…]()

**Comment by Maje53** [comment]
![WhatsApp Image 2020-11-02 at 22 06 25](https://user-images.githubusercontent.com/71787556/97937646-4d0b1480-1d90-11eb-8732-8be847871e8e.jpeg)
![WhatsApp Image 2020-11-02 at 22 06 29](https://user-images.githubusercontent.com/71787556/97937647-4da3ab00-1d90-11eb-8e09-685116ac28fb.jpeg)
![WhatsApp Image 2020-11-02 at 22 06 32](https://user-images.githubusercontent.com/71787556/97937649-4e3c4180-1d90-11eb-99a4-3d4033726118.jpeg)

Account A: 4R8LNdSKsPjMyBWBCkmB3g4jziFXbabxF3JijnnXW1fgQDq5Dt
Account B: 4J83DmwYaWBLoGwZBehUCpq7DHU8s8Pmx51WQP5iiz4uB8gScx

**Comment by slon36** [comment]
account addresses for A: 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb
account addresses for B: 4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4
Device: OnePlus 6T

- OS version:

 Android 10

**Comment by MVPLA** [comment]
- account addresses for A: 4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4
- account addresses for B: 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb
- Device: OnePlus 6T
- OS version: Android 10

**Comment by edrolu87** [comment]
account addresses for A: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
account addresses for B: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re
Step - 1
![edrolustep1](https://user-images.githubusercontent.com/73315597/98465811-3f142400-21d4-11eb-9227-1d16c4857005.PNG)
Step - 2
![edrolustep2](https://user-images.githubusercontent.com/73315597/98465814-49362280-21d4-11eb-8f88-4a1a41abd02f.PNG)
Step - 3
![edrolustep3](https://user-images.githubusercontent.com/73315597/98465818-4f2c0380-21d4-11eb-8f76-13561b70df08.PNG)
Step - 4
![edrolustep4](https://user-images.githubusercontent.com/73315597/98465826-581cd500-21d4-11eb-9725-327b66fb3cf1.PNG)

**Comment by tugba88** [comment]
account addresses for A: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re
account addresses for B: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
Step - 1
![Step1](https://user-images.githubusercontent.com/73640380/98466303-6a4c4280-21d7-11eb-9642-7f6156f6b002.PNG)
Step - 2
![Step2](https://user-images.githubusercontent.com/73640380/98466308-70422380-21d7-11eb-9556-5ab474f8f4dd.PNG)
Step - 3
![Step3](https://user-images.githubusercontent.com/73640380/98466313-76d09b00-21d7-11eb-96cf-830a4fd523d7.PNG)
Step - 4
![Step4](https://user-images.githubusercontent.com/73640380/98466319-7f28d600-21d7-11eb-8f38-d6ef65fd4166.PNG)
