### ISSUE TITLE
(T3) Bulk transactions with Concordium Client

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1119]
**Mission:**
- create or reuse identity (mobile wallet Concordium ID)
- create or reuse accounts (mobile wallet Concordium ID)

**Using Concordium Client:**
- send 1000 transfers, one immediately after the other

_Note that all transfers come with a fee to be paid from the general balance, so please make sure, you have enough money on the general balance of the accounts. Otherwise, you might want to create a new account an get a new GTU drop. See [Transfer Fees](https://github.com/Concordium/Testnet3-Challenges/wiki/Transfer-Fees) for more details._

**Submission:**
- submit account addresses
- submit transaction IDs, or alternatively, time period when the transactions were sent

**Comment by cemuney** [comment]
"send **1000** transfers, one immediately after the other" 
How can we make 1000 transaction one by one. it asks password every time. 
Is there any way sending without password from client?
Thanks

**Comment by iekmuby** [comment]
`#!/usr/bin/expect

set receiver "***"
set sender "***"
set pass "***\n"

set timeout -1

spawn ./concordium-client transaction send-gtu --receiver $receiver --amount 0.1 --sender $sender --expiry 3m --no-confirm --no-wait

expect "Enter password"
send $pass
expect eof`

**Comment by Adelfinabuzdyak** [comment]
> "send **1000** transfers, one immediately after the other"
> How can we make 1000 transaction one by one. it asks password every time.
> Is there any way sending without password from client?
> Thanks
```
#!/usr/bin/expect

set receiver "***"
set sender "***"
set pass "***\n"

set timeout -1

spawn ./concordium-client transaction send-gtu --receiver $receiver --amount 0.1 --sender $sender --expiry 3m --no-confirm --no-wait

expect "Enter password"
send $pass
expect eof
```

**Comment by Adelfinabuzdyak** [comment]
```
!/bin/bash
receiver="***"
sender="***"
pass="***\n"
for i in {1..1000}
do
   /usr/bin/expect << EOF
set timeout -1

spawn ./concordium-client transaction send-gtu --receiver $receiver --amount 0.1 --sender $sender --expiry 3m --no-confirm --no-wait

expect "Enter password"
send $pass

EOF
done
```

**Comment by Adelfinabuzdyak** [comment]
Complete script for 1000 transactions.

**Comment by cemuney** [comment]
> ```
> #!/bin/bash
> receiver="***"
> sender="***"
> pass="***\n"
> for i in {1..1000}
> do
>    /usr/bin/expect << EOF
> set timeout -1
> 
> spawn ./concordium-client transaction send-gtu --receiver $receiver --amount 0.1 --sender $sender --expiry 3m --no-confirm --no-wait
> 
> expect "Enter password"
> send $pass
> 
> EOF
> done
> ```

Thanks but we need to grap transactionI Ds to send for T3 can we log them with your script.
Something like "cat tx-out.log | grep "Transaction is finalized into block" > blocks.log"

**Comment by EmreNOP** [comment]
Here is the mine version. 
https://github.com/EmreNOP/Testnet3-Challenges/tree/main/Transactions/T3

$ cat expect 
#!/usr/bin/expect -f
set timeout -1


spawn ./concordium-client  transaction send-gtu --sender "Prod account 1" --amount 0.1 --receiver "Prod account 2" --no-confirm
expect "Enter password for signing key:"

send -- "xxxxx\r"

expect eof
$ cat send.sh 
#!/bin/bash

for i in {1..1000}
do
	echo "Run $i"
	./expect >> tx-out.log
done

cat tx-out.log | grep "Transaction is finalized into block" > blocks.log
cat tx-out.log | grep "Transaction '" > txs.log

**Comment by concordium-admin** [comment]
I've updated the submission content; no logs anymore.
