### ISSUE TITLE
(T4) Shielded transfers with Concordium Client over a longer period

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1120]
**Mission:**
- create or reuse identity (mobile wallet Concordium ID)
- create or reuse accounts (mobile wallet Concordium ID)

**Using Concordium Client:**
- Send and receive shielded transfers, i.e. transfers from the shielded balance:
   -- 10 times per hour
   -- 3 times a day 
   -- 5 days
- **Transfers must be shielded and successful to count.**

_Note that all transfers come with a fee to be paid from the general balance, so please make sure, you have enough money on the general balance of the accounts. Otherwise, you might want to create a new account an get a new GTU drop. See [Transfer Fees](https://github.com/Concordium/Testnet3-Challenges/wiki/Transfer-Fees) for more details._

**Submission:**
- submit account addresses

**Comment by concordium-admin** [comment]
I've updated the submission content; no logs anymore.

**Comment by dursunalp** [comment]
Account 1 : 2wsLwUEDfMsWSFYHskf8pnLsp3NBcr2atJfs34d7dzmaLmSvni
Account 2 : 36SJtniuNgmR972Pk8xq7w39nxhfcvXvwLCP9k2JVr9LweSvAM

**Comment by Aysealp** [comment]
Account 1 :    3mVA2fLyKXHMJUk2dMaSCGVrdyXxzTbkMkGeTYhaqu3p5EEenW
Account 2 :    37KhTWomBrEz8h479t5NxWsoro6qGagVYnfdYGkoCg2Rh4VDAM

**Comment by insomnium7** [comment]
Adres A: 3VieeftstPKAZfeCeduMMNVMNYLetkQ5LWck1DuZa5CfkJU7Ti
Adres B: 4NNHqvi3mDMGrigFa7doiBzJD5VBVwBUzBYkSQ7gSfVnb7T89r

**Comment by tahacon** [comment]
Account A: 3nbToaUsMsnBbfAtD7UKmLMpCwwuo67bHRYB483xfqt2TkndF4

Account B: 4Qg9bTezgMjvYHDx1n7vqntoyKJo8v31v5HDPcbGAFSeAWUHL7

**Comment by Maje53** [comment]
Acc A: 4R8LNdSKsPjMyBWBCkmB3g4jziFXbabxF3JijnnXW1fgQDq5Dt
Acc B: 4J83DmwYaWBLoGwZBehUCpq7DHU8s8Pmx51WQP5iiz4uB8gScx

**Comment by boss95rnd** [comment]
Account 1 (Sender): 4rUoNHiJ8TYPsfAMACeoFyFGyzviBBRsx3BfvoKo1ACRvZNC6k

Account 2 (Receiver): 48rfFFyiZJp5owBDi3epPdx6t4rq4PHREdfm1wG8rysLLtuKT7

**Comment by gokmenkutuk** [comment]
Does the time zone matter?

**Comment by SymphonyQntm** [comment]
account addresses for A: 4Pc2BQze9yVra1TWx3gU8D8tAfZ1i3myJ7DAm2U51mnzHP4bkd
account addresses for B: 4BH7FtVh9eLenNNUn9YZdKCLcDqYcmsCWzkSAckw9UDvsK3ebw

**Comment by tugba88** [comment]
account addresses for A: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re
account addresses for B: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ

**Comment by edrolu87** [comment]
account addresses for A: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
account addresses for B: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re

**Comment by yenerh** [comment]
Account 1 : 34XQxo4bNeqtPqRYSfAn1xau6zv4ZnVjEDHyE6TNpqkKcTs9fd
Account 2 : 4agPVmxSj58C4Z2w3Zi6YYv1F5H1tK3nAMBau8948MUc18WRwv

**Comment by yenerh** [comment]
account addresses for A: 34XQxo4bNeqtPqRYSfAn1xau6zv4ZnVjEDHyE6TNpqkKcTs9fd
account addresses for B: 4agPVmxSj58C4Z2w3Zi6YYv1F5H1tK3nAMBau8948MUc18WRwv
