### ISSUE TITLE
Have problems with B6 logs

### ISSUE THREAD

**Issue by andrste** [Concordium/Testnet3-Challenges#1177]
The problem is that I retrieved logs when the new tool wasn't introduced, so I was doing what I have at that moment used command `concordium-node-retrieve-logs`. 

It retrieved successfully and generated `concordium-testnet-system-report.log` file too, if it would fail I couldn't generate any log at all. So after generated logs, I've downloaded them to my computer and deleted VPS, because I was using VPS / challenge. 

And I was waiting for the new instructions on how to submit our logs, and I see Concordium team publish a new tool to retrieve these logs, but the problem that I had no VPS and only have logs. 

And another problem that with this command `concordium-node-retrieve-logs` it didn't retrieved full log, it just cut off at some point... and from log it shows that I ran only for 5 days, even I was running for full 7 days. Log weights ~2.0Gb. 

I hope I will be able to participate on B6 challenge, because now is too late to start from scratch.

My Pull request number is: #533

**Comment by concordium-admin** [comment]
Hi andrste, if we can see in the log you submitted that your node ran for 5 days, we'll accept the submission.

**Comment by andrste** [comment]
@concordium-admin thank you for understanding!

**Comment by concordium-admin** [comment]
@andrste: FYII have added the comment above also to your pull request.
