### ISSUE TITLE
account name characters problem

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1239]
my account name : Mehmet öncel

example charecter : ö, ı , ş, ü .... vs

"./concordium-client -v config account import export.concordiumwallet"
when i run the code i get character error.  I cannot add my other accounts.

![Adsız6](https://user-images.githubusercontent.com/73251385/97677352-30769000-1aa3-11eb-9e9d-60d8d9b28ebe.png)

**Comment by concordium-admin** [comment]
Hi donadel01, this is an interesting finding. We have worked in this area before launch and made some improvements but it seems your case has slipped our analysis and test.

Unfortunately, I don't know of any workaround for your scenario but to start from scratch, i.e. reinstall the app (to delete all data), create new accounts without Turkish letters, export and import.

Thanks for submitting!!

**Comment by donadel01** [comment]
Thank you. Will I get a reward for this?

**Comment by donadel01** [comment]
:+1:

**Comment by concordium-admin** [comment]
Related to https://github.com/Concordium/Testnet3-Challenges/issues/1328.

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
