### ISSUE TITLE
logging problem

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1250]
Code : 
wget https://client-distribution-testnet.concordium.com/retrieve_minified_logs-linux-v1
chmod +x retrieve_minified_logs-linux-v1
./retrieve_minified_logs-linux-v1

Text entered by right mouse click on Putty by mistake created a log record. It gives an error due to the Turkish characters in the log record created.  This situation can be encountered frequently.

![30](https://user-images.githubusercontent.com/73251385/97700777-6e80ad80-1abd-11eb-8789-b9b23d7af01f.png)

**Comment by supermario** [comment]
Thanks @donadel01 – would you be able to copy paste that terminal text instead of the screenshot? It's unclear why this text is appearing in your logs.

A sample of your logs would also be helpful if possible, i.e. `./concordium-node-retrieve-logs | head -n 10000` and sending us that file.

**Comment by donadel01** [comment]
`$ ./concordium-node-retrieve-logs | head -n 10000
Now beginning to extract logs. This might take a long time depending on how long the client has been running for

memory allocation of 536870912 bytes failedAborted (core dumped)
$ ./retrieve_minified_logs-linux-v1
Now beginning to extract logs. This might take a long time depending on how long the client has been running for

thread 'main' panicked at 'byte index 30 is not a char boundary; it is inside 'ş' (bytes 29..31) of `Boyasız göçük düzeltme işlemi esnasında aracın daha fazla zarar almaması adına özel gereçlere gerek duyulabilir. Boyasız göçük düzeltmede en çok kullanılan malzemelerden biri de uzun çubuklardır. Uzun çubuklar yardımıyla göçüğü`[...]', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1987:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
`
The file given by ./retrieve_minified_logs-linux-v1 code is added.
[concordium-testnet-node.log](https://github.com/Concordium/Testnet3-Challenges/files/5476196/concordium-testnet-node.log)
