### ISSUE TITLE
Transfer Problem

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1292]
code : ./concordium-client transaction send-gtu-encrypted --sender T1 --receiver T2 --amount 0.1

I ran the transfer code. I accidentally clicked the letter **"y"** without the confirmation, but the transfer was not made, despite my confirmation.

![33](https://user-images.githubusercontent.com/73251385/97784010-9438b000-1bac-11eb-81c3-246ec932fb8a.png)

**Comment by concordium-admin** [comment]
Hi donadel01, the client probably takes "yy" as input without writing it out. I've reproduced your issue and created an internal bug report. Thanks for submitting!

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
