### ISSUE TITLE
0 GTU TRANSFER

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1303]
CODE : ./concordium-client transaction send-gtu --amount 0 --sender T1 --receiver T2

0 gtu can be sent with other transfer codes. 0 GTU should not be transferred

https://dashboard.testnet.concordium.com/chain/75ccf15aa61017ea2969d0bb467699d979dde7b45c15ef0f7b2bd28a4a841f2d

![44](https://user-images.githubusercontent.com/73251385/97790354-1b9c1880-1bd9-11eb-8ac8-c8804b2390c7.png)

**Comment by concordium-admin** [comment]
Hi donadel01, we do not want to check if the amount is strictly higher than 0. It might not be meaningful to do so and it also costs the regular transaction fee. However, we do not have plans to restrict that right know. But thanks for submitting!
