### ISSUE TITLE
LOSS OF INSUFFICIENT BALANCE WARNINGS

### ISSUE THREAD

**Issue by okannako** [Concordium/Testnet3-Challenges#1327]
If there is not enough balance in your wallet account, it keeps waiting on the code screen because the transfer is being made and does not show a warning such as no balance, etc. I noticed this error today.

CODE: ./concordium-client transaction send-gtu-encrypted --receiver "okan2" --amount 0.1 --sender "okan"

![1](https://user-images.githubusercontent.com/73176377/97813306-4305ea80-1c98-11eb-8b76-3f80ea2eecb3.JPG)

**Comment by concordium-admin** [comment]
Hi okannako, 

actually in your case the transaction was successful:
![transfer2](https://user-images.githubusercontent.com/69570978/97883601-5e6b0700-1d25-11eb-8f29-9f6097ff39d2.JPG)

![transfer](https://user-images.githubusercontent.com/69570978/97883608-6034ca80-1d25-11eb-8cd1-a9943cf95e3b.JPG)

However, you are right that if you hadn't enough general balance, the transaction would be "pending" until it would become  "absent", without an error message to the user, which is inconvenient. I have created an internal improvement suggestion for it. 

Thanks for submitting!

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
