### ISSUE TITLE
Character problem in Gtu transfer

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1328]
Account Name: Mehmet öncel

Code: ./concordium-client transaction send-gtu --amount 25 --sender Mehmet öncel --receiver T2
The names of the login accounts opened give errors other than Latin, and there is a problem all over the software.

![77](https://user-images.githubusercontent.com/73251385/97815536-c8d96400-1c9f-11eb-9d94-d1b8bd4ceb15.png)

**Comment by concordium-admin** [comment]
Hi donadel01, another interesting find, related to your previous issue https://github.com/Concordium/Testnet3-Challenges/issues/1239. It should not be possible to use these special language characters when naming an account in the app, which would solve both problems. I have created an internal bug report for both issues.

Thanks for submitting!

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
