### ISSUE TITLE
TRANSFER FROM A ACCOUNT TO A

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1334]
CODE : ./concordium-client transaction send-gtu --amount 1 --sender T1 --receiver T1

Transfers can be made from A to A.

https://dashboard.testnet.concordium.com/chain/a5c191a49c15089c016c2386f9dbb0f2641ba1ba37cea8aa32baf15356149d7b

![88](https://user-images.githubusercontent.com/73251385/97843324-28645d80-1cfa-11eb-98ec-f25b9a8ec818.png)

**Comment by concordium-admin** [comment]
Hi donadel01, wow, you're testing quite thoroughly! Thanks!

While it is not "wrong" nor causes troubles, we might consider aligning the client to the app in this scenario. There it is not possible to transfer to the same account. I have created an internal improvement report.

Thanks for submitting!

**Comment by concordium-admin** [comment]
Transactions in client from A to A needed; won't fix.
