### ISSUE TITLE
T4 Challenge issue when transfering.

### ISSUE THREAD

**Issue by andrste** [Concordium/Testnet3-Challenges#1336]
Hello, I am doing a T4 challenge and was running from October 30th. it just was transferring successfully from shielded A account to shielded B account. Had no issues till today morning November 2nd.

My command: `./concordium-client transaction send-gtu-encrypted --receiver 3ChifyK369cRTiSFUUxMvBYzbyCH3TAYPGpkjYybQ24ib29V3B --amount 0.35 --sender 45bfqjei4fQa981qLji1mxdvi8AMi7nKTqs5VuHAJsqaTdKkUU --no-confirm`

Balance on shielded A account: 966,36 GTU
Balance on shielded B account: 51,64 GTU

Screenshot:
![screen](https://user-images.githubusercontent.com/20327738/97875837-a4bf6680-1d23-11eb-870c-2b40a8ec789d.jpg)

**Comment by andrste** [comment]
Tried another transaction, same situation but shows that pending 2232 transaction nonce:

![screen2](https://user-images.githubusercontent.com/20327738/97877585-100a3800-1d26-11eb-8299-aa33b517626d.jpg)

**Comment by ab-concordium** [comment]
It looks like you're in a state where a transaction was invalid for some reason, but is still retained by your node. In particular it might be that transaction with nonce 2233 is missing for some reason.

Can you try forcing the nonce to be 2233 with your new transaction. You can supply the nonce via `--nonce` flag to the concordium client.

**Comment by andrste** [comment]
@ab-concordium Thank you for reply the problem was insufficient balance on non shielded account.
