### ISSUE TITLE
T4 Challenge insufficience balance

### ISSUE THREAD

**Issue by andrste** [Concordium/Testnet3-Challenges#1351]
Hi, I've started a T4 challenge. And on 2020-11-02 saw that from morning I am not receiving from A to B shielded accounts. After that I noticed that I have not enough balance on A account, even on shielded account I had enough (my issue was here: https://github.com/Concordium/Testnet3-Challenges/issues/1336 ).
Now when I finished the task I saw that on 2020-11-01 at 19:00 UTC just sent 5 tx instead of 10 tx because from earlier issue about insufficient balance on sender A account. 

Now question do I need to start from the beginning?

Started from 2020-10-30 till 2020-11-03

2020-10-30 9:00 UTC 10tx
2020-10-30 14:00 UTC 10tx
2020-10-30 19:00 UTC 10tx

2020-10-31 9:00 UTC 10tx
2020-10-31 14:00 UTC 10tx
2020-10-31 19:00 UTC 10tx

2020-11-01 9:00 UTC 10tx
2020-11-01 14:00 UTC 10tx
2020-11-01 19:00 UTC only 5 transactions, because of insufficient balance.

2020-11-02 22:00 UTC 10tx
2020-11-02 19:00 UTC 10tx
2020-11-02 17:00 UTC 10tx

2020-11-03 9:00 UTC 10tx
2020-11-03 11:00 UTC 10tx
2020-11-03 13:00 UTC 10tx

**Comment by concordium-admin** [comment]
Hi andrste, no, you don't need to start again. If we can later validate that the above transactions were made successfully, your submission will be accepted.

**Comment by andrste** [comment]
Thanks @concordium-admin I have logs with all tx and I see on my wallet all transactions, thats how I saw that is missing for 5 tx on Nov. 1d. :)

**Comment by alkadeta** [comment]
I too have the same problem, insufficient balance, but my transactions are stuck right now and can't send or receive from shielded balance. To my chance my issue occured on last day of the challenge.

**Comment by concordium-admin** [comment]
@andrste, @alkadeta, I have added a comment to your pull request that T4 will be accepted even without all 10 transactions completed on a single day.

**Comment by alkadeta** [comment]
> @andrste, @alkadeta, I have added a comment to your pull request that T4 will be accepted even without all 10 transactions completed on a single day.

Just seen it. Thank you 👏
