### ISSUE TITLE
Database Problem

### ISSUE THREAD

**Issue by ilhamm24** [Concordium/Testnet3-Challenges#1429]
I cant access dashboard and see the log. I got this error
```2020-11-06T03:44:59.334219531Z: ERROR: TreeState: Database invariant violation: Could not read last finalized block
2020-11-06T03:44:59.334687343Z: ERROR: External: Database invariant violation: Could not read last finalized block
Error: ErrorMessage { msg: "Database invariant violation. See logs for details." }```

**Comment by ab-concordium** [comment]
This indicates that the node's database where it stores transactions, blocks, and other data, is corrupt.

From the provided message it is unclear why it became corrupt, but the most common reasons are that you ran out of disk space, or the node shut down in an in irregular way (e.g., was killed).

The only solution at the moment is to delete the database. You can do that in two ways
- concordium-node-reset-data, but be warned that this will also delete all the logs.
- manually remove the database. The location of this is platform dependent. On Linux it is typically `$HOME/.local/share/concordium/database-v3`.

**Comment by concordium-admin** [comment]
No further analysis possible without logs.
