### ISSUE TITLE
Warning: There is a pending transaction with nonce 1157, but last committed one has 1154.  This transaction will have nonce 1158 and might hang if the pending transaction fails.

### ISSUE THREAD

**Issue by alkadeta** [Concordium/Testnet3-Challenges#1476]
I've got an error that says: Warning: There is a pending transaction with nonce 1157, but last committed one has 1154.
This transaction will have nonce 1158 and might hang if the pending transaction fails.

I was doing  the t4 task with a script. I've sent 10 transaction in 3 different times in 1 hour for 4 days, in my last day which is 5th day of challenge script stopped working after 14 transactions and failed to send it
Then when i try to send it manually via client encrypted transaction, i had this error that says: There is a pending transaction with nonce 1157, but last committed one has 1154. This transaction will have nonce 1158 and might hang if the pending transaction fails. It isn't finishing the transaction.
![chrome_noPqHkBdTL](https://user-images.githubusercontent.com/72661026/98454186-bc0eb180-2172-11eb-9c60-bf81dbac5316.png)

**Comment by alkadeta** [comment]
My bad, my sender account's funds were empty after 4 days of spending sending fees. This was the issue, solved it now.

**Comment by ZloyMyshok** [comment]
fill in the balance

**Comment by alkadeta** [comment]
doesn't linked to that. its solved now tho all of a sudden
