### ISSUE TITLE
Commit & Pull Req Template

### ISSUE THREAD

**Issue by CyberSensei1** [Concordium/Testnet3-Challenges#149]
Is there any template for commiting and pull request.
I will commit my responses but if i do it wrong you will not accept without a template we will see a lot of conflict on the repository.
  
Please share a template for commiting and pull requests. @concordium-admin @bissembert1618

**Comment by devrimdanyal** [comment]
I totally agree with dear CyberSensei

**Comment by andrste** [comment]
Thank you! Do we need to pull with different branches?

**Comment by samiaraboglu** [comment]
Exactly. That's why I created the file name as "b4 submission samiaraboglu", "id2 submission samiaraboglu"...

**Comment by trancetr** [comment]
Thank you

**Comment by concordium-admin** [comment]
There isn't and won't be a template for submissions. The submission content is given in each challenge. The rest should be chosen according to common sense.

We have also updated our FAQs: https://github.com/Concordium/Testnet3-Challenges/issues/323
