### ISSUE TITLE
My node disappered on general dashboard

### ISSUE THREAD

**Issue by cryuwan** [Concordium/Testnet3-Challenges#1514]
At the 25th or 26th of its running period my node is not listed on the general dashboard. I checked it out with /node/<nodeID> too but it is stated 'Unknown node ID'. 
Meanwhile I have checked out my node ID:8099 and saw that the node is still working in its 26th day. 
I have connected to the VPS that I am running the node and tried to do some transections on concordium.client. I have tried two transections; first one between the accounts connected to the node and it was finalized successfully. 
Then I found a random concordium account adress on git hub and sent a transection to that address it was also finalized successfully. 
Now the node is still not shown on dashboard. 
I am sending screenshots. 

![Another random tx](https://user-images.githubusercontent.com/72798897/98577735-6d295f00-22cd-11eb-8864-e373063db559.JPG)
![Baker problem](https://user-images.githubusercontent.com/72798897/98577737-6e5a8c00-22cd-11eb-9f96-07a2eca50da5.JPG)
![Jasebel D26](https://user-images.githubusercontent.com/72798897/98577739-6ef32280-22cd-11eb-8ba0-56f27b2c9904.JPG)
![Node is not found](https://user-images.githubusercontent.com/72798897/98577741-6ef32280-22cd-11eb-9bdc-d568764b3ed5.JPG)
![Tx ](https://user-images.githubusercontent.com/72798897/98577742-6f8bb900-22cd-11eb-89d0-860602314100.JPG)

**Comment by concordium-admin** [comment]
Discussion ongoing in same issue reported to email support. Will close report here.
