### ISSUE TITLE
(EI2) Export from iOS / Import to Android

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1526]
**Mission:**
- export identities, accounts, and address book from an iOS-based mobile phone
- import the export file to an Android phone
- verify the identities
- verify the accounts
- verify the address book

**Submission:** 
- screenshots from both platforms with clear details

**Unexpected Behavior:**
If you experience any unexpected behavior, please check known issues with label **export_import** under 
[Bugs](https://github.com/Concordium/Testnet3-Challenges/projects/2) and 
[FAQs](https://github.com/Concordium/Testnet3-Challenges/projects/3).

If your issue is not yet listed, please submit a bug report via [Bugs](https://github.com/Concordium/Testnet3-Challenges/projects/2) or testnet@concordium.com (to send attachments), thanks! It is crucial that you include
- a clear description
- expected result 
- actual result
- exported wallet file
- export password
- platform and OS of export device
- platform and OS of import device.

**Comment by erknfe** [comment]
Since I do not have an Android device, I installed the Concordium ID apk on Bluestacks. I try to set the password on the first run, but I get "Failed to setup password" error.

![b1](https://user-images.githubusercontent.com/7534459/98667203-271cdb80-235f-11eb-85a3-b7b36fe9cdd7.png)
