### ISSUE TITLE
(EI4) Export from Android / Import to Android

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#1528]
**Mission:**
- export identities, accounts, and address book from an Android phone
- reinstall the mobile wallet Concordium ID or switch device
- import the export file
- verify the identities
- verify the accounts
- verify the address book

**Submission:** 
- screenshots from both platforms with clear details

***Unexpected Behavior:**
If you experience any unexpected behavior, please check known issues with label **export_import** under 
[Bugs](https://github.com/Concordium/Testnet3-Challenges/projects/2) and 
[FAQs](https://github.com/Concordium/Testnet3-Challenges/projects/3).

If your issue is not yet listed, please submit a bug report via [Bugs](https://github.com/Concordium/Testnet3-Challenges/projects/2) or testnet@concordium.com (to send attachments), thanks! It is crucial that you include
- a clear description
- expected result 
- actual result
- exported wallet file
- export password
- platform and OS of export device
- platform and OS of import device.

**Comment by Karim-betta** [comment]
Export from Android / Import to Android
![karim3](https://user-images.githubusercontent.com/74362404/98969877-946f6e80-250f-11eb-8f60-118b47572919.jpeg)
![karim2](https://user-images.githubusercontent.com/74362404/98969881-95080500-250f-11eb-951f-aa5873059544.jpeg)
![Karim1](https://user-images.githubusercontent.com/74362404/98969882-95a09b80-250f-11eb-9bef-8b3e731dcf0f.jpeg)
