### ISSUE TITLE
Can’t export wallet on Android which was imported from iOS

### ISSUE THREAD

**Issue by andrste** [Concordium/Testnet3-Challenges#1655]
## Issue:
Wallet which was earlier imported from iOS to Android, trying to export from Android it restarts the app.

## Devices were used:

**Device:** iPhone 7 
**iOS version:** 14.2

**Device:** Redmi Note 9 Pro, 
**Android version:** 10 QKQ1.191215.002

## My actions:

After I imported wallet from iOS to Android on challenge EI2, with the same imported wallet from iOS I started doing EI3 challenge where you need to export wallet from Android and import to iOS.

1. After imported wallet from iOS I clicked on More button at the bottom and selected Export.
2. It prompted to enter passcode.
3. After entering passcode it asks to create export password and re-enter export password.
4. After re-entering export password I clicked on the button continue which is at the bottom and it rebooted the app.

How I noticed that app is restarting is that after making an export action it shows again “Concordium log” and then ask to enter passcode.

## Steps to reproduce error:

1. On iOS app click on button more and select export.
2. Enter export password and then re-enter export password. Click on button continue it will prompt where to save. As there is no direct bluetooth connection between iOS & Android, I had to send exported from iOS wallet through gmail and import to Android.
3. On Android import wallet by entering export password, it will import wallet without any issues.
4. To export wallet, click on Export, create export password and click continue.
5. After clicked continue button, app is restarting.

## What I tried:

1. On iOS create identity, create account and select recent identity.
2. Request GTU balance, it will give 1000GTU.
3. Export wallet and import to Android device.
4. Trying to export it restarts again.

## Screenshots with steps:

![1](https://user-images.githubusercontent.com/20327738/99181110-14c2e900-2735-11eb-9d2e-8b548d16b3ef.jpg)
![2](https://user-images.githubusercontent.com/20327738/99181117-17bdd980-2735-11eb-8bae-d053bb701fa9.jpg)
![3](https://user-images.githubusercontent.com/20327738/99181119-18567000-2735-11eb-8c95-ebbf7cb52b6a.jpg)
![4](https://user-images.githubusercontent.com/20327738/99181123-18ef0680-2735-11eb-8a6b-01f62003361d.jpg)
![5](https://user-images.githubusercontent.com/20327738/99181124-19879d00-2735-11eb-8d2c-7868e6503d59.jpg)
![6](https://user-images.githubusercontent.com/20327738/99181125-19879d00-2735-11eb-8f74-15b2f8623de8.jpg)
![7](https://user-images.githubusercontent.com/20327738/99181126-1a203380-2735-11eb-9521-207155a06ec9.jpg)

**Comment by concordium-admin** [comment]
Thanks for the detailed report, andrste! I will try to reproduce it to better understand the issue.

**Comment by andrste** [comment]
@concordium-admin thanks will be waiting for your response.

**Comment by concordium-admin** [comment]
Hi andrste, we could reproduce it here. I will create an internal ticket for us to fix it. Your submission will get accepted of course.

Thanks again. We appreciate it very much!

**Comment by andrste** [comment]
Hey I am glad to help you ;)

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
