### ISSUE TITLE
Error on the dashboard when trying to see the content of "set-account" and "set-keys" blocks

### ISSUE THREAD

**Issue by greyheaven** [Concordium/Testnet3-Challenges#1667]
I completed my B5 challenge and created pull request for it 2-3 weeks ago. 

**_B5 Missions:_**
**_1. run a node (or reuse existing node)_**
_**2. apply to bake in the Concordium Client**_
_**3. get stake from the node dashboard**_
_**4. update baker's reward account in the Concordium Client**_
_**5. update baker's keys in the Concordium Client**_

I did all these steps. I got my "success" feedback on the terminal after all transactions on these steps above. I checked them in concordium application. Everything was fine. So I uploaded my submission files and this is my PR link. https://github.com/Concordium/Testnet3-Challenges/pull/1022 . 

**_4. update baker's reward account in the Concordium Client_**
I did this step with "_concordium-client baker set-account_" command and I got success return. Here are the screenshots.
![set update acc](https://user-images.githubusercontent.com/49264077/99183980-f7037d00-2750-11eb-82fe-0616a3333a89.png)
![jj](https://user-images.githubusercontent.com/49264077/99184337-1c918600-2753-11eb-8835-8976d1c1012d.PNG)

After 1 epoch, I saw my reward accout updated on my node dashboard. I went on and completed my b5 task.

Everything was fine until I tried to check my transactions on https://dashboard.testnet.concordium.com/chain by the blockhashes I got on concordium client and concordium app.

This is the block hash of the block that my update account transaction finalized into: 6e3003e4fb01ae4cf20f6d2f093a3ecd752f3b16a419686724c4af05efeaa90c 
can be seen in the screenshots above.

https://dashboard.testnet.concordium.com/chain/6e3003e4fb01ae4cf20f6d2f093a3ecd752f3b16a419686724c4af05efeaa90c
I got this errors in the block explorer 
![resim](https://user-images.githubusercontent.com/49264077/99184434-cb35c680-2753-11eb-8113-a2aa7d843aa5.png)

Even though I got success return on the terminal and my account updated successfully on the node dashboard/mobile app, I get this error.

I thought maybe I did smt wrong so wanted to see other users' blocks. There are many users that uploaded their screenshots/blockhashes in their pull requests. I checked them all. Same errors appear in the block explorer. 

Here are some examples from the pull requests of other users.

https://github.com/Concordium/Testnet3-Challenges/pull/973
https://dashboard.testnet.concordium.com/chain/280351766df021c45a46e8434d38393959d9c96c741466bea6988afeeeff8920

https://github.com/Concordium/Testnet3-Challenges/pull/1112
https://dashboard.testnet.concordium.com/chain/118d009e6f22875f94874c78a1b7f638c6aa3ba970e7459cc2c6a40eb2e7aa29

https://github.com/Concordium/Testnet3-Challenges/pull/1038
https://dashboard.testnet.concordium.com/chain/dac60f7da74862494459edb0c7d0e8afc172ebbed65404ff8abe62d9c17bcb07

https://github.com/Concordium/Testnet3-Challenges/pull/1080
https://dashboard.testnet.concordium.com/chain/6a13c31bd7b31bd914145356be4c21430d8b325f34c950f9dda4514557151a19

https://github.com/Concordium/Testnet3-Challenges/pull/1037
https://dashboard.testnet.concordium.com/chain/c85da647344724c2bbe628b60a8127eb7663c147eaa74769bade4c9dc940c107

While block content JSON file is being created, smt goes wrong and causes this bug I guess.

_**2. apply to bake in the Concordium Client**_
_**5. update baker's keys in the Concordium Client**_
I also checked for **_baker add_** and **_baker set-keys_** transactions. Add baker works fine. But same errors appears on set-keys transactions blocks. Here is the link: https://dashboard.testnet.concordium.com/chain/d5a1ab77fc893515a252582a27820a668e2060e684d91d40803eebdad65d0cec

**Comment by concordium-admin** [comment]
Hi greyheaven, thank you very much for this detailed bug report! It's much appreciated.

I have created an internal bug report and we will have the json decode error on the network dashboard fixed in the next version.

**Comment by concordium-admin** [comment]
Issue will be traced by internal ticket.
