### ISSUE TITLE
Challenge (B3) updated

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#287]
It came to our attention that in challenge (B3) line 

- `restart a node with --listen-grpc-port set to 9999` and start Concordium Client connecting to port 9999 

cannot be executed in a straightforward way, so we decided to delete it from the challenge. The challenge card has been updated and tagged accordingly. There is no need to resubmit (B3). Please merge this change into your working space.

**Comment by iekmuby** [comment]
Actually you are wrong. I complete this step abou 10 times for different nodes, everything fine. This step isn't working if you access the node from the same vps. But if you run client from another machine/server you successfully access the node by ip.
