### ISSUE TITLE
New Mac release out now!

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#291]
There was an issue on Mac when trying to add a baker on the node dashboard, which failed with a network error in the first released Mac version. 

We have fixed the issue and uploaded a new release for Mac to our 
[Downloads page](https://developers.concordium.com/testnet/docs/downloads) page. Please make sure to download the latest Mac version, released on 16-10-2020.

Please follow the step-by-step guide:

1. Delete folder `~/Documents/concordium-software` .
2. Download the new release.
3. Extract the .zip into the folder `~/Documents`
4. Open a terminal in `~/Documents/concordium-software`.
5. Ensure your node is stopped by running `./concordium-node-stop`.
6. Reset the data by running .`/concordium-node-reset-data`.
7. Run `./concordium-node` and let it catch up.
8. Follow the regular guides towards becoming a baker.

Note that in all releases you can use the Concordium client for account and baker management, see e.g. `concordium-client config account --help` and `concordium-client baker --help`, respectively, to get started.

**Comment by supermario** [comment]
Update moved to the [status page](https://github.com/Concordium/Testnet3-Challenges/blob/main/status.md).
