### ISSUE TITLE
Stake delegation slot increase

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#299]
The delegation service has been changed so that it now has 25 slots, each with around 1% stake. The duration of the delegation is unchanged, each **delegation lasts for 2 hours**. With these parameters we expect bakers that have the amounts delegated to produce around **7 blocks in the two hour**s.

**Comment by supermario** [comment]
Update moved to the [status page](https://github.com/Concordium/Testnet3-Challenges/blob/main/status.md).
