### ISSUE TITLE
(B2) Restart a node according to schedule.

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#30]
**Mission:**
- restart twice a day for 7 days
-- stop the node
-- wait for different periods
-- restart the node

**Submission:**
- submit node ID
- submit log summaries of the run (see [Logs](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md) for instructions & tooling)

### ⚠️ Submission Note 

We originally asked for full logs, which turned out to be difficult due to log sizes. Please update your submission with the output of new [log summary tool](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md) instead.

**Comment by andrste** [comment]
Node ID
andrste
Logs will be submited

**Comment by Zipporol** [comment]
Node ID
zipporol
Logs will be submited

**Comment by zvagol** [comment]
Node id - c998ab7b1c90cbd3
Weednigga
Full logs will be submitted

**Comment by xaochuk** [comment]
Node ID:
87d2f01db8d708eb
Full logs will be submitted

Node Name: xaochuk

**Comment by kazantip85** [comment]
Node ID: 076bd2a1bd4044a9
Full logs will be submitted

**Comment by stguller** [comment]
Node ID: d799d7da5cc9af99
Full logs will be submitted

**Comment by farukbostansua** [comment]
Node ID: Id: c5d124a969c5c7c1
Full logs will be submitted

**Comment by gokmenkutuk** [comment]
Node ID: 84d426dc716e
full logs will be submitted

**Comment by Rookie23** [comment]
Node ID: dffc35c76091ef28
Full logs will be submitted

**Comment by Earth-Oz** [comment]
Node ID: 37b194f70924088a

 Full logs will be submitted

**Comment by bertco** [comment]
Node ID: 

Full logs will be submitted

**Comment by memur01** [comment]
Node name: ronald
Node ID: 5fca2fa41285122f
Full logs will be submitted.

**Comment by crowleyy** [comment]
Name : preacher
Node id : ecd0a62d9160772d
Full logs will be submitted

**Comment by rezeda88** [comment]
Node ID:

Full logs will be submitted

**Comment by doantn09** [comment]
Node id: 9e0c448eebeba0b6
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: fe864d7611d30977
Full logs will be submitted

**Comment by namekutuk** [comment]
Node ID: b53a27de140d
Full logs will be submitted
Name: Namek

**Comment by selaslan72** [comment]
Node id: 6e945dc2f8d947fb
Full logs will be submitted

**Comment by cryptosquanch** [comment]
Node id: a5558e4e2f96a125
full logs will be submitted

**Comment by elturrco** [comment]
Node id: a5b03a5f223c4d99
full logs will be submitted

**Comment by Ivan123-ops** [comment]
Node id: 0d84e1f4f49382ae
full logs will be submitted

**Comment by frtozkn** [comment]
Node id: ce2a663b44b98384
full logs will be submitted.

**Comment by hknnr** [comment]
node ID : dbd207ceb4bfdbc4
full logs will be submitted

**Comment by senevrensel** [comment]
Node ID : 2fc321a224b02fde

Full Logs will be submitted

**Comment by devrimdanyal** [comment]
Node ID: a716a8bf551f969e
full logs will be uploaded

**Comment by ozans28** [comment]
Node ID : 49fdb7942847ee08 and Node ID : 08801395abf8606a
full logs will be uploaded

**Comment by mrdaddyru** [comment]
Name: mrdaddy
Id: 93dcd872424fabf0
full logs will be uploaded

**Comment by vivalldi25** [comment]
Node ID: bc2de4c5285d3c08
full logs will be uploaded

**Comment by ozans28** [comment]
Node ID : 49fdb7942847ee08 
Node ID : 08801395abf8606a
full logs will be uploaded

**Comment by insomnium7** [comment]
Node id: 5a4c327351edca64
full logs will be submitted

**Comment by mrdaddyru** [comment]
Name: mrdaddy
Id: 93dcd872424fabf0
full logs will be uploaded

**Comment by civileagle** [comment]
Node ID: 6438b92265a3c11b
Full logs will be submitted

**Comment by wingman31192** [comment]
Node ID: ce08d5145d5a0054
full logs will be uploaded

**Comment by olazing4u** [comment]
Node ID: 6fe8980a7725931a
Full logs will be submitted

**Comment by wingman666** [comment]
Node ID: d30e8aeb7a633916
Full logs will be submitted

**Comment by vitconratran9x92** [comment]
Node ID: a9c6033f7434f8f6
Full logs will be submitted

**Comment by diaryofbigjourney** [comment]
Node Id: 5b291dca7a4b5841
full logs will be uploaded

**Comment by bitboomxxx** [comment]
Node Id: 71c5e68705ee298d
full logs will be uploaded

**Comment by doantn09** [comment]
Node id: e677925cf7273772
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: a9d85ac2d7e1203b
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: ac1bf8563d669ae7
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: e7a0a5684b1816b2
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: 68612ade6c31ee78
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: b973de5901406e14
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: ab0f6980e95bd826
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: 3fdae3d910554784
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: c0121daed9f12f2b
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: 6061fba8e4ac03c8
Full logs will be submitted

**Comment by doantn09** [comment]
Node id: d13b29d6e46c7921
Full logs will be submitted

**Comment by gulayse142** [comment]
node ID : Id: c575960f33c93f07
full logs will be uploaded

**Comment by pumphard88** [comment]
Node ID:d7c1a503f310932f
Full logs will be submitted

**Comment by battaodineucothe** [comment]
Node ID: 225411261eb488e8
Full logs will be submitted

**Comment by sbtgny** [comment]
Node Id: 8d8524f50c5ce09f
Full logs will be submitted

**Comment by mmonline9x92** [comment]
Node ID: a6f14eff6e5e9204
Full logs will be submitted

**Comment by bitearnx** [comment]
node id: d5347e1737b50364
full logs will be submitted

**Comment by vitconxxx** [comment]
Node Id: d4ace0e3ed903879
full logs will be uploaded

**Comment by ilhamm24** [comment]
Node ID : 2a0a1713b90b4e8b(https://dashboard.testnet.concordium.com/node/2a0a1713b90b4e8b)
Full log: soon

**Comment by byebye9x** [comment]
node id: 2838f783996f4c55
full logs will be submitted

**Comment by liray-unendlich** [comment]
Node ID: 2268d9ccd6c00633
Full Logs: [TODO]

**Comment by canoplos** [comment]
Name: canoplos
Id: 4661b48dd469c9d2
Full logs will be submitted

**Comment by yunus1729** [comment]
Node Name: anglachel
Node ID: 81cda53fe56a03ae

**Comment by TO-BOwan** [comment]
Node ID: 0ce45240afed83c4
Full logs of the run will be submitted

**Comment by edandrada** [comment]
Node ID : aae804235fb5a39e
full logs will be uploaded

**Comment by TO-BOwan** [comment]
Node name: TOBO
Node ID: 0ce45240afed83c4
Full logs of the run will be submitted

**Comment by TravelerAnu** [comment]
node ID: 1d3b0e7d15b7be69
name: angin
full logs will be submitted

**Comment by MichaelDamsgaard** [comment]
Node name: doc.com.1
Node ID: f377d8f2ca66f91c
Full logs will be submitted.

**Comment by Ebruberen** [comment]
Node ID: c89e05fa4d204665
full logs will be submitted

**Comment by Syd-ai** [comment]
Node ID : 9292a8c7c27ac33d
Full logs : to be submitted

**Comment by sun1534** [comment]
Node ID:2cb1caa6ffabaacf
Full logs : to be submitted

**Comment by coreman000** [comment]
Node Id: a7fe8ba37134aa3e
Full log : to be submitted

**Comment by wallnode** [comment]
Node Id: a9499e2217a5f576
Full logs will be submitted

**Comment by pasha036** [comment]
Node name: SERKAN_PASHA
Node ID: 1bcb66929636f504
Full logs will be submitted.

**Comment by Hohlas** [comment]
Name: hohla
Id: d4915c486748b29c
Full logs will be submitted.

**Comment by bukala** [comment]
Name: buka
Id: d23666cf32f97af2
Full logs will be submitted.

**Comment by huba-buba** [comment]
Name: Luba
Id: c041c7efa83e6211
Full logs will be submitted.

**Comment by Julyla** [comment]
Name: July
Id: 352bf3ceebe47ea2
Full logs will be submitted

**Comment by serkanalgl** [comment]
Name: serkan
Id: eb8102cbcdb76a5d

**Comment by Crypto-Awake** [comment]
Node id: e9d6fe26fb03fd18
Full logs will be submitted

**Comment by zeybek-omer** [comment]
Node name: zeybek_omer
Node ID : 12f2711780683226
Full logs will be submitted.

**Comment by network82** [comment]
Node name: alidemirel
Node ID:      cb9be1e8633bf93b
Full logs will be submitted

**Comment by BeytullahEVLENDI** [comment]
Node Id: 31e7c56c49370691
Full logs will be submitted

**Comment by kryatsvn** [comment]
Node ID: 19a6be158ad592f1
Full logs will be submitted

**Comment by zybk70** [comment]
Node ID: 654436cf379fc1d0
Full logs will be submitted

**Comment by MehmetAliATLI** [comment]
Node ID: 876d534cf6fa9f7b
Full logs will be submitted

**Comment by bozard** [comment]
Node Name: bozzard
Node ID: 9b710cb25ef7c9ad

**Comment by erknfe** [comment]
Node ID: 973acce424dbca3d
Full logs will be submitted

**Comment by Kkemosabe** [comment]
Node ID: d3f0897e637ff9ce
Full logs will be submitted

**Comment by snnucr2** [comment]
Node Name :mgsnn
Node Id : bd4734b63de8e19a

Full logs will be submitted

**Comment by akindemiroz** [comment]
Node Name : akınmelih
Node Id : 5effb2c031278f5e

Full logs will be submitted

**Comment by erknfe** [comment]
Node ID: 8ada2caba4182965
Full logs will be submitted

**Comment by cryptodzh** [comment]
Node id: 73d3428cbde56927
Baker ID: 682

**Comment by lukapodlesnik** [comment]
Node ID: 18fc79fb35c7460b
Full logs will be submitted

**Comment by truth-seeker88** [comment]
Node name Seeker_of_the_truth
Node ID cafc02f9475bbe11
Full logs will be submitted

**Comment by ogumogumakyak** [comment]
Node ID: cdf1400135749adc

Full logs will be submitted

**Comment by wormaxe** [comment]
Node ID: ac580bd551910bdf

Full logs will be submitted

**Comment by minatofund** [comment]
Node Name : MinatoFund
Node ID : b37234959a375b35
https://dashboard.testnet.concordium.com/node/b37234959a375b35
Full logs will be submitted

**Comment by armyids** [comment]
Node Name : Army IDs
Node ID : 054f07bfb8b22e38
Node Link : https://dashboard.testnet.concordium.com/node/054f07bfb8b22e38
Full logs will be sumbitted.

**Comment by ozerbeg** [comment]
Node ID: 70f53e4d01f729a1

Full logs will be submitted

**Comment by donadel01** [comment]
Node ID: 5bbdaa9fd9d3f13d

Full logs will be submitted

**Comment by donadel01** [comment]
Node ID: 04da7a8399c95de4

Full logs will be submitted

**Comment by okannako** [comment]
Node ID: 9905857303f81b43
Full logs will be submitted

**Comment by okannako** [comment]
Node ID: 24d92aac7617a140
aokannn2
Full logs will be submitted

**Comment by edrolu87** [comment]
Node id: bd35a764b4caa77f
full logs will be submitted

**Comment by alevoncel** [comment]
Node ID: f831ab99788ead80

Full logs will be submitted

**Comment by dursunalp** [comment]
Node ID  :     824c52c634fa7881
full logs will be submitted

**Comment by cengizgndgd** [comment]
Node name  :  eser
Node ID:          0b0fc0a2720f974f

düğüm bağlantısı   :    https://dashboard.testnet.concordium.com/node/0b0fc0a2720f974f

Tam günlükler kaydedilecektir.

**Comment by cengizgndgd** [comment]
Node name : cengiz
Node ID: 9ae99d88e802203e
düğüm kimliği  :  https://dashboard.testnet.concordium.com/node/9ae99d88e802203e
tam günlükler gönderilecek

**Comment by eserow** [comment]
Düğüm adı: eser
Düğüm Kimliği: 0b0fc0a2720f974f

düğüm bağlantısı: https://dashboard.testnet.concordium.com/node/0b0fc0a2720f974f

Tam günlükler kaydedilecektir.

**Comment by esmirs** [comment]
Node Id : 8d01fe08ba949291

Node name : esmir

Full logs will be submitted

https://dashboard.testnet.concordium.com/node/8d01fe08ba949291

**Comment by melihbozard** [comment]
Node name:  mgsnucr

Node ID:  f19cc2517b1e9b37

Link: https://dashboard.testnet.concordium.com/node/f19cc2517b1e9b37

Full logs will be submitted

**Comment by tagpesa** [comment]
Node name: Tagpesa

Node ID: 1d0d43818a001831

Link: https://dashboard.testnet.concordium.com/node/1d0d43818a001831

Full logs will be submitted

**Comment by tugba88** [comment]
Node id: 881651fcdfdfc927
full logs will be submitted

**Comment by tugba88** [comment]
Node Name: tugba88
Node id: 881651fcdfdfc927
full logs will be submitted
 https://dashboard.testnet.concordium.com/node/881651fcdfdfc927

**Comment by Aysealp** [comment]
Node ID :   59eddc588e6924d8
full logs will be submitted

**Comment by minivipers** [comment]
Node ID : d105d00749efe743
Full logs will be submitted

**Comment by Maje53** [comment]
Name: Maje
Id: 345d9d66c25c94b1

https://dashboard.testnet.concordium.com/node/345d9d66c25c94b1

 full logs will be submitted

**Comment by wondayer** [comment]
Node ID : 296c781594092ee5
Full logs will be submitted

**Comment by wxl2578** [comment]
Node Name : wxl2578
Node ID : 3111d8a5ab8f5220
Node Link : https://dashboard.testnet.concordium.com/node/3111d8a5ab8f5220
Full logs will be sumbitted.

**Comment by yenerh** [comment]
Node ID : ab58bf97f3af273e
Node Link : https://dashboard.testnet.concordium.com/node/ab58bf97f3af273e
Full logs will be submitted.

**Comment by BreenLine** [comment]
Node ID: cc13e70de9984ba2
Node Name: breenline
Address: 4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZc
Link: https://dashboard.testnet.concordium.com/node/cc13e70de9984ba2

Logs will be submited soon

**Comment by BreenLine** [comment]
Node ID: cc13e70de9984ba2
Node Name: breenline
Address: 4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZc
Link: https://dashboard.testnet.concordium.com/node/cc13e70de9984ba2

Logs will be submited soon

**Comment by Erdincgumus** [comment]
Node ID:11d02d862c6127ad
Full logs will be submitted

**Comment by adali125** [comment]
Node ID:a5767d7ab78a3cb5
Full logs will be submitted
