### ISSUE TITLE
(B3) Restart a node with different restart type

### ISSUE THREAD

**Issue by bissembert1618** [Concordium/Testnet3-Challenges#31]
**Mission:**
All restart types must be executed. Measure the time it takes to catch-up and note down the current chain length.

- restart a node using local DB
- restart a node with `--no-block-state-import`

**Submission:**
- submit node ID
- submit logs of startup sequence
- provide feedback on measured time and chain length

**Comment by andrste** [comment]
Node ID
andrste
Logs will be submited

**Comment by zvagol** [comment]
Node id - c998ab7b1c90cbd3
Weednigga
Full logs will be submitted

**Comment by xaochuk** [comment]
Node ID:
87d2f01db8d708eb
Full logs will be submitted

Node Name: xaochuk

**Comment by kazantip85** [comment]
Node ID: 076bd2a1bd4044a9
Full logs will be submitted

**Comment by farukbostansua** [comment]
Node ID: Id: c5d124a969c5c7c1
Full logs will be submitted

**Comment by Rookie23** [comment]
Node ID: dffc35c76091ef28

Full logs will be submitted

**Comment by rezeda88** [comment]
Node ID
Logs will be submited

**Comment by crowleyy** [comment]
Name : preacher
Node id : ecd0a62d9160772d
Full logs will be submitted

**Comment by ekcoder** [comment]
Reserved

**Comment by elturrco** [comment]
Node ID: Id: a5b03a5f223c4d99
Full logs will be submitted

**Comment by Ivan123-ops** [comment]
Node ID: Id: 0d84e1f4f49382ae
Full logs will be submitted

**Comment by hknnr** [comment]
node ID : dbd207ceb4bfdbc4
full logs will be submitted

**Comment by mrdaddyru** [comment]
Name: mrdaddy
Id: 93dcd872424fabf0
full logs will be submitted

**Comment by vivalldi25** [comment]
Node ID: bc2de4c5285d3c08
full logs will be uploaded

**Comment by ozans28** [comment]
Node ID : 49fdb7942847ee08
Node ID : 08801395abf8606a
full logs will be uploaded

**Comment by wingman31192** [comment]
Node ID: ce08d5145d5a0054
full logs will be uploaded

**Comment by olazing4u** [comment]
Node ID: 6fe8980a7725931a
Full logs will be submitted

**Comment by wingman666** [comment]
Node ID: d30e8aeb7a633916
Full logs will be submitted

**Comment by vitconratran9x92** [comment]
Node ID: a9c6033f7434f8f6
Full logs will be submitted

**Comment by diaryofbigjourney** [comment]
Node Id: 5b291dca7a4b5841
full logs will be uploaded

**Comment by bitboomxxx** [comment]
Node Id: 71c5e68705ee298d
full logs will be uploaded

**Comment by gulayse142** [comment]
Node Id: c575960f33c93f07
full logs will be uploaded

**Comment by battaodineucothe** [comment]
Node ID: 225411261eb488e8
Full logs will be submitted

**Comment by pumphard88** [comment]
Node ID:d7c1a503f310932f
Full logs will be submitted

**Comment by mmonline9x92** [comment]
Node ID: a6f14eff6e5e9204
Full logs will be submitted

**Comment by bitearnx** [comment]
node id: d5347e1737b50364
full logs will be submitted

**Comment by vitconxxx** [comment]
Node Id: d4ace0e3ed903879
full logs will be uploaded

**Comment by byebye9x** [comment]
node id: 2838f783996f4c55
full logs will be submitted

**Comment by mmonline9292** [comment]
Node Id: b1a710ac032a367f
full logs will be uploaded

**Comment by sbtgny** [comment]
Node Id: 8d8524f50c5ce09f
full logs will be uploaded

**Comment by liray-unendlich** [comment]
Node ID: 2268d9ccd6c00633
Full logs: [TODO]

**Comment by edandrada** [comment]
Node ID : aae804235fb5a39e
full logs will be uploaded

**Comment by Syd-ai** [comment]
Node ID: 9292a8c7c27ac33d
Logs : to be uploaded

**Comment by sun1534** [comment]
Node ID:2cb1caa6ffabaacf
Full logs : to be submitted

**Comment by devrimdanyal** [comment]
Node ID: a716a8bf551f969e
full logs will be uploaded

**Comment by TravelerAnu** [comment]
Node ID : 1d3b0e7d15b7be69
name : angin
Full logs will be uploaded

**Comment by network82** [comment]
Node name: alidemirel
Node ID:      cb9be1e8633bf93b
Full logs will be submitted

**Comment by zeybek-omer** [comment]
Node name : zeybek_omer
Node ID : 12f2711780683226
Full logs will be submitted

**Comment by mrcnode** [comment]
Node name : mrcnode
Node ID : 101ae99baf5b7843
Full logs will be submitted

**Comment by kryatsvn** [comment]
Node ID: 19a6be158ad592f1
Full logs will be submitted

**Comment by BeytullahEVLENDI** [comment]
Node Name: BeytullahE
Node ID: Id: 31e7c56c49370691
Full logs will be submitted

**Comment by zybk70** [comment]
Node ID: 654436cf379fc1d0
Full logs will be submitted

**Comment by MehmetAliATLI** [comment]
Node ID: 876d534cf6fa9f7b
Full logs will be submitted

**Comment by bozard** [comment]
Node name : bozzard
Node ID : 9b710cb25ef7c9ad

Full logs will be submitted

**Comment by erknfe** [comment]
Node ID: 973acce424dbca3d
Full logs will be submitted

**Comment by webshark** [comment]
Node ID: 6e54c3091f81fc55
Full logs will be submitted

**Comment by Kkemosabe** [comment]
Node ID: d3f0897e637ff9ce
Full logs will be submitted

**Comment by snnucr2** [comment]
Node Name : mgsnn
Node Id : bd4734b63de8e19a


Full logs will be submitted

**Comment by dmitriyzh1** [comment]
Node id: 50ff67b9b6d89248
Baker ID: 934

**Comment by cryptodzh** [comment]
Node id: 73d3428cbde56927
Baker ID: 682

**Comment by ogumogumakyak** [comment]
Node ID: cdf1400135749adc

Full logs will be submitted

**Comment by wormaxe** [comment]
Node ID: ac580bd551910bdf

Full logs will be submitted

**Comment by minatofund** [comment]
Node Name : MinatoFund
Node ID : b37234959a375b35
https://dashboard.testnet.concordium.com/node/b37234959a375b35
Full logs will be submitted

**Comment by donadel01** [comment]
Node ID: 5bbdaa9fd9d3f13d

Full logs will be submitted

**Comment by donadel01** [comment]
Node ID: 04da7a8399c95de4

Full logs will be submitted

**Comment by slon36** [comment]
**node ID:**   d6decaa28e70c084
**logs of startup sequence** +  **time and chain length**
**SUBMITTED** to my repository

**Comment by MVPLA** [comment]
**node ID:**   d6decaa28e70c084
**logs of startup sequence** + **time and chain length**
**SUBMITTED** to my repository
https://github.com/MVPLA/Testnet3-Challenges/commit/845159613d5bf0e6702e7afca342d3db4e8e35b0

**Comment by okannako** [comment]
Node ID: 24d92aac7617a140
aokannn2
Full logs will be submitted

**Comment by edrolu87** [comment]
Node Name : edrolu
Node ID : bd35a764b4caa77f
https://dashboard.testnet.concordium.com/node/bd35a764b4caa77f
Full logs will be submitted

**Comment by alevoncel** [comment]
Node ID: f831ab99788ead80

Full logs will be submitted

**Comment by dursunalp** [comment]
Node ID   :   824c52c634fa7881
Full logs will be submitted

**Comment by eserow** [comment]
Düğüm numarası: 0b0fc0a2720f974f
https://dashboard.testnet.concordium.com/node/0b0fc0a2720f974f
tomruk başlatma dizisi + zaman ve zincir uzunluğu

**Comment by esmirs** [comment]
Node Id : 8d01fe08ba949291

Node name : esmir

Full logs will be submitted

https://dashboard.testnet.concordium.com/node/8d01fe08ba949291

**Comment by melihbozard** [comment]
Node name: mgsnucr

Node ID: f19cc2517b1e9b37

Full logs will be submitted

**Comment by tagpesa** [comment]
Node name: Tagpesa

Node ID: 1d0d43818a001831

Link: https://dashboard.testnet.concordium.com/node/1d0d43818a001831

Full logs will be submitted

**Comment by tugba88** [comment]
Node Name: tugba88
Node id: 881651fcdfdfc927
Full logs will be submitted
https://dashboard.testnet.concordium.com/node/881651fcdfdfc927

**Comment by Aysealp** [comment]
Node name :Ayşe55aLP
Node ID  :   59eddc588e6924d8
Full logs will be submitted
https://dashboard.testnet.concordium.com/node/59eddc588e6924d8

**Comment by minivipers** [comment]
Node name : miniconcorde
Node ID : d105d00749efe743
Node Link : https://dashboard.testnet.concordium.com/node/d105d00749efe743
Full logs will be submitted

**Comment by Maje53** [comment]
Name: Maje 
Id: 345d9d66c25c94b1

https://dashboard.testnet.concordium.com/node/345d9d66c25c94b1

Full logs will be submitted

**Comment by wxl2578** [comment]
Node name : wxl2578
Node ID : 3111d8a5ab8f5220
Full logs will be submitted
https://dashboard.testnet.concordium.com/node/3111d8a5ab8f5220

note:
normal:
--no-block-state-import

**Comment by BreenLine** [comment]
Node ID: cc13e70de9984ba2
Node Name: breenline
Address: 4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZc
Link: https://dashboard.testnet.concordium.com/node/cc13e70de9984ba2

Logs will be submited soon
