### ISSUE TITLE
(B4) Register as baker on node dashboard

### ISSUE THREAD

**Issue by bissembert1618** [Concordium/Testnet3-Challenges#32]
**Mission:** 
- run a node (or reuse existing node)
- apply to bake on the node dashboard
- get stake on the node dashboard
- after some time, stop baking on the node dashboard

**Submission:**
- submit baker ID
- submit account address
- submit observations, if any

**Comment by andrste** [comment]
Baker ID
Account address

**Comment by Zipporol** [comment]
baker ID
account address

**Comment by paveldp** [comment]
submit baker ID
194

submit account address
2xKSYfYEJK5cUtfY3fYGogeDYNhyN3gD6gVUeu7J16qQuQTnve

**Comment by zvagol** [comment]
Baker id - 97
Weednigga
submit account address - 3Qaq5vDT5sEQeMnkAued7YW1BgA2hjQLnCZuHHUv8td2A3UKaP

**Comment by xaochuk** [comment]
submit baker ID
114

submit account address
2wzoWzMGMzu9o3ZccBYLB9EUs9GBqmmMdy91vU7dWx8tTp5zwD

**Comment by ildidetka** [comment]
Baker ID - 280
Account address - 36V1bQKRvLRZzLVmxUtxfTn7RGZMRx5VzPH7Q9ZaA1TTfpXAcd

**Comment by kazantip85** [comment]
Baker ID: 183
Account address -

**Comment by jamabai** [comment]
baker ID: 569
account address: 4KbMCjfSJzuwoTdW1VhChaDhAuXnsSGVRxP1jA4BTtwixizdqk

**Comment by trader-payne** [comment]
**Baker ID** - `511`
**Account Address** - `3krsknjcFgpkRaGwVJATXqXt5WPNPNwcgc351AH1ZTehyxSJxS`

**Comment by czarly** [comment]
Baker ID - 587
Account Address - 3DstimcqJt8jjhrWBj3nYMUkv23euv4XB2VATakCe4ng2MwED9

**Comment by stguller** [comment]
Baker ID- 455
3hcm3jxuP5Qdmc5rQM3G6KimJwMCJSQ8AN3A2QxY6qxcVcSpSW

**Comment by rooiboss** [comment]
Baker ID - 409
3s1G92ePBGFjcBkwgjbixGHd3t8Hbxhs8K2ecFw2YQrGmdu1gt

**Comment by farukbostansua** [comment]
Baker ID : 121
4XwjDx13B9NPmwRgokd15hhWczSc77tBQpNtkoeeVgqwwMpiEN

**Comment by Rookie23** [comment]
Baker ID: 350
3pmGPBQGgAhKCSLoiWWUwEqUmFS11PhxaxVLTp7rQJEVyKP83u

**Comment by lopotras** [comment]
Baker ID: 38
adress: 3d3njFY4zQSPk9aLSkeBH7UKAcXQX7wQc2NGRKsTp6vHkeS1j4

**Comment by stguller** [comment]
e30ba43a2638ecc7
3hcm3jxuP5Qdmc5rQM3G6KimJwMCJSQ8AN3A2QxY6qxcVcSpSW

**Comment by Earth-Oz** [comment]
Baker ID: 521
Account Address: 3gkLg2Qf4UwxiK6VVH1h6UWWHPhpGro1mBNonbc3JyhnRv4tPv

**Comment by wingman31192** [comment]
Baker ID: 55
Account Address: 3Gqw5QZNZpxkzv699rjEzUM6QtBWqVFudHd94wLVN6bHvF6XVB

**Comment by bertco** [comment]
Baker ID:
Account Address:

**Comment by olazing4u** [comment]
Baker ID: 61
Account Address: 4azrNGeig7FzYjyEq8yP195F9jEUNax4Gc4nPFj5m1T8j19srp

**Comment by vitconratran9x92** [comment]
Baker ID: 62
Account Address: 4jtd5k7SaQfqdpVDKwrdXQQ2ZibgsgtyV6VytPq6FP7b8zZoLv

**Comment by crowleyy** [comment]
Baker id : 329. 

4b31A4EEo2obWF1Xx33L9BtDqUrhwbYu6yrmawHUfMuVnReo5Y

**Comment by rezeda88** [comment]
Baker ID:
Account Address:

**Comment by diaryofbigjourney** [comment]
Baker ID: 146
Account Address: 4Wee6uTQtm7AnCbGr814EitoPWjppcUPwjm75NVKMXigg1v7uk

**Comment by bitboomxxx** [comment]
Baker ID: 147
Account Address: 3PmuwP3Fn5om49L7Quww11YX8THmFRpwDEJF3oGdTfZGhXMTyY

**Comment by wingman666** [comment]
Baker ID: 69
Account Address: 3CLCn6wfYb9G51fWWTcXN4obfsCzxZFzw7AcivVVqp4LGaGUp1

**Comment by mmonline9x92** [comment]
Baker ID: 150
Account Address: 4CULjvEC8scHbBPiNJ1Ws8zZ5brWWcdwCm6pHAAyGC6u6SbXqm

**Comment by pumphard88** [comment]
Baker ID: 148
Account Address: 4Qt8Zg5uryhbEMrjCVAHjz5JDkHhW5knwd1owr1w82ANJdeEH5

**Comment by Vladislav1z** [comment]
Baker ID: 85 
Account Address: 322C4YuaGzdByJas1uNnCdjzdXvmRdf4SjrJW86u1T5fntQg1F

**Comment by doantn09** [comment]
Baker ID: 57
Account address: 4ih64E5aWRYyQKhtuWThu5xtbFyFxwqUKqwApjedGGWoF1RWM3

**Comment by doantn09** [comment]
Baker ID: 58
Account address: 3ibzuwhHWuvF6J6Ca7XM1FTr83bdokW7LLHq1S8uo5927dRhwq

**Comment by EK2503** [comment]
Baker ID: 102
Account Address: 3nYPWUZzsw5cHmyRNukygFixmFCm7fj2KjzzrLhct25PSLcvdc

**Comment by battaodineucothe** [comment]
Baker ID: 149
Account Address: 3B2dCmn33KJPHxJxiQ6NnEaFVRUxCyhCSjjTjPAunYLCh4bLth

**Comment by TVV61** [comment]
Baker ID: 112
Account Address: 49iM2pymCQp9WS5ECJT7d92S8tnApSgLx1oi9tN1fzRAQk6V4D

**Comment by Irina0880** [comment]
Baker ID: 101
Account Address: 4SDHDUevSoqhTvPDJFPYjwUakFsk6R6QqmB8xdAUqorU1MwEA7

**Comment by doantn09** [comment]
Baker ID: 59
Account address: 45UqFVUx488yMcbyi5UQfPnKvpAtYDXCTAgEhwjKANDtrUo2tL

**Comment by doantn09** [comment]
Baker ID: 63
Account address: 4awSMcaTjhevnQxBadTS1VHia3YKwSimX8e8vSoUBKykqk33bh

**Comment by doantn09** [comment]
Baker ID: 64
Account address: 3rewbmwWdnRRbex7sgRf2i2mWDsvoNE9MVh4B4K28dSShcEbEH

**Comment by doantn09** [comment]
Baker ID: 77
Account address: 37b5AY1Akw7BewzuEaz55RgaMig9dbURmSurQqJvtsFDo1n9XU

**Comment by doantn09** [comment]
Baker ID: 78
Account address: 33eudDsjB98nJUirT9d1R1GbyhYRD8LWsGBd7BFMHN8xUiVZAd

**Comment by doantn09** [comment]
Baker ID: 80
Account address: 3u2LhWmko8GsenVFAjtUxWiXy6qtJokCQKzBkFdDTSr5FdF5tB

**Comment by doantn09** [comment]
Baker ID: 82
Account address: 2zfRGtA2wNmwpoyxZTb1KqLNa1xcmeSbM3PVWBa7iZSoTw7Vby

**Comment by doantn09** [comment]
Baker ID: 151
Account address: 4ig117CWTKbbQAK6omyd9AAaQvFdGg9XmQ6ozCYtE1Cmc4DLKD

**Comment by doantn09** [comment]
Baker ID: 154
Account address: 4crGbqbWezTowRdkUvY4iKg9PPBo9RUNEqWWcXR1B76QcqFWBW

**Comment by doantn09** [comment]
Baker ID: 200
Account address: 4MCVbQrKAse6KxSM8yf6fWHTeyQktP8MBvuERjfW1phcYF3xY5

**Comment by doantn09** [comment]
Baker ID: 226
Account address: 4MbMAQCZsD1U7v9D1jtjSK6D9W6MUsCS7X4L5nPvJWeN44783V

**Comment by doantn09** [comment]
Baker ID: 394
Account address: 47EQAx8UePkPisAvJVV3aVrfWTVmZzD3y33ZQsdtBHvWvQBg4F

**Comment by doantn09** [comment]
Baker ID: 431
Account address: 4sYCN2YhF2VSqqKPGuD6gEBouzLqDasoNSjCn6M6JTmo5P3FZj

**Comment by elturrco** [comment]
Baker ID: 303
Account address: 3tfcLNMtZET7e9JQhYKZksSWFTcCu5Yy269JoKNpwuydHTJym5

**Comment by vuhuan17** [comment]
Baker ID: 79
account address : 3dem5Cys9CQxNb8z3ePJbJuBkCWZbyh95zqNjvJze8hoyyxdLJ

**Comment by byebye9x** [comment]
Baker ID: 600
account address : 4S6cS98dKkrPxLXJZCck8xR8FHfnTYSjv9ewViFxCKS1ybnzVr

**Comment by hudasboy** [comment]
Baker ID: 83
account address : 4NHThYaLu8PhF4pNLNhApYRJauGGBERuDqT1P9yFcs5EoUQerk

**Comment by bitearnx** [comment]
Baker ID: 601
account address : 2yStkDKSUTdCpNV8kqi6vMhNXvh3FUfA7XuZxKZErHNvvk5FHZ

**Comment by kinhdoantocviet** [comment]
Baker ID: 81
account address : 3STeXRgogCHtqUQe6uoe2HdczzH5F6oc79WCdRZvSEedpJRwLo

**Comment by hknnr** [comment]
Baker ID : 291

Account Adress : 3AnSuw1wjZWAnwMPhvLFAr6ZmCkGcKaJvevYvNaGYBsJw5mvCr

**Comment by mmonline9292** [comment]
Baker ID: 601
account address : 2yStkDKSUTdCpNV8kqi6vMhNXvh3FUfA7XuZxKZErHNvvk5FHZ

**Comment by hudasboy** [comment]
Baker ID: 81
account address : 4NHThYaLu8PhF4pNLNhApYRJauGGBERuDqT1P9yFcs5EoUQerk

**Comment by kinhdoantocviet** [comment]
Baker ID: 83
account address : 3STeXRgogCHtqUQe6uoe2HdczzH5F6oc79WCdRZvSEedpJRwLo

**Comment by bitearnx** [comment]
Baker ID: 603
account address : 4RSjcmpJCgYgDDirHECooHMmZV93tv18weEX5c5nFHniFXSE1N

**Comment by mrdaddyru** [comment]
Your Baker ID is 396
account address: 4hTUc7eDtns8474FsZUwUTojb8qQPF1oz41v51XPRWb3oyodYY

**Comment by vuhoa17** [comment]
Baker ID: 300
account address : 3PyotJnHj9k5q9bL7u6SGyn38ecRenUsVKsE7Ctw97iL7rauh5

**Comment by vitconxxx** [comment]
Baker ID: 599
account address : 4cxKnyjToyr7EEqs5WUK1h5fJN787XrTaDWJGRwEX1Pqc26x3T

**Comment by devrimdanyal** [comment]
Baker ID: 249
account address : 
3QpXKBR7zG45bBGHTUzrWgteXj1nHL43CnAYauiW3Ft9vU3LHj

**Comment by namekutuk** [comment]
Baker ID: 605
Account Address: 3eiFBKXxTXUWYHRG2Y1t36aN1Ay4utxBs4ncmsqgXGWaP3jZhU

Observations: It took too long to stop baking at first, and additionally while it was counting backward it the remaining duration was flickering.

**Comment by huysim** [comment]
Baker ID: 301
account address : 3hH54ZWJ4ufFtAV4BkrhF2tbqG6q53eQMyjCLpncUhkBrR2r9q

**Comment by gokmenkutuk** [comment]
Baker ID: 606
Account Address: 3J7BnAdEwyvcqhYL9oeHRSBZy8ZbEUGiQrZgJ6SQtBy62ihBhz
Observations: remainging time is flickering, takes too long to stop baking.

**Comment by ozans28** [comment]
Baker ID : 130
Baker ID : 214
account address: 4CgiFrhx81ckZXswe2bNa8jMMsBHsgzjgca3M1apgA6coxJhZb

**Comment by vivalldi25** [comment]
Baker ID: 315
account address : 2xx7GPC2DBn5LgjNxgXsp3iZs9okKf7WrJEHvWvMbkgGCee2HZ

**Comment by insomnium7** [comment]
Baker ID: 163
Account Address:

**Comment by Crypto-Awake** [comment]
Baker id: 290
Account adress: 4KuQ8SZZ3P7ycbmtpPJKt3rXcMBUZecTUyuiR5wN69NtVjkLPr

**Comment by gulayse142** [comment]
Baker ID - 328
4iH2AzBqxvSxBz6WfHDQpFZheaEKWcAipKdsqZ4ncwHLfknSqB

**Comment by slon36** [comment]
Baker ID: 616
Account address: 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb

**Comment by mrtcan** [comment]
Baker ID is 355
Account address : 4WnU9eZ8oe17ibPLUfMcg84LVRY2QenkwBfXnc3Rn5NYtm6BM4

**Comment by Musil2020** [comment]
Baker ID: 358
Account Address : 4ZPPvBV3xkeop5Xk8VWk7tStFiuJ7FfPu3rHkoGan5LKmbDU7G

**Comment by sbtgny** [comment]
Baker ID : 143
Account Address :32jMLWVcyfSPms59v18CggvSWj3ByJhMuCjZ7ng1JjG2aayy2q

**Comment by sevnode** [comment]
Baker ID : 399
Account Adress : 3AdRmsUVjy58jCoYy7wW6WNnBpb1pqagHb3Q6Do2iYQZdV6jvr

**Comment by drtugi** [comment]
Baker ID : 393
Account Adress : 4Ww3RAdtf6vyzD9imBySBYcgDPM3m5N9Qbdc1yoT6bBP1ZAyZH

**Comment by liray-unendlich** [comment]
Baker ID: 629
Account Address: 3vc3MV3g1T49xYDhpQ3VJUPMRjTiF6RehwtCuaJ7kT69MwX78o

**Comment by Ebru2020** [comment]
Baker ID: 414

Account address:

4AqoF5Wwc5bPpJf1UAu5RHuQKcH2ugscbE8hJSiegHpuPezoSr

**Comment by doantn09** [comment]
Baker ID: 627
Account address: 4awSMcaTjhevnQxBadTS1VHia3YKwSimX8e8vSoUBKykqk33bh

**Comment by pavrych** [comment]
Baker id: 512
Account Address: 3h54beJuxCHxAhCYA4jV361Es8inEJ6LQrUYnkw7sPs5UP55ZD
Observations: baking do not stop immediately, it will take 2 hours after bake stop TX

**Comment by canoplos** [comment]
Baker ID  201
Account address: 4LRLKqfSK2Q46WheuJoUmjDvhPtyAPk6tAJU8kkt9v6SrTBc6P

**Comment by yunus1729** [comment]
Baker ID 408
Account address: 3cJZ7rLUor4Nnq9TMjZL5bdCeuXCTDj8VAtjihPsV9XEyjpGGY

**Comment by zvagol** [comment]
baker 97
account address - 3sR9jpUuKxcRTt9PzESfLoTksiLzn3j5L9LkL4rMNDhLqHA71q

**Comment by MVPLA** [comment]
Baker ID: 631
Account address: 4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4

**Comment by sebo2002** [comment]
Baker ID : 390
Account address: 3sfLsrsbKJGGwZkkU1spdBUyjH77xqswn5vwr55CDmUtH9bkXc

**Comment by xaochuk** [comment]
Baker ID : 114
Account address: 2wzoWzMGMzu9o3ZccBYLB9EUs9GBqmmMdy91vU7dWx8tTp5zwD

**Comment by ilo2002** [comment]
Baker ID : 371
Account address : 43fnuKRzi4YmWnLLHtzWcUZPiAZPmttoaJsZmwzdC9bRewg9Mw

**Comment by ardo2002** [comment]
Baker ID : 391
Account address : 4NdTvniynGoQWDBYWwPyvoRHohqw4UTBCcsx4DsTQGgafM79LP

**Comment by draltunibrahim** [comment]
Baker id: 573
Account adress: 4K3n8xuknKLeWPJbrVFZbPhngTfpMKitN2rKAoPKuWdciAos56

**Comment by Malik0120** [comment]
Baker ID : 449
Account address : 3DWfPAPt2hm2RxAtbtaJC1Fb4EUVTqLDKTLG4GawhGr7ybEQiV

**Comment by vitconratran9x92** [comment]
Baker ID : 62
4jtd5k7SaQfqdpVDKwrdXQQ2ZibgsgtyV6VytPq6FP7b8zZoLv

**Comment by Shulepov** [comment]
Backer ID: 384
Account address: 37qiTNg3qtiiH5HnFex1nSfEmnoghomV7fJoECcRq1i4NRxubW

**Comment by battaodineucothe** [comment]
Baker ID : 149
3B2dCmn33KJPHxJxiQ6NnEaFVRUxCyhCSjjTjPAunYLCh4bLth

**Comment by TO-BOwan** [comment]
Baker ID: 652
Account address: 4pL3aSHkfwU7HjPZCUi8wLqUNU91dpsPJUo6haZ3N8U7Sg2vkN

**Comment by yerdeniz-node** [comment]
baker ID: 515
Account address:
3YRT8V1RAuSjErYVmAjmN6t1Cs9LjQp5ndg12YrzinL1T4EW8t

**Comment by wallnode** [comment]
Baker ID: 676
Account address: 3yxsAxipWR89f76kgPfEMFZMqcGEjkLsacWYgaY81GRkXtx1bx

**Comment by zybk70** [comment]
Baker ID: 100
Account address: 3VjC88swb5V73vpoiANbVDNJj5hvb2SAqhCiAaNhn5b5eDjdqd

**Comment by webshark** [comment]
Backer ID: 37
Account address: 4fT59jdrFbRVBzmyvzjzxasfu6MgyNndKnTTfVECsHinxLVmKd

**Comment by Ebruberen** [comment]
Baker ID: 544
Account adress: 48ddRbSQZZuCKaDakUfpzPNSDRSgLugtqjBSPC2ZvocHMX8GT4

**Comment by yusuftrl** [comment]
Baker ID; ziya08
33G2TsnyKjDqWZCGTZCJaKQfVVsJJJtm1E8toXvy1ocxoBLgMH

**Comment by yusuftrl** [comment]
Baker ID: ziya08
Account address: 33G2TsnyKjDqWZCGTZCJaKQfVVsJJJtm1E8toXvy1ocxoBLgMH

**Comment by yusuftrl** [comment]
Baker ID: 481
Account address: 33G2TsnyKjDqWZCGTZCJaKQfVVsJJJtm1E8toXvy1ocxoBLgMH

**Comment by Syd-ai** [comment]
Baker ID : 697
Account address: 2xT7kSNr5BEEvS4RPndbiTPwB9sj6x9LoQrbcZasdfSqUbCAdf

**Comment by sun1534** [comment]
Node ID:2cb1caa6ffabaacf
Account address:4cbQEcPYgSyxGarncL1pUkMev6iRcvgk8VSZid8YnxBhuZCsR4

**Comment by trancetr** [comment]
BakerID : 332
Account Address : 3nX1mVdnKjAxdwEDcwbB6xwGwi6wZdbTEDPraQd8qG3M7MF89Y

**Comment by mdlog** [comment]
Baker ID : 299
Account Address : 3McNbFRXbW3ky1yKT58DCWp8tn8hLKvCtNW3w9aSueoxCMGyut

**Comment by pasha036** [comment]
baker ID : 690
account address : 41QBG6ZgBNS23sp3wDCKE6SeaGXdzL5fR49E6bj8ZXPtooTpM7

**Comment by TravelerAnu** [comment]
Baker ID : 706
account address : 3jAAeY568MpUu3as3mCe7fKu41eerRQhTm3ffjj4P5V1Ab2sg3

**Comment by slon36** [comment]
baker ID: 663 
account address:  4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb

**Comment by serkanalgl** [comment]
Baker ID is 419
Account Address is 4jV4sYjHz4R9yH59P2D5dB7AGHKRV8m6XaypAXo35o388Ddvrh

**Comment by Crypto-Awake** [comment]
submit baker ID: 290
submit account address: 4KuQ8SZZ3P7ycbmtpPJKt3rXcMBUZecTUyuiR5wN69NtVjkLPr

**Comment by zeybek-omer** [comment]
Baker ID : 579
Account Address : 4JumHZTY3boCfNXF8a9qP2Jhv3jwsvGpZ3AiZPgwyd68VvQBsG

**Comment by network82** [comment]
Baker ID : 479
Account Address: 3bZRHeemJToMRzveqEJSj2YjnB8CWLQqQjpWzMcycSSJEzc7Pm

**Comment by kbrrgn** [comment]
Name: 
Kubra
Id: 2de8799ad59fdc88
Baker ID : 679

Account Address: 4QEoT3x4Ja5teG28M7NdyNuCdvzuBm3LXiQ3Frhio1vMXRQ9Nt

**Comment by mrcnode** [comment]
Baker ID : 379
Account Address: 4ozcgTyH2oNS43wipFuXM8nN5RXGDQmri2VMKKZtmJsFEvabGA

**Comment by Supernode-s** [comment]
Baker ID: 198
Account Address: 3udLrqSxy4gaiVP5RvADzahjZpBii2MMn9T6E1HtGKMaYMdPHa

**Comment by BeytullahEVLENDI** [comment]
baker ID: 505
account address: 4JbHE3nXgojiPAGuMnU3etCWybf4dhaf3c8MruiE3xoDdYgEhq

**Comment by kryatsvn** [comment]
Node name: kry2concordium
Node ID: 19a6be158ad592f1
Baker ID: 642
Account Adress: 3YN4FX8FfLrmrNM5ADm4DAEAM8NrcBnThe5vGroupqMbtMZaxz

**Comment by kryatsvn** [comment]
Node ID: 19a6be158ad592f1
Baker ID: 642
Account Adress: 3YN4FX8FfLrmrNM5ADm4DAEAM8NrcBnThe5vGroupqMbtMZaxz

**Comment by Erdincgumus** [comment]
Account adress: 3P13XoWzQXRiS2xVaRjpZ5D3zd2MJFX91o9vB3aHqguiejVMvb
Baker ID: 748

**Comment by sonerbo** [comment]
Baker ID: 687
4AsdEaWG5ftyFCEDSuq7PvePc8bzC7QVLbuVXqdGVZ156fVDRz

**Comment by psypro123** [comment]
Node ID: 99b99b692439767a
Baker ID: 767
Account Address: 3V7nXLBpEfsFivLAXdeTBK3UDzv65RG3xVc8dLhzUVTTQm2LyX

**Comment by MehmetAliATLI** [comment]
Baker ID: 653
Account address: 3zYkjow9SyPV5WSPb9L7RpeRcv1ZWY13nzcSx1Rhj2JdcedjKm

**Comment by drtakkus** [comment]
Baker ID:528
Account adress: 3stUbfxvrdgMqSr31G8gmvDq7ryT7TwnZLutTvuXsQG8LdWsT6

**Comment by Necooo7** [comment]
Baker ID : 790

Account Address : 3JeW9TNdWsRPfAFGddqxLJaiHnnu23m8tkmEmzgYHsWutSy3Rr

**Comment by driboooooo2** [comment]
Baker ID : 532
Acoount Address : 4aNToJvwqU6inpURaeLABRxaDcDXyvFHKLaW3jRjKSQvgBLaXR

**Comment by ftosun** [comment]
Baker ID - 805
Account address - 36FKRctMVF3K2xk8qynyXhhHxyjE6XWdnL4ALE5bLUY4WySDzp

**Comment by nidaozkan95** [comment]
Baker id : 836
Account address: 31BcRahz9RxJunESGkm55Qn7o2bDf3iQwxxh65ZghmJFswgNYL

**Comment by coreman000** [comment]
submit baker ID: 268
submit account address: 3EdsZVbfAWZk2DsBErAWjm75CY96br933JpVoeyVL7YCWyz3bu
submit observations, if any: sometimes baking starts pending, time to stake freezes(time does not change or ticks plus minute-minus minute), but everything works perfect in other browser.

**Comment by ftosun** [comment]
Baker ID - 805
Account address - 36FKRctMVF3K2xk8qynyXhhHxyjE6XWdnL4ALE5bLUY4WySDzp

**Comment by bozard** [comment]
Baker ID : 840
Account adress - 2zrmfFUbj4yiQ6AbganSF3havFbYGdf31wtr7d3HawZRC33aeW

**Comment by darko313** [comment]
Baker ID : 865
Account adress - 3v7nDZs7QgzXemvpa6jNvLHtRmoKbmvRUiDydqCm6YiYSSvBMH

**Comment by doantn09** [comment]
Baker ID : 828
Account Address : 4crGbqbWezTowRdkUvY4iKg9PPBo9RUNEqWWcXR1B76QcqFWBW

**Comment by erknfe** [comment]
Baker ID - 555
Account address - 45At3vkVVPn2ixxGmjXLqDzGR6SKjrGHyKqhk7ngkEgVD9Ypg6

**Comment by Kkemosabe** [comment]
Backer ID - 842
3ZFGHL45RRMoppP5GJwMRgBxr9KUSXFvmntCBvs4byWKCpnL28

**Comment by betulum34** [comment]
Baker ID : 784
Account Address : 4iu4hiNfpLNmkftzX3FQxExvJ83aXswevC5hYj9SN4o8yrJqoj

**Comment by snnucr2** [comment]
Baker ID : 907
Account Address : 47VSJ2a4VKPhcQJcrgdGpAeGsQ9qTAybx8QbMbExBoSasnQPGN

**Comment by akindemiroz** [comment]
Baker ID : 838
Account Address : 3cfB5idPSZgkCT7nC68V59sWfNBgNRRNFokBE8R5HYnEXNfm55

**Comment by trmetan** [comment]
baker ıd:915
my adress  :41bK3XZoRxtB4qRDoRyRS895xPtVMbPo27b8zxGkcZkJyWNCTa

**Comment by BreenLine** [comment]
Baker ID: 715

Account Address: 4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZ

**Comment by ufukoc** [comment]
Baker ID: 751

Account Address: 3yJpKPMhQj5AU3FMSPDbpuaPVFwccgJXhA8gaCLFvFupMMXBHF

**Comment by Aslisa** [comment]
BakeBaker ID - 430
Account Address - 3WYMAVFB9evf7BagUPdACymhGDCsHmKCW71K27GbJhCoSbKdkb

**Comment by coinalemdar** [comment]
BakeBaker ID - 375
Account Address - 4dCR2q3WJFNEDM6pS6rZvQP8Xpx42PRn1yXzp4t2fGfsutsvB8

**Comment by ogumogumakyak** [comment]
Baker ID: 995

Account address: 38FkQTWvGwqxkGfuxzW2V3NpyLnR2PK1wVX1PPxJ6NS7gnfjd2

**Comment by wormaxe** [comment]
Baker ID: 914

Account address: 3HmrRPwvQMHRZkTk2WqTcxLXh7im21NNaKQT8ikMa3mbV2pmbU

**Comment by minatofund** [comment]
Baker ID: 1022
Account address: 373xpWxFWxwYCZqfX2A6BoLtHhsK1bD8r5ufPTAAJyCg41GVfB

**Comment by ozerbeg** [comment]
Baker ID: 221
Account address:4gR6oUPM29TQNim6ShqR8Jdfx4wqHo6yEybZuN3fqMduyEdn65

**Comment by okannako** [comment]
Baker ID - 1048
Account Address - 3W4EbUdvmDFizYeRFCDQ2gdCN2WdKzh5dzdgHtHJpeeEwpCxDw

**Comment by SymphonyQntm** [comment]
Baker ID - 864
Account address - 4Pc2BQze9yVra1TWx3gU8D8tAfZ1i3myJ7DAm2U51mnzHP4bkd

**Comment by huseyinfe** [comment]
Baker ID: 508
Account Address: 3ixS2Vz4kVUgmNetd9aQghNVjQPrL81T8Nabck1TgxWDZjqthV

**Comment by kubrafe** [comment]
Baker ID: 504
Account Address: 3yf19mxTZGoCbgzrx43hMDFrNzbvyTY2C3t64mhqwAznpHakRt

**Comment by donadel01** [comment]
Baker ID: 1033
Account Address: 4Pp9DmRESCN9Z74GYRuKDdqVTyxxmeYhUDo5jocf3jWv2XBu3Y

**Comment by donadel01** [comment]
Baker ID: 1087
Account Address: 4dkfgtpj7vQMqNMrYF2NTyJb4YPUe5BnBptWeJH3jUTnJizb53

**Comment by slon36** [comment]
Baker ID : 1046
Account Address: 4g3DBxNm28g9D18MnqCz86PXTtuvLSuacY8kRMvxwdd36RXbCb

**Comment by MVPLA** [comment]
**Baker ID** : 1045
**Account Address:**  4jJ5PKMVJQD4XQkPaBMuHsZ8UiCZ64TgVb4UNqP1DtGDR7rxR4

**Comment by okannako** [comment]
Baker ID - 1158
Account address - 3W4EbUdvmDFizYeRFCDQ2gdCN2WdKzh5dzdgHtHJpeeEwpCxDw

**Comment by alevoncel** [comment]
Baker ID: 1165
Account Address: 4dkfgtpj7vQMqNMrYF2NTyJb4YPUe5BnBptWeJH3jUTnJizb53

**Comment by okannako** [comment]
Baker ID - 1177
Account address - 3W4EbUdvmDFizYeRFCDQ2gdCN2WdKzh5dzdgHtHJpeeEwpCxDw

**Comment by jnbn** [comment]
Baker ID - 242
Account Address - 3hYjKPXywBu5Qmms7zCZUU1zNkXCfupJSVpa4FjruZPx58Voyt

**Comment by edrolu87** [comment]
Baker ID: 1161
Account Address:  34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ

Observations: remainging time is flickering, takes too long to stop baking.

**Comment by edrolu87** [comment]
Baker ID: 1161
Account Address: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ

Observations: remainging time is flickering, takes too long to stop baking.

https://dashboard.testnet.concordium.com/node/bd35a764b4caa77f

**Comment by edrolu87** [comment]
Baker ID: 1183
Account Address: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ

Observations: remainging time is flickering, takes too long to stop baking.

https://dashboard.testnet.concordium.com/node/bd35a764b4caa77f

**Comment by sysdba** [comment]
Baker ID : 1184
Accound Address : 3CxKrSS7V3Sg1o5GF8CcUmebMvSNaDqQ5MBApEED845PjRXs6v

https://dashboard.testnet.concordium.com/node/0f0d3ba18bc41d11

**Comment by dursunalp** [comment]
Baker ID :  1064      
Account  Address : 2wsLwUEDfMsWSFYHskf8pnLsp3NBcr2atJfs34d7dzmaLmSvni
https://dashboard.testnet.concordium.com/node/824c52c634fa7881

**Comment by mrllhyksl** [comment]
Baker ID :1197

Account Adress
3MQD1BUq9ofNQGyijsGMUCcF7bFmsnhw7bL4Civ8DhWodRNZyD

**Comment by mertcan1007** [comment]
Baker ID : 1039

Account Adress
36MyUr4j9h74Ac899rwMPVXiQkcJhjJvLHe89kziTv8dBhkJGn 

https://dashboard.testnet.concordium.com/node/42b4486e8b1aa5ab

**Comment by esmirs** [comment]
Baker ID: 1204
Account Address: 3UATFzjUb5oJHVFPH4qMWjT7FyMheZKDg4eEDLLxNq2ZUaVxMH

Observations: remainging time is flickering, takes too long to stop baking. 2 hours aq

https://dashboard.testnet.concordium.com/node/8d01fe08ba949291

**Comment by melihbozard** [comment]
Baker ID : 1250
Account Address : 2zR2bGF6dhHF8x2FvKEMcyPLPLNpW2KnCkroYJ4KP6hMsotsgA

**Comment by tagpesa** [comment]
Baker ID: 1265
Account Address: 4guPArfki9gezPVpaiyZDzjDyjiybW9D5QavwjemS76FngUco4

**Comment by tugba88** [comment]
Baker ID: 1220
Account Address: 4g8zTfT8csUZ7FNz4okyT6oCCpRf6r6QVkHJAYw415CbnhP7re

Observations: remainging time is flickering, takes too long to stop baking.

https://dashboard.testnet.concordium.com/node/881651fcdfdfc927

**Comment by Aysealp** [comment]
Baker ID  :  1120
Account Address:  3mVA2fLyKXHMJUk2dMaSCGVrdyXxzTbkMkGeTYhaqu3p5EEenW

**Comment by kaznil5** [comment]
baker ID: 1277
account address: 3efeqqMRniBJhiLu8tQhZiujhnnwGvVJ6UqycP83uUgB7xmz6d

**Comment by sidoroffalex** [comment]
Baker ID 158
4YchMueKfofRBt7rMQWfjnrvznPnAHCFdYpSMJM6tacXMz9U8c

**Comment by Maje53** [comment]
Baker ID : 1350
Account Address : 4R8LNdSKsPjMyBWBCkmB3g4jziFXbabxF3JijnnXW1fgQDq5Dt

https://dashboard.testnet.concordium.com/node/345d9d66c25c94b1

**Comment by minivipers** [comment]
Baker ID is 1357
46uYxDUjmLqZ9aHVNDnSUbK1MBmUm2QQubTHASLo4ak2qvpFgQ
takes 30 seconds to reach x.x.x.x:8099

**Comment by wondayer** [comment]
Baker ID : 1359

Account Adress : 4tJp4ennWuQaRQJVm4rB83m24pCVTdwK9BYH88pTMzcuWo4dM2

**Comment by ahmetsaydin** [comment]
Baker ID : 1315
Account Adress : 4Dp4gGP9kMSXF4MXAsjYN3zHSotC6ZKiFks8AApLGA8LnfY9cd
Observation :  I could not join testnet stake and delegation list until restart node.

**Comment by yenerh** [comment]
Baker ID: 1386
Account Adress: 4Jm6LWyTcMC3WCEk6QxGo1yzWa9mSRPy8vMm5Laq9bKQo5fv2Q

**Comment by srcankmk** [comment]
Baker ID : 1227
Account Adress : 4Gp2mZtsbWWzHyLsc7tD8VRCZ2MvrPVizgQmqcY386V3SdzH8U

**Comment by trancetr2** [comment]
Baker ID : 344
Account Address : 42oFC8fS57QwJ5deumuWyjuRGguqP482wiv6g5fa3JNcRdcEcE

**Comment by DragonriderZ** [comment]
Baker ID: 1491
Account Address: 4VxzRHiyHpEg14B1o9mndzeLrfrhY14riLCJN1YF688Nfb8TVf
