### ISSUE TITLE
(B6) Memory and persistent storage

### ISSUE THREAD

**Issue by bissembert1618** [Concordium/Testnet3-Challenges#33]
**Mission:**

- run a node for 7 days (calendar days)
- frequently check RAM usage
- frequently check disk usage of the database

**Submission:**

- submit node ID
- submit machine specs
- provide feedback on RAM and disk usage and expectations
- submit log summaries of the run (see [Logs](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md) for instructions & tooling)

### ⚠️ Submission Note 

We originally asked for full logs, which turned out to be difficult due to log sizes. Please update your submission with the output of new [log summary tool](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md) instead.

**Comment by andrste** [comment]
Node ID

**Comment by kazantip85** [comment]
Node ID: 076bd2a1bd4044a9

**Comment by stguller** [comment]
Node ID: d799d7da5cc9af99

**Comment by stguller** [comment]
Node ID: e30ba43a2638ecc7

**Comment by farukbostansua** [comment]
node ID : c5d124a969c5c7c1

**Comment by bertco** [comment]
Node ID:

**Comment by rezeda88** [comment]
Node ID:

**Comment by hknnr** [comment]
Node ID:  dbd207ceb4bfdbc4

RAM: 1GB
Harddisk: 250GB SSD

**Comment by elturrco** [comment]
node ID : a5b03a5f223c4d99

RAM: 1GB
Harddisk: 250GB SSD

Ram Usage : 62.4 MB
DiskUsage: 0 MB/s

**Comment by devrimdanyal** [comment]
Node ID: a716a8bf551f969e
RAM: 4GB
Harddisk: 500GB SSD

Ram Usage : 62.4 MB
DiskUsage: 0 MB/s

**Comment by vivalldi25** [comment]
node ID : bc2de4c5285d3c08

RAM: 1GB
Harddisk: 250GB SSD

Ram Usage : 66.4 MB
DiskUsage: 0 MB/s

**Comment by ozans28** [comment]
Node ID: 49fdb7942847ee08

HDD: 50GB SSD
DiskUsage: 0 MB/s
RAM | 153 MB / 3072 MB
-- | --
CPU | 199 MHz / 6798 MHz

Node ID: 08801395abf8606a

HDD : 35 GB
DiskUsage: 0 MB/s
RAM | 102 MB / 2048 MB
-- | --
CPU | 134 MHz / 6798 MHz

**Comment by Crypto-Awake** [comment]
Node ID: e9d6fe26fb03fd18
HDD: 120GB SSD
HDD USAGE: 0 MB
RAM:8GB
RAM USAGE: 18,0MB

**Comment by insomnium7** [comment]
Node ID : 5a4c327351edca64
CPU : Intel Core i-7 6700HQ  2.60 GHz
RAM: 16 GB
Harddisk: 125GB SSD

Ram Usage : 19,4 MB
DiskUsage: 0 MB/s

**Comment by gulayse142** [comment]
node ID : c575960f33c93f07

RAM: 1GB
Harddisk: 250GB SSD

Ram Usage : 60.4 MB
DiskUsage: 0 MB/s

**Comment by ZloyMyshok** [comment]
Node ID: dcc8a9e94e5de95e
CPU: Intel(R) Core(TM) i5-7300HQ CPU 2.50GHz
RAM: 16Gb
SSD: 256Gb
![USE](https://user-images.githubusercontent.com/70433632/96156778-23da2f80-0f1a-11eb-8841-125732c02728.png)
She does not use the disk and this is a plus. there is no extraneous additional load. everything works in RAM. the node takes from the processor from 1.5 to 4% of the power. a Docker-like buffer to cope with its task. The noda was launched on October 7th. there are no changes in work or increase in PC resources. or they are so insignificant as to be invisible.
[Log.txt](https://github.com/Concordium/Testnet3-Challenges/files/5386378/Log.txt)

**Comment by edandrada** [comment]
Node ID: aae804235fb5a39e
CPU i7 -3537U 3.00 GHZ
RAM: 8GB
Harddisk: 500GB 
Ram Usage : 66.4 MB
DiskUsage: 0 MB/s

**Comment by Ebruberen** [comment]
Node ID: c89e05fa4d204665
CPU 1 i1
RAM: 25 GB ssd 
Harddisk: 1000 GB 
Ram usage: 60.2 MB
Disk usage: 0 MB

**Comment by Rookie23** [comment]
Node ID: dffc35c76091ef28
CPU: 2vcpu
RAM: 4 GB 
Harddisk: Ssd 25 GB
Experiance: [TODO]
Log: [TODO]
RAM usage: 60.5
Disk usage:0

**Comment by zybk70** [comment]
Node ID: 654436cf379fc1d0
CPU i5 -3230M CPU 2.60 GHZ
RAM: 6GB
Harddisk: 500 GB
Ram Usage : 66.4 MB
DiskUsage: 0 MB/s

**Comment by koen84** [comment]
Uhm, i'm going to venture and say : this is the memory footprint of the binary wrapper and not of the (docker) node running.

**Comment by wallnode** [comment]
Node ID: a9499e2217a5f576
CPU 1 vcore
RAM: 1 GB
Harddisk: 25 GB SSD
Ram usage: %13
Disk usage: 0

**Comment by mdlog** [comment]
Node ID: f78030435465b50f
CPU 2 vCore
RAM: 4096 MB
Harddisk: 80 GB SSD
Ram usage: 40%
Disk usage: 0

**Comment by madilog** [comment]
Node ID: d433a023e8165d4a
CPU 2 vCore
RAM: 4096 MB
Harddisk: 80 GB SSD
Ram usage: 82%
Disk usage: 0

**Comment by psypro123** [comment]
Node ID: 99b99b692439767a
CPU 2 CPUs
RAM: 4 GB
Harddisk: 80 GB SSD
Ram usage: 20%
Disk usage: 0

**Comment by ilhamm24** [comment]
Node ID : 2a0a1713b90b4e8b
CPU : 4 Cores (20% usage)
RAM : 8GB (3.4% usage)
Disk : 200GB SSD (20% usage)

**Comment by pasha036** [comment]
Node ID: 1bcb66929636f504
CPU 1 vCore
RAM: 1024 MB
Harddisk: 25 GB SSD
Ram usage: 11%
Disk usage: 0

**Comment by TravelerAnu** [comment]
Node ID : 1d3b0e7d15b7be69
Name : angin

CPU : AMD x4 2.20 GHz
RAM : 4 GB
Harddisk : 450 GB SSD
Ram Usage : 18 MB
Disk Usage : 0

**Comment by sonerbo** [comment]
Id: 37cd107972c63ed4

intel G3260 3.20 ghz
Ram 8 gb
harddisk: 120gb ssd

Ram usage : 7,9mb
disk: 0

**Comment by kryatsvn** [comment]
Node ID: 19a6be158ad592f1
Cpu: e2-medium 2 vCPU, Intel Haswell
Ram: 4 GB
Harddisk: 25 GB SSD
Ram usage :61.5 MB
Disk Usage : 0

**Comment by MehmetAliATLI** [comment]
Node ID: 876d534cf6fa9f7b
CPU 1 vCore
RAM: 1GB
Harddisk: 25 GB SSD
Ram usage: 13%
Disk usage: 0

**Comment by Vladislav1z** [comment]
Node Id: a309662f0bc535a8
Architecture: x86_64
Model name: Intel(R) Xeon(R) CPU @ 2.30GHz
Ram: 4 GB
Harddisk: 30 GB SSD
====
information in the repository
![ram](https://user-images.githubusercontent.com/72387556/96339617-8d834680-109e-11eb-9838-5acd43ce3add.JPG)

**Comment by Supernode-s** [comment]
Node Id: 34b256504b67d94b
Model name: AMD EPYC 7B12
CPU MHz: 2250.000
Architecture:  x86_64
RAM: 4 GB
Harddisk: 30 GB SSD
**Information in the repository**

**Comment by EK2503** [comment]
Node Id: 73d375d5408c721d
Model name: Intel(R) Xeon(R) CPU @ 2.30GHz
RAM: 4 GB
Harddisk: 30 GB SSD
OS: ubuntu 18.04
------> [repositories](https://github.com/EK2503/Testnet3-Challenges/blob/main/Bakers/B6/b6%20submission%20space)

**Comment by Irina0880** [comment]
Node ID: b4ebed426d7f1cda
Ubuntu 18.04.5
Model name: AMD EPYC 7B12
Harddisk: 30 GB SSD
RAM: 4 GB

Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           394M 1000K  393M   1% /run
/dev/sda1        29G  7.7G   22G  27% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop2       56M   56M     0 100% /snap/core18/1885
/dev/loop1       31M   31M     0 100% /snap/snapd/9279
/dev/sda15      105M  3.6M  101M   4% /boot/efi
tmpfs           394M     0  394M   0% /run/user/1002
/dev/loop3      128M  128M     0 100% /snap/google-cloud-sdk/154
/dev/loop4      128M  128M     0 100% /snap/google-cloud-sdk/155
/dev/loop0       31M   31M     0 100% /snap/snapd/9607

**Comment by TVV61** [comment]
Node ID: bc82e6aa8449590f
Model name: AMD EPYC 7B12
Harddisk: 30 GB SSD
RAM: 4 GB
Statistics in the repository

**Comment by bozard** [comment]
Node ID: 9b710cb25ef7c9ad
CPU 1 vCore
RAM: 1024 MB
Harddisk: 25 GB SSD
Ram usage: 12%
Disk usage: 0

**Comment by Kkemosabe** [comment]
Node ID: d3f0897e637ff9ce
Cpu: 2 vCPU, Intel Skylake  
Cpu usage - 8-16%
Ram: 4 GB 
RAM usage - 10-14%
Harddisk: 30 GB SSD
Disk Usage : 
![image](https://user-images.githubusercontent.com/48792235/96365076-c70f8c80-1146-11eb-96c7-5bad12c87d0e.png)

**Comment by betulum34** [comment]
Node ID: 8d631afb688f5f50
CPU 1 vCore
RAM: 1024 MB
Harddisk: 25 GB SSD
Ram usage: 11%
Disk usage: 0

**Comment by snnucr2** [comment]
Node ID: bd4734b63de8e19a
CPU : 1 vCore
RAM: 2 GB
Harddisk: 50 GB SSD
Ram usage: 8%
Disk usage: 0

**Comment by akindemiroz** [comment]
Node ID: 5effb2c031278f5e
CPU 1 vCore
RAM: 1024 MB
Harddisk: 25 GB SSD
Ram usage: 10%
Disk usage: 0

**Comment by erknfe** [comment]
Node ID: 8ada2caba4182965
RAM: 8GB
Harddisk: 200GB SSD

Ram Usage : 482.9 MB
DiskUsage: 0 MB/s

**Comment by donadel01** [comment]
Node ID: 5bbdaa9fd9d3f13d
CPU : 1 vCore
RAM: 2 GB
Harddisk: 50 GB SSD
Ram usage: 8%
Disk usage: 0

**Comment by donadel01** [comment]
Node ID: 04da7a8399c95de4
CPU : 1 vCore
RAM: 1GB
Harddisk: 25 GB SSD
Ram usage: 9%
Disk usage: 0

**Comment by slon36** [comment]
**node ID:** d6decaa28e70c084
**machine specs:**
Bus info          Device       Class      Description
=====================================================
                               system     Computer
                               bus        Motherboard
                               memory     3935MiB System memory
cpu@0                          processor  Intel(R) Xeon(R) CPU @ 2.30GHz
pci@0000:00:00.0               bridge     440FX - 82441FX PMC [Natoma]
pci@0000:00:01.0               bridge     82371AB/EB/MB PIIX4 ISA
pci@0000:00:01.3               bridge     82371AB/EB/MB PIIX4 ACPI
pci@0000:00:03.0               generic    Virtio SCSI
virtio@0                       generic    Virtual I/O device
pci@0000:00:04.0               network    Virtio network device
virtio@1          ens4         network    Ethernet interface
pci@0000:00:05.0               generic    Virtio memory balloon
virtio@2                       generic    Virtual I/O device
pci@0000:00:06.0               generic    Virtio RNG
virtio@3                       generic    Virtual I/O device
                  veth537f7c3  network    Ethernet interface
                  docker0      network    Ethernet interface

**RAM and DISK usage:** 
  total        used        free      shared  buff/cache   available
Mem:           3935         787         226           0        2920        2877
Swap:             0           0           0

Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1028-gcp x86_64)
  System information as of Thu Oct 22 12:41:32 UTC 2020
  System load:  0.04              
  Usage of /:   16.8% of 48.29GB   
  Memory usage: 24%                
  Swap usage:   0%                 

**Logs:** submitted to my repository

**Comment by MVPLA** [comment]
**node ID:**      04ccfe7aab9c3387

**machine specs:**

Bus info          Device       Class      Description
=====================================================
                               system     Computer
                               bus        Motherboard
                               memory     3935MiB System memory
cpu@0                          processor  Intel(R) Xeon(R) CPU @ 2.30GHz
pci@0000:00:00.0               bridge     440FX - 82441FX PMC [Natoma]
pci@0000:00:01.0               bridge     82371AB/EB/MB PIIX4 ISA
pci@0000:00:01.3               bridge     82371AB/EB/MB PIIX4 ACPI
pci@0000:00:03.0               generic    Virtio SCSI
virtio@0                       generic    Virtual I/O device
pci@0000:00:04.0               network    Virtio network device
virtio@1          ens4         network    Ethernet interface
pci@0000:00:05.0               generic    Virtio memory balloon
virtio@2                       generic    Virtual I/O device
pci@0000:00:06.0               generic    Virtio RNG
virtio@3                       generic    Virtual I/O device
                  docker0      network    Ethernet interface
                  vethe0385de  network    Ethernet interface
				  
				  
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1028-gcp x86_64)
  System information as of Thu Oct 22 14:11:21 UTC 2020
  System load:  0.4                
  Usage of /:   16.9% of 48.29GB   
  Memory usage: 25%                
  Swap usage:   0%      

**Logs:**    submitted to my repository

**Comment by donadel01** [comment]
Node ID: f831ab99788ead80
CPU : 1 vCore
RAM: 1 GB
Harddisk: 25 GB SSD
Ram usage: 8%
Disk usage: 0

**Comment by alevoncel** [comment]
Node ID: f831ab99788ead80
CPU : 1 vCore
RAM: 1 GB
Harddisk: 25 GB SSD
Ram usage: 8%
Disk usage: 0

**Comment by jnbn** [comment]
Node ID: 0eed83ebf7ae76d1
Macbook Pro i9, 2.3 GHz
16 GB Ram

Running On Docker w/ 
8CPU 
2GB Memory 
1GB Swap 
60 GB HD

uptime:
21:06:08 up 9 days, 22:32,  0 users,  load average: 0.06, 0.09, 0.10

`              
total        used        free      shared  buff/cache   available
Mem:        2038184      877252       82880         788     1078052     1045260
Swap:       1048572       67340      981232
`

`
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G  7.5G   48G  14% /
tmpfs            64M     0   64M   0% /dev
tmpfs           996M     0  996M   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda1        59G  7.5G   48G  14% /etc/hosts
grpcfuse        793G  335G  424G  45% /var/lib/concordium/config
tmpfs           996M     0  996M   0% /proc/acpi
tmpfs           996M     0  996M   0% /sys/firmware
`

`
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                 
23 docker    20   0 1026.6g 771844 181728 S  50.0  37.9 780:30.61 p2p_client-cli         
`

**Comment by dursunalp** [comment]
Node ID :  824c52c634fa7881
1 GB  / 1 CPU
25 GB SSD  Disk
1000 GB transfer
ubuntu 20.10x64

**Comment by edrolu87** [comment]
Node ID: bd35a764b4caa77f
CPU: 1 vCore
RAM: 1024 MB
Storage: 25 GB SSD
Bandwidth: 17.28 GB of 1000 GB
OS: Ubuntu 20.04 x64
CPU Usage: %13

**Comment by esmirs** [comment]
Node ID : 8d01fe08ba949291
CPU : Intel Core i-5 7500 3.40 GHz
RAM: 16 GB
Harddisk: 1 TB + 256 gb SSD

Ram Usage : 356.3 MB
CPU Usage: %4.83
Network : 5.3 GB / 5.3 GB
OS : windosw 10 pro

**Comment by melihbozard** [comment]
Node ID: f19cc2517b1e9b37
CPU 1 vCore
RAM: 2 GB 
Harddisk: 50 GB SSD
Ram usage: 9%
Disk usage: 1%

**Comment by tugba88** [comment]
Node ID: 881651fcdfdfc927
CPU: 1 vCore
RAM: 1024 MB
Storage: 25 GB SSD
Bandwidth: 19.9 GB of 1000 GB
OS: Ubuntu 20.04 x64
CPU Usage: %18

**Comment by ogumogumakyak** [comment]
Node ID: cdf1400135749adc

CPU: 1 vCore

CPU Usage: 15%

RAM: 1024 MB

Storage: 25 GB 1SSD

Bandwidth: 65.76 GB of 1000 GB

OS: Ubuntu 20.04 x64

![image](https://user-images.githubusercontent.com/39438257/97785862-b3d5d580-1bb8-11eb-86e6-a272b8a01f50.png)

**Comment by 0011010000110010** [comment]
Node ID: 1ed4c513021080e1
CPU: 1 vCore
CPU usage: 21%
RAM: 1024 MB
Storage: 25 GB SSD
Bandwidth: 80.05 GB of 1000 GB
OS: Ubuntu 20.04 x64

![usage](https://user-images.githubusercontent.com/47231270/97785851-a1f43280-1bb8-11eb-9d6c-acf3fc10a82e.png)

**Comment by wormaxe** [comment]
Node ID: ac580bd551910bdf
CPU: 1 vCore
CPU usage: 
![Ekran Alıntısı112](https://user-images.githubusercontent.com/65225577/97785922-1038f500-1bb9-11eb-9a80-04ae9065b6f2.PNG)

RAM: 1024 MB
Storage: 25 GB SSD
Bandwidth: 
![Ekran Alıntısı 111](https://user-images.githubusercontent.com/65225577/97785916-0911e700-1bb9-11eb-9d5d-be494edea85a.PNG)
Disk usage:
![Ekran Alıntısı113](https://user-images.githubusercontent.com/65225577/97785936-25158880-1bb9-11eb-870b-f35f7102b13a.PNG)


OS: Ubuntu 18.04 (LTS) x64

**Comment by Aysealp** [comment]
Node ID:  59eddc588e6924d8
1 GB / 1 CPU
25 GB SSD Disk
1000 GB transfer
ubuntu 20.10x64

**Comment by coinalemdar** [comment]
Node ID : 3573caaf20869e2d
1 vCPUs
1GB / 25GB Disk

Ram Usage : 19,4 MB
DiskUsage: 0 MB/s

Ubuntu 20.04 (LTS) x64

**Comment by Aslisa** [comment]
Node ID : 61c07c111c9f730c
1 vCPUs
1GB / 25GB Disk

Ram Usage : 19,4 MB
DiskUsage: 0 MB/s

Ubuntu 20.04 (LTS) x64

**Comment by minivipers** [comment]
Node ID : d105d00749efe743
"Virtual box on windows" ubuntu mate 20.04 LTS 
CPU: INTEL i7 4GHZ
RAM : 16.7 GB
Harddisk : 590 GB SATA
![Capture](https://user-images.githubusercontent.com/15265079/97811983-e3ebaa00-1c86-11eb-9a00-809073d20e82.PNG)

**Comment by wondayer** [comment]
Node ID: 296c781594092ee5
CPU : 4 vCore
RAM: 4 GB
Harddisk: 50 GB SSD
OS: Ubuntu 18.04 x64

![Uploading Snipaste_2020-11-04_11-55-15.png…]()

**Comment by yenerh** [comment]
node ID : ab58bf97f3af273e
1 vCPUs
1GB 
25GB Disk
Ram Usage : 19,8 MB
DiskUsage: 0 MB/s

Ubuntu 20.04 (LTS) x64

**Comment by BreenLine** [comment]
Node ID: cc13e70de9984ba2
Node Name: breenline
Address: 4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZc
Link: https://dashboard.testnet.concordium.com/node/cc13e70de9984ba2

OP: Ubuntu 20.04.1 LTS
CPU: Intel i5-3230M
GPU: Nvidia 710M
RAM: 8GB
DISC: 1TB HDD

While working normaly CPU, RAM, DISC and Network usage was low. When I restart the node, I monitored that,: First Network than CPU usage increased. Also, without minified log tools, ordinary retrive log command crashed my pc due to huge Ram and Disc usage. 

[concordium-testnet-system-report.log](https://github.com/Concordium/Testnet3-Challenges/files/5601316/concordium-testnet-system-report.log)
[concordium-testnet-node-177eea3b23580fe9733233242daa4633d6022b46b2ac1ba69663ba95d0b898bf.log](https://github.com/Concordium/Testnet3-Challenges/files/5601317/concordium-testnet-node-177eea3b23580fe9733233242daa4633d6022b46b2ac1ba69663ba95d0b898bf.log)
