### ISSUE TITLE
(ID2) Create identities and accounts using production environment

### ISSUE THREAD

**Issue by bissembert1618** [Concordium/Testnet3-Challenges#36]
**Mission:** 
- create a real-life identity (using the production environment) with a physical identity paper supported for your country
- create 2 accounts; make at least 1 identity data attributes public (**_When choosing an attribute, keep in mind that this attribute is publicly shown on the blockchain_**)
- request GTU drops for each account

**Submission:**
- submit document type and nationality
- submit account addresses
- submit public data attribute(s)
- submit device make and model and OS version

**Comment by andrste** [comment]
Account addresses

**Comment by stguller** [comment]
Driving License-Turkey
Driving License-Turkey
3hcm3jxuP5Qdmc5rQM3G6KimJwMCJSQ8AN3A2QxY6qxcVcSpSW
49qgPEXSPXShJRb6G8gz598fCaXq5yVMCmViKScQhZcH41rJNd
![image0](https://user-images.githubusercontent.com/32449978/96093747-32522800-0ed5-11eb-875d-2955a2e568c5.png)
iphone SE, IOS 13

**Comment by bertco** [comment]
submit document type and nationality
submit account addresses
submit public data attribute(s)
submit device make and model and OS version

**Comment by rezeda88** [comment]
submit document type and nationality
submit account addresses
submit public data attribute(s)
submit device make and model and OS version

**Comment by EmreNOP** [comment]
submit document type and nationality
Driver License / Netherlands
submit account addresses
Account 1 = 3ZfCBDZS5MBwmKMuGjkRPSMaHNbdQvgxEFCspwpveJ5iEpGJkR
Account 2 = 4fLndv52R1YRLWix2KMh7huMH66vHzDnRV1j5NcLT59XLuH4m2
submit public data attribute(s)
Identity Document Issuer = Netherlands
submit device make and model and OS version
Huawei P30 Pro / Android 10 (10.1.0.150)

**Comment by mahofmahof** [comment]
submit document type and nationality
passport/ Turkey
submit account addresses
Account 1 = 4Dp4ghnGKdq1Md5REuYRxnrKb4AjH7VDKQexkrQVX6KR4yFWTZ
Account 2 = 3jFkViSBWk6xxtfaRW5xnPbsRXWL91AVC251Ar2AGkGeWPLJGx
submit public data attribute(s)
Nationality:Turkey
submit device make and model and OS version
Samsung S7edge / Android 8.0.0

**Comment by memur01** [comment]
document type and nationality: passport, Turkey
account addresses: 3URm9PR6kGJMnaUqPdggRmYMpMv2azW1dNmo2Pn6RA7bsy6NQc 
386fS9xsfzp1DXWd8urJysvWzwjMKDNUu6udY2Q3h6zzf1R8Xm
public data attribute:
Country of nationality: Turkey
device make and model and OS version: iphone 7 ios 13.6.1

**Comment by lopotras** [comment]
document type: passport
nationality: polish

addresses:
1. 3QCZjoAxMbPW8M6PW5id51cVAs6QFhZHSNZALjDeAuBSTumGHf
2. 3s7BC1z9YEjoWvsv4HwUcpc8GJjE8yY6o4sY5dx5jQy66X4y8S

public data attributes:
1. Identity Document Type: Passport, Country of Nationality: Polish
2. Identity Document Type: Passport

Device make and model and OS version:
OnePlus 5 A5000/ Android 9 (OxygenOS 9.0.11)

**Comment by Marius83-web** [comment]
submit document type and nationality
Driver License / Romania
submit account addresses
Account 1 = 3qWDDXHfdxtwHqNb4WGGZWRnEAL4v1JGKtcLKiR2x2vk356QvD
Account 2 = 3eP9Q2U5jcEFAJov69HYD8jhoQXa9q3YyLxzWxdz219XJkMers
Account 3 = 4YsV1PTpTKvjr7d9v2sVU4vmdgfrjxnddkBQkrb7ajVBXFYyY5
submit public data attribute(s)
Identity Document Issuer = Romania
submit device make and model and OS version
Huawei Mate 10 / Android 10 (10.1.0.150)

**Comment by hknnr** [comment]
node ıd: dbd207ceb4bfdbc4

**Comment by hknnr** [comment]
document type: Drive License
nationality: Turkey

addresses:

3AnSuw1wjZWAnwMPhvLFAr6ZmCkGcKaJvevYvNaGYBsJw5mvCr
4EqNFnkUjBS1FoGaPpQfQhAKUVNDxr85UYbDACGk5XSpov6FZS

Device make and model and OS version:
Samsung S9 SM-G950U1

**Comment by devrimdanyal** [comment]
document type: Drive License
nationality: Turkey

addresses:
3QpXKBR7zG45bBGHTUzrWgteXj1nHL43CnAYauiW3Ft9vU3LHj

4cfMKiRyHEmDa4ycWbc6YmjAapH5XCbK1yit4XXbTUU1ygsPyq

3ye2tvnF9y7sQ53zmvmvisBtfGbqpek2sJSuB1CVVbojAE6zHq

4WN3ByvqGSvnDyWKUrxdShR3czX29sK7CA2zit4p8TqcWQNocX

3gQX6zQ9Ejkk6RD1zsTeCkLGjGkaVbHFT9UvEGnx5YJmmf4RiU

Huawei p smart android 10.0.0.28

**Comment by boss95rnd** [comment]
document type: Passport
nationality: Russia

account addresses and public data attribute(s):

1) 48rfFFyiZJp5owBDi3epPdx6t4rq4PHREdfm1wG8rysLLtuKT7
Country of Nationality: Russia

2) 3cBfpoPS6TXgk6niG1iDt2agxvTEYdAtPxkAoGV41auj72uMT7
First Name: Nikita

Iphone XS MAX: IOS 13,7

**Comment by Vladislav1z** [comment]
document type and nationality: passport, Russia
account addresses: 
35W6QvET3tuZMCjHhkD2bmhzCVudt9iTbcAfbwts2U4RYoZf8s
3LXDx8hzDGMgv1p6XqejutRLio4KeDaFLrgNnAoiib79bYYrqU
public data attribute:
Country of nationality: Russia
Indentity Document Type: Passport
device make and model and OS version: iphone 7 plus ios 14.0.1

**Comment by gulayse142** [comment]
document type: Drive License
nationality: Turkey

Addresses: 4iH2AzBqxvSxBz6WfHDQpFZheaEKWcAipKdsqZ4ncwHLfknSqB


Device make and model version:
Samsung S9 SM-G950U1

**Comment by liray-unendlich** [comment]
Document type: Passport
Nationality: Japan

addresses:
1. 3vc3MV3g1T49xYDhpQ3VJUPMRjTiF6RehwtCuaJ7kT69MwX78o
2. 3gdtXpAYFg8bcYoLboi7yoEBQxvC7hmxfZs6mBvfYDMjsaQUzP
public identity data attributes:
1. Country of Nationality: Japan, Identity Document Type: Passport
2. Country of Nationality: Japan, Identity Document Type: Passport

Device make and model and OS version:
iPhoneXs, iOS 14.0.1

**Comment by Chibunke** [comment]
document type: National ID and nationality: Nigeria
account addresses:

1) 38djioHWtCTeeLrma5Nee6Y8gx5jYDvKMcJ9bzutW64v38HgzB
2) 45pApnaHQaEdSRqhasAbUJzmaS3g7Lr6aAqbMF2KnJEpFWEhyJ

public data attribute(s)
1) Country of Nationality: Nigeria, Identity Document Type: National ID card
   

device make: Tecno and model: Tecno KC8 and OS version: Android 9

**Comment by EK2503** [comment]
document type and nationality: passport, Russia
account addresses:
Addresses:  44bjQ8KiWEDNDR9TVVzcMSw6eqVRdyQnEfb8Dm1Pozmbe6xWPY  public data attribute:
Country of nationality: Russia
Indentity Document Type: Passport  
Addresses:  3MZT7UP7n3LHee1QiG15qJKmsB1TgfBbNJ71zXehqpVQ3demx3  
public data attribute:
Country of nationality: Russia
Indentity Document Type: Passport
device make and model and OS version:  Apple iphone xs, IOS 14.0.1

**Comment by TO-BOwan** [comment]
Account 1: 
document type and nationality: Driving license, Turkey
account addresses:  32uQSGuPYkAzxjzEDioWJPgHBprwB3q4T9XZic5g6VtQg8wViz   
public data attribute: Identity document type : Driver license
device make and model and OS version:  Apple iphone 6s plus, IOS 14.0.1   

Account 2: 
document type and nationality: Driving license, Turkey
account addresses:  44mTuKhVRcQ9vMpGLxVg83S3BFRdPeWaARnpdCNAjsHLx5Pz2g   
public data attribute: Identity document issuer : Turkey 
device make and model and OS version:  Apple iphone 6s plus, IOS 14.0.1

**Comment by Shulepov** [comment]
document type and nationality: Passport, Russia
account addresses: 37qiTNg3qtiiH5HnFex1nSfEmnoghomV7fJoECcRq1i4NRxubW
public data attribute: None
device make and model and OS version: iPhone X, iOS 14.0

**Comment by zybk70** [comment]
document type and nationality: Passport, Turkey
Account address: 3VjC88swb5V73vpoiANbVDNJj5hvb2SAqhCiAaNhn5b5eDjdqd
public data attribute:
Country of nationality: Turkey
device make and model and OS version: iphone XS ios 14.0.1

**Comment by edandrada** [comment]
document type and nationality: Driver Licence, Turkey
account addresses:
32kZjASdbDS884V9pygBXr4C8CP9X3zaBJoMX7PHsugCqAeycN
2yorR5XHovqRD53EUPD49pL2wEWXtpxB2i6gfvszMpLGiaSxYG

public data attribute:
Country of nationality: Turkey
Indentity Document Type: Driver Licence

Device make and model sm-g6100 Android Version 9

**Comment by TravelerAnu** [comment]
document type : driver license
nationality : turkish
account1 : 3jAAeY568MpUu3as3mCe7fKu41eerRQhTm3ffjj4P5V1Ab2sg3
account2 : 4X6hzSg6XohkvHVyM2x9EKr9LUcbBw3q8E7HkbdwMJtBz1NWHm

public data attribute(s) : 
country of nationality Turkey

device make and model : Samsung S8+

**Comment by Ebruberen** [comment]
Pasaport/ Türkiye 
48ddRbSQZZuCKaDakUfpzPNSDRSgLugtqjBSPC2ZvocHMX8GT4
![38AA425A-5C14-44C6-AAF8-B77775355033](https://user-images.githubusercontent.com/72947146/96188504-8564c300-0f47-11eb-8600-5ef2c520eb09.jpeg)

İphone 7 iOS 14.0.1

**Comment by Rookie23** [comment]
Document typ: Passport / Bulgaria
Account adress: 3pmGPBQGgAhKCSLoiWWUwEqUmFS11PhxaxVLTp7rQJEVyKP83u
Public data Country: Bulgaria / Passport
Device make and model: iPhone 7 iOS 14.0.1

**Comment by BreenLine** [comment]
Driver Licence & Turkey

4d46o4XE4yPXg4TJfSXT9FRxTBVEGqxMkqNbBohJCWqCVtSnZc

I submitted all data via Mobile App but I cant share them in here because of privacy.

Samsung A71, Android 10

**Comment by tahacon** [comment]
document type: passport
nationality: Turkey

adress1: 31Y6Nf2oty3UbwGLaoYDTuNDLe46aUZ1a7xBGddBggrqUDEnAT
Last name: Altunok

adress2: 3Z6VZf8jThzN8ni85Uw1ZpzLD97tP9Ky4uFSo2PVtGFi4JupYa
Nationality: turkey

Device iPhone7 iOS 13.7

**Comment by xaochuk** [comment]
Identity Document Type: Passport
Country of nationality: Latvia

Addresses:
3Y1mQCfDd36b3x36xFRcZdbXQi8p9juGnPpKc38kSqW3YHpsbL
3JW1Rv5YC8aS6SVKSaoydF99GpPdePC5QDJiR4rD7N46wpJFAQ

Public data attributes:
First Name: ARTURS
Identity Document Type: Passport
Country of Nationality: Latvia

Device make and model and OS version:
Iphone 8, ios 14.0.1

**Comment by MehmetAliATLI** [comment]
Identity Document Type: Driver Licence
Country of nationality: Turkey

Addresses:
3zYkjow9SyPV5WSPb9L7RpeRcv1ZWY13nzcSx1Rhj2JdcedjKm
3aYpAWsiX53AWonTEgu1Eu4ftCmM7QB61Ye7aDptQCoXaQUry3

First Name: MEHMET ALI
Identity Document Issuer: Turkey

Device make and model and OS version:
Iphone 11, ios 14.0.1

**Comment by Erdincgumus** [comment]
Identity Document Type: Driver Licence
Country of nationality: Turkey

Addresses:
3P13XoWzQXRiS2xVaRjpZ5D3zd2MJFX91o9vB3aHqguiejVMvb
3nwvU7VC2aGjWuJRYUATw1gj1N6dtCAUwahzrd1FJiZdV1YYtV

First Name:Erdinç Gümüş

Device make and model and OS version:Samsung Galaxy S10 android 10

**Comment by coreman000** [comment]
Address: 41MMbHHyy13TDyzfhrmwUN3psvPNvi1S4CfftDdrXEkw5U9t9K
Id: passport, Russia
Public attributes:
Name: Anna

Address: 3EdsZVbfAWZk2DsBErAWjm75CY96br933JpVoeyVL7YCWyz3bu
Id: passport, Russia
Public attributes:
First name: Mikhail 
Last name: Krasnoselskii

Device: Samsung A50 Android 10

**Comment by cdilaver** [comment]
document type: National ID Card
nationality: Turkey
Name: Caglar

addresses:

4JfPvnfSmtXW9fZ9Ttwog2Aynw7iQrmGH7n6gT8PkuYrR85xxX

41vru7ceDCnaEVdHk55f5xvjBaZekFEoSJvCvmckzmnbgyfiDN

Xiaomi Poco F2 Pro/ Android  12.0.3.0

**Comment by Supernode-s** [comment]
document type and nationality: passport, Russia
account addresses:
4PYomVNGoqLBBZttN8dfD6SLHk6yB4j5p2bc6V6X6LbwuvCN83
3fGv4ZNGUcjWz36GmuMWjd8sXUubqyrnS3mp7Mj2VTHiNPa75f
public data attribute:
Country of nationality: Russia
Indentity Document Type: Passport
device make and model and OS version: iphone SE ios 14.0.1

**Comment by kbrrgn** [comment]
Identity Document Type: Driver Licence
Country of nationality: Turkey
account addresses:
4QEoT3x4Ja5teG28M7NdyNuCdvzuBm3LXiQ3Frhio1vMXRQ9Nt
3yhAYkinRKfbW9GiBCdKNPDn2mDqr1BGta6QYMaBsF3JSQJRcy
public data attribute:

Device and os info: Iphone 7 ıos 14.0.1

**Comment by BeytullahEVLENDI** [comment]
document type and nationality: Driving Licence / Turkey
account addresses - 1: 4S5uZWksmquGFsHyvUdeegVBgHRfSCyXdgMNfAxKSydx7GReRM
account addresses - 2: 3UzYRdwd32brcGHAYT1PJPVP4byKqen7Pk3Asrcr4E9fXfEsWs
public data attribute(s) : BEYTULLAH
device make and model and OS version : LG G6 - Android 9

**Comment by netman38** [comment]
Document Type: Driving License
Country of nationality: Turkey
Account Adress1: 3eYYhBNquetRaror8ojbTQRoqe6BdTvKB4Dt48LtGcxLjEdMVJ
Account Address2: 4mbsfzZh9zyZsdDEtMy3cXFYWfEv2NAFJ5fpLixekBQYSd6v5C

Public Data Attributes:
First Name: UMIT
Last Name: KAYA
Identity Document Type: Driving License

Device Info: Samsung Note8 - Android 9

**Comment by vivalldi25** [comment]
document type: Passport
nationality: Turkey

Addresses: 43LLtWvEUaSgLt4b4dgtH969vYhMG1gqfA8mnZUkYtK57yXL4f
Fake adress1 : 4Wo3PH6bDNwWq1J67ZAQ4pWx5fw7GL3FSss2U2nNtHKPw7e6VZ
Fake adress2: 44KjKB4JmYrqov7WBKosdcKb3bHNo4niqCjnbrr2wMLVDLSWEg

public data attribute: 

First name: Kubra

Device make and model version:
iPhone 6s ios 14.0.1

**Comment by adali125** [comment]
Identity Document Type: Driver Licence
Country of nationality: Turkey

Addresses:
4MKXESZsTRPUadHM1EJmGNwRTTuMF5JsGX6tkSUf7pa4BaAT6V
4jaUXZfYLopMa5Zo3DCrW4UH96LkB2DgDXAx4sMJKtrvZzPnnW
First Name: Nilgün Gümüş
Device make and model and OS version: General Mobile Gm8 Android 9

**Comment by Necooo7** [comment]
document type: Driver License
nationality: Turkey

addresses:
3JeW9TNdWsRPfAFGddqxLJaiHnnu23m8tkmEmzgYHsWutSy3Rr
3c99RnisKq4uJw5xKPHDiUaW2NzXaLMyEAzjrbCJckxBsSmgD2

public data attributes:
First Name : NECARI 

Device make and model and OS version:
Xiaomi Redmi Note 8 Pro - Android 10

**Comment by ftosun** [comment]
1st Account
Adress: 36FKRctMVF3K2xk8qynyXhhHxyjE6XWdnL4ALE5bLUY4WySDzp
Document Type: Driving License
Nationalitiy: Turkish
First Name: Furkan 
Device: Iphone 6s
OS: ios 13.6.1

1st Account
Adress: 4LJJNz2cwoJyyrEmyQ4p8ce2rT9FTeS1TtzAsnxtkzP56wyEqY
Document Type: Driving License
Nationalitiy: Turkish
First Name: Furkan 
Device: Iphone 6s
OS: ios 13.6.1

**Comment by darko313** [comment]
Driving License , Turkey

adresses:
1st : 3v7nDZs7QgzXemvpa6jNvLHtRmoKbmvRUiDydqCm6YiYSSvBMH
2nd : 3Dt8HGsVa2iEdXaiqeAoprVJLYDTKVNK45VF5SYb4JM6bW28yJ

Public Data Attributes: First Name: Cenk (Both)

Device make and model and OS version: iPhone 7 / iOS 13.6

**Comment by berkesim** [comment]
1
Driving License
46nU16VbKyVnF1yh8HDjYvSLr4xsUt8RpQnLRvrSRawdeq5R1N
all (country of residence, first name, id valid to, sex, country. of nationality, id valid from, identity document type, last name, date. of birth, identity document. number)
iPhone 11 iOS 14.0.1

2
Pasport
3UngxfAuEkrhJoKXVuv4gHwmV11fdUpkPhdPgVn2bRUxZ6gLAk
All
iPhone 11 iOS 14.0.1

**Comment by Kkemosabe** [comment]
Document: Passport - Ukraine

Address: 3ZFGHL45RRMoppP5GJwMRgBxr9KUSXFvmntCBvs4byWKCpnL28
PD: Kemosabe

Address: 3gPVoc44Yajb85VRmYzyqV3TBCb6pzvai4uU8aB3Kdg6rPUJEC
PD: Contiki

Iphone SE 
IOS 13.5.1

**Comment by omertfn** [comment]
Identity Document Type: Driver Licence
Country of nationality: Turkey

46amcASJLbqgCaV8TufAZGCc7GVjqvaiesTBfRTdDbvwJpf3ou

4ehCgYJmDFwtnmM9bvJKPhSLmbaPW8zMPCFPd4Fcijfx6QVDcA

3pxZZsFF4srZW2KitLBZZW2zxkDm4R44azJhmwzdyRXobXQkUf

public data attribute:
Country of nationality: Turkey
Indentity Document Type: Driver Licence

iphone 7 plus 
ios 14.01

**Comment by erknfe** [comment]
Account addresses:
45At3vkVVPn2ixxGmjXLqDzGR6SKjrGHyKqhk7ngkEgVD9Ypg6

Public data attribute(s):
First Name: ERKAN
ID Valid to: January, 2027
Identity Document Issuer: Turkey
Identity Document Number: 1234
Date of birth: 01.01.1985
Identity Document Type: Driving License
Last Name: EFE

Device make and model and OS version:
Iphone 7 - IOS 14.0.1

**Comment by Aslisa** [comment]
document type: Drive License
nationality: Turkey

Addresses: 3WYMAVFB9evf7BagUPdACymhGDCsHmKCW71K27GbJhCoSbKdkb
Fake adress1 : 4UuqyUgFp5C7PSmpraK3DbsDCHqdEdEf5s3EZbSASXKqCdYoD7
Fake adress2: 48JFHtku6Z69sXRBPu8YZEc1ruWpdnjyn9iTgiVNyhZo1GuiRu

public data attribute: ALL

Device make and model version:
IPHONE 8 PLUS 14.0.1

**Comment by coinalemdar** [comment]
document type: Drive License
nationality: Turkey

Addresses: 4dCR2q3WJFNEDM6pS6rZvQP8Xpx42PRn1yXzp4t2fGfsutsvB8
Fake adress1 : 4SexWiojCxTLiuttjt6K74utMhEVx4mjzkHoiRZHEoRyQ47oPq
Fake adress2: 3buYzVQVrfznoLMKvN2RoE2razgdv7MtBt8A9WzFpRYdXdiGKT

public data attribute: ALL

Device make and model version:
IPHONE 8 PLUS 14.0.1

**Comment by minatofund** [comment]
document type and nationality: 
Driver's License, Japan

account addresses
1. 41kWekTmyoq4i3SaZedY3sL1VBbcE9XTb299swvgyoAA3QXSgn
2. 3oVY8ayTA9CCED2YEBgP121e21qz8M4pKvCc5KiCMM7qAxsnVN

public data attribute(s):
1. ID Valid to October, 2021
2. Identity Document Issuer Japan

device make and model and OS version:
iPhone 11, iOS 14.0

**Comment by h02051995** [comment]
document type: National id card
nationality: Việt Nam

Addresses: 39KFKd7MVSHPXYuLwtf24kWoqQcauP7bgGMcYwupXYQYCn16cc
Fake adress1 : 3nJMFEtDmnLgT5JpGHpyWHh7QTTFJktLTnoNTiBjxevMxc8nYT
Fake adress2: 3XyPvcBK2wtGiYUKgRpXX4z2gySmgSWXexwiq9AHd9yV1N3WsQ

public data attribute: ALL

Device make and model version:
SamSung A70 -Android 10

**Comment by htkubrat** [comment]
Account-1
Document type: Driver License
Nationality: Turkey
Account address: 3mMxBcvURMCDsNb9v1bsJmB2WWjaZjtKAr1SC14SumZrrg7SSm
Public data attribute(s):
First Name: HATICE KUBRA

Account-2
Document type: National ID
Nationality: Turkey
Account address: 4mfZ4aUP1P23RGre8coDWmYoGs6ZQP4i4Z3bEpQbfwvLKP7cxA
Public data attribute(s):
First Name: HATICE KUBRA
Identity Document Issuer: Turkey

Device make and model and OS version:
Iphone 6s - IOS 14.0.1

**Comment by SymphonyQntm** [comment]
Account-1
Document type: Driver License
Nationality: Turkey
Account address: 4Pc2BQze9yVra1TWx3gU8D8tAfZ1i3myJ7DAm2U51mnzHP4bkd
Public data attribute(s):
First Name: EMIR
Last Name: TURKOGLU
ID Valid to: January, 2029

Account-2
Document type: National ID
Nationality: Turkey
Account address: 4BH7FtVh9eLenNNUn9YZdKCLcDqYcmsCWzkSAckw9UDvsK3ebw
Public data attribute(s):
First Name: TURKOGLU
Last Name: EMIR
Identity Document Issuer: Turkey

Device make and model and OS version:
Huawei P Smart - Android 9

**Comment by huseyinfe** [comment]
Document type: Driver Licence
Nationality: Turkey

Addresses:

3ixS2Vz4kVUgmNetd9aQghNVjQPrL81T8Nabck1TgxWDZjqthV
3JH8S1qy3q21tM5X4VxFvBUh7Y3y3Lmz45R17vwmgqXzeBKwKn

Public data attributes:

First Name : HUSEYIN
First Name : HUSEYIN

submit device make and model and OS version
Huawei p 20 lite - Android 9

**Comment by kubrafe** [comment]
Document type: Driver Licence
Nationality: Turkey

Addresses:

3yf19mxTZGoCbgzrx43hMDFrNzbvyTY2C3t64mhqwAznpHakRt
3AXGCZSa5PjdCGb63w56JuQkLa4nWGmQCPRp39dARdxq7DQmbU

Public data attributes:

First Name : KUBRA
First Name : KUBRA

submit device make and model and OS version
Huawei p 20 pro - Android 10

**Comment by donadel01** [comment]
document type and nationality: driver licence , Turkey
Account address: 4Pp9DmRESCN9Z74GYRuKDdqVTyxxmeYhUDo5jocf3jWv2XBu3Y

4s2fskUiquN1xyFnYcB8NoNPPCJEbzjdR8xVwwECmdvn9peP1R

public data attribute:
Country of nationality: Turkey
device make and model  OS version: reeder p13 blue android 9

**Comment by donadel01** [comment]
document type and nationality: driver licence , Turkey
Account address: 
4dkfgtpj7vQMqNMrYF2NTyJb4YPUe5BnBptWeJH3jUTnJizb53

3fuRMkfgZcDoUyF1AKDKDFvGaD4mYhLzqmeCrGH7CenMjdMWc9

public data attribute:
Country of nationality: Turkey
device make and model OS version: Iphone 7 plus ios 14

**Comment by alevoncel** [comment]
document type and nationality: driver licence , Turkey
Account address:
4dkfgtpj7vQMqNMrYF2NTyJb4YPUe5BnBptWeJH3jUTnJizb53

3fuRMkfgZcDoUyF1AKDKDFvGaD4mYhLzqmeCrGH7CenMjdMWc9

public data attribute:
First Name: ÖNCEL
Last Name: ALEV
Country of nationality: Turkey
device make and model OS version: Iphone 7 plus ios 14

**Comment by burkay5** [comment]
Account name 1: Kimlikdeneme1
document type and nationality: Driving license, Turkey
account addresses: 31f58jUAb5ngvPPv8JyUs1nb8Suko6VVt7EeRooDr3eaSpNGkb
public data attribute: Identity document type : Driver license


Account name 2: Kimlikdeneme2
document type and nationality: National ID Card, Turkey
account addresses: 3Fgs3ZqePhDcp1AEXwBrWbK6EG7aBkPxNS5BmHsyGjYw4jGybx
public data attribute: Identity document type : National ID Card, Turkey

device make and model and OS version: Casper_VIA_G1_Plus - Android 8.1.0

**Comment by jnbn** [comment]
document type: Drive License
nationality: Turkey

addresses:
**iamjnbn** 
Address: 3hYjKPXywBu5Qmms7zCZUU1zNkXCfupJSVpa4FjruZPx58Voyt
document type and nationality: Driving License, Turkey
Firstname: Ugur
Lastname: Aydogdu
DOB: 16.06.88
Issuer: Turkey
ID Valid to: October 2026
Doc Number: 7422


**stash** 
Address: 3aUAJJ53d8ENvwfJgEcn9XRcQ9Vw16qrsWUdYpF5ZmPvjhZvxx
Identity Document Issuer: Turkey

iPhone 11

**Comment by ilhamm24** [comment]
document type: passport, Indonesia
address : 3ZsYx9LcBSiXqtP5qayEUEjtTnsAXwyoCxqy2ZtN5BZsFS7JjX
Nationality: Indonesia
Indentity: Passport
Device : Redmi note 8, Android 9

**Comment by dursunalp** [comment]
Account Address : 2wsLwUEDfMsWSFYHskf8pnLsp3NBcr2atJfs34d7dzmaLmSvni
Identity Document Type: driving license
Country of nationality: Turkey
   First NAME : DURSUN
   İphone  XS İOS 12

**Comment by esmirs** [comment]
addresses:

real-life identity (using the production environment) with a physical identity paper supported for your country
Identity Document Type: NATIONAL ID CARD - TÜRKİYE
'esmir' - Real : 3UATFzjUb5oJHVFPH4qMWjT7FyMheZKDg4eEDLLxNq2ZUaVxMH

Testesmir - Fake1 : 36KY42Ck3QtEHZpMHSSaX8t62qS6dcyHNUrbNRKYW2b7HhQvxy
Testesmir2 Fake2:  3pQiBpQ51a5HAq9gdykVTTZ2vd2oqcQYMP2HPum6qSZfZXqimq

![WhatsApp Image 2020-10-25 at 22 49 17](https://user-images.githubusercontent.com/34422585/97117381-7e426f80-1714-11eb-8f6c-19208a7d1f44.jpeg)
![WhatsApp Image 2020-10-25 at 22 49 17(1)](https://user-images.githubusercontent.com/34422585/97117382-800c3300-1714-11eb-9755-6ea0fe0e9af4.jpeg)
![WhatsApp Image 2020-10-25 at 22 49 17(2)](https://user-images.githubusercontent.com/34422585/97117383-826e8d00-1714-11eb-8928-33180c650ecc.jpeg)
![WhatsApp Image 2020-10-25 at 22 49 17(3)](https://user-images.githubusercontent.com/34422585/97117387-839fba00-1714-11eb-88f8-7e03faa537ed.jpeg)

DEVICE: REDMI NOTE 7 - ANDROID 9

**Comment by byzdndr** [comment]
document type: National ID
nationality: Turkey

Real Address: 2y94yep4tntFva14GdRJBG2J8zvmWppntZL24wc3Pu8dixZQEc
Fake adress1 : 3ZTaui9XUHpDisfcqFo8KsNScWHjP4a3zBFdCYSxA1iR4sHTpZ
Fake adress2: 4oaeumvHGnMCxrVP5vXgopwsHBJhZF9q9SArZXBGYCmXRgGy6m

public data attribute:
Country of nationality: Turkey

Device make and model version:
iPhone 7 iOS 13.7

**Comment by snrdndr** [comment]
document type: Driving Licence
nationality: Turkey

Real Address: 3D2Anp7LQTJP9bTkbyH5tkM1SGVmPAm828SgGnJVm88PiGS7jN
Fake adress1 : 4JiCiUHXzoj3JqezLFRCDREJgRSKMnvYmzCAnMbyyzsy7UDM47
Fake adress2: 4Q7dJr1PfucmdzNyjJebwbk9WkVzz5cTMHGsXoZXHEpP5rXZk7

public data attribute:
Country of nationality: Turkey

Device make and model version:
iPhone 7 iOS 13.7
