### ISSUE TITLE
(ID3) Try to create identities with invalid physical ID documents

### ISSUE THREAD

**Issue by bissembert1618** [Concordium/Testnet3-Challenges#37]
**Mission:**
Try to create an identity object with ID documents that are either expired, modified, not supported by Onfido (see https://onfido.com/supported-documents/) etc.

We are interested both in failed verifications (correct behavior) and in successful verifications (incorrect behavior). **Please also submit the cases, where you managed to get a successful verification with an invalid document or create a bug report, see [Bugs and Improvements](https://github.com/Concordium/Testnet3-Challenges#bugs-and-improvements).** We will collect this information and forward it to the identity issuer Onfido for them to improve their services.

**Submission:** 
- submit information about the document type and nationality
- submit device make and model and OS version
- describe process/experience
- submit screenshot of error message, if applicable

**Comment by andrste** [comment]
Will be more info

**Comment by stguller** [comment]
Turkey,  Vocational ID Card
İphone SE IOS 13
The system accepted 
![IMG_6814](https://user-images.githubusercontent.com/32449978/96095263-12236880-0ed7-11eb-9c39-7efd729c46d0.PNG)
my appeal and processing and than failed.

**Comment by bertco** [comment]
submit information about the document type and nationality
submit device make and model and OS version
describe process/experience
submit screenshot of error message

**Comment by rezeda88** [comment]
submit information about the document type and nationality
submit device make and model and OS version
describe process/experience
submit screenshot of error message

**Comment by EmreNOP** [comment]
submit information about the document type and nationality
Netherlands driver license
submit device make and model and OS version
Huawei P30 Pro / Android 10 (10.1.0.150)
describe process/experience
google search for expired sample driver license
submit screenshot of error message
![photo_2020-10-15_12-48-39](https://user-images.githubusercontent.com/72916436/96113729-e313f380-0ee4-11eb-97f3-2b34f42bc555.jpg)

**Comment by mahofmahof** [comment]
submit information about the document type and nationality
driving licens/turkey
submit device make and model and OS version
samsung s7 edge/ android 8.0.0
describe process/experience
found the picture of a driving license from internet

submit screenshot of error message
![photo_2020-10-15_14-06-01](https://user-images.githubusercontent.com/35915995/96115514-bca78580-0eef-11eb-8388-c4bf60520a7a.jpg)

**Comment by hknnr** [comment]
node ıd : dbd207ceb4bfdbc4

**Comment by gokmenkutuk** [comment]
Passport- Turkey
Xiaomi Redmi Note 8 Pro - Android 10
Verification failed.
![IMG_20201015_154356](https://user-images.githubusercontent.com/38683203/96128015-72c59c00-0efd-11eb-93b0-d7f2bd40e2a8.jpg)

**Comment by gulayse142** [comment]
Passport- Turkey
Samsung S9 SM-G95OU1
node ıd:  c575960f33c93f07
Verification failed.

**Comment by boss95rnd** [comment]
Driver Licence: USA 
Iphone xs max; IOS 13,7
Took a driver licence from google search. It took much longer as previous verifications. After half an hour, verification was rejected.
![1](https://user-images.githubusercontent.com/72925068/96138709-58d88900-0efe-11eb-9926-96eea22c5904.jpg)

![2](https://user-images.githubusercontent.com/72925068/96138744-6130c400-0efe-11eb-8201-35c6f8ccce86.jpg)

**Comment by liray-unendlich** [comment]
- Document type: Passport
- Nationality: Japan
- device: iPhoneXs, iOS 14.0.1
- process: I use fake passport picture, fake selfie. onfido said "Verification in Progress...." for 10mins. 
                Then the pictures are denied for verification.
                The verification process seemed to be smooth.
![S__65052674](https://user-images.githubusercontent.com/15893314/96141995-87755480-0f3c-11eb-97cb-28c9ec374f3b.jpg)

**Comment by hankoc** [comment]
Document type: Expired ID Card

Nationality: Turkey

Device: iPhone XR, iOS 14.0.1

Process: I used an expired ID & chose driver's license to see If I can trick the system, authentic selfie.
 "Verification in Progress...." for 6 mins.
Identity was accepted after approx. 10 mins

**Comment by Vladislav1z** [comment]
Document type: Passport
Nationality: Russia
Device: iPhone 7 plus, iOS 14.0.1
Process: expired passport, was rejected after 5 minutes of verification. "Failed to create"
![IMG_4296](https://user-images.githubusercontent.com/72387556/96159115-f347c500-0f1c-11eb-95fb-a16643211fe7.jpg)

**Comment by Irina0880** [comment]
Document type: Passport
Nationality: Russia
Device: Apple iPad (6), iOS 13.5.1
Process: expired passport, was rejected after 8 minutes of verification. "Failed to create"
![IMG_0235](https://user-images.githubusercontent.com/72391928/96161206-a74a4f80-0f1f-11eb-8983-0b583cf014e2.jpg)

**Comment by kriegzeist** [comment]
Document type : Passport

Nationality : Turkey 

Device make and model and OS version: iPhone 6s; iOS 13.7

Describe process/experience : I tried with expired old passport and it was not approved

Error message : Verification failed 
![IMG_1424](https://user-images.githubusercontent.com/64436866/96165846-dcf23700-0f25-11eb-9a6e-994d86ae2e95.PNG)

**Comment by enginsev** [comment]
Id: a09dd314839cb8e9
Document type : Passport
Nationality : Turkey
Samsung J7 - Android 9

The pre-wait took quite a long time. (4-6 min)
control time was pretty fast (1-2 min)

![image](https://user-images.githubusercontent.com/6599823/96182722-8a714480-0f3e-11eb-97a5-403e3de6aca7.png)
![image](https://user-images.githubusercontent.com/6599823/96182760-952bd980-0f3e-11eb-88ab-d6b3eb704cef.png)

**Comment by thearsiv** [comment]
Id: 301fe5a8f530255e
Turkey / Passport
Android j7 - Android9

They checked the scanned documents in a very short time and returned them.

**Comment by edandrada** [comment]
submit information about the document type and nationality: residence permit turkey 
submit device make and model and OS version:  model sm-g6100 Android Version 8
describe process/experience : notabene is a good service for kyc. system is fast and reliable. it takes only 2 min to upload files and take result
submit screenshot of error message
![Screenshot_20201015-234117_Concordium ID](https://user-images.githubusercontent.com/55541037/96183802-20599f00-0f40-11eb-92db-055e6146fa80.jpg)

**Comment by TO-BOwan** [comment]
the document type and nationality: driving license , UKGB
device make and model and OS version: Apple iphone 6S plus, ios 14.0.1 
I have submitted a birtish dirviing license sample and verification failed  
![IMG_1839](https://user-images.githubusercontent.com/72916996/96184244-e0df8280-0f40-11eb-9589-9cab1d99f5ac.jpg)

**Comment by zybk70** [comment]
document type: Personnel ID card and nationality:Turkey
iPhone XS ios:14.0.1
describe process: I used an ID card without submitted identifiers. Experiences: 
I did not scale it right and did not pay attention to the lighting. Results: Cut-off image detected and blurry photo detected.
Moreover,I used Turkish National ID card although submitted as Portugal. Result:Verification failed
![image](https://user-images.githubusercontent.com/54598911/96183999-7d555500-0f40-11eb-821b-d91e767f003c.png)
![image](https://user-images.githubusercontent.com/54598911/96184075-9a8a2380-0f40-11eb-9162-2644518e5cde.png)
![image](https://user-images.githubusercontent.com/54598911/96184506-3fa4fc00-0f41-11eb-98ed-cf255ef7974c.png)

**Comment by kryatsvn** [comment]
![sahte](https://user-images.githubusercontent.com/47062169/96186981-e63ecc00-0f44-11eb-8cd4-bfd6fed39db2.jpg)
Document type: Passport
Nationality: Turkey
Device: Samsung A7 Android 8.0
Process: expired passport, was rejected after 8-9 minutes of verification. "Failed to create"

**Comment by nghnng** [comment]
![invalidpassport](https://user-images.githubusercontent.com/72946735/96187309-73822080-0f45-11eb-86f8-0652c5322699.jpg)

Document type: Passport
Nationality: Turkey
Device: I Phone 8 , IOS 14.0.1
Process: expired passport, was rejected after 10 minutes of verification. "Verification Failed"

**Comment by Ebruberen** [comment]
Passport/ Türkiye 
İphone 7 iOS 14.0.1
![769B87B3-6ED5-41B7-A805-B8CAEEBA4FE4](https://user-images.githubusercontent.com/72947146/96188831-1471db00-0f48-11eb-85e0-a2bafe5dea62.jpeg)

**Comment by Rookie23** [comment]
Document type: Passport

Nationality: Bulgaria

Device: iPhone 7, iOS 14.0.1
![image](https://user-images.githubusercontent.com/36521585/96191051-fefeb000-0f4b-11eb-8698-0f945f25c951.jpeg)

**Comment by BreenLine** [comment]
I used a Transportation Card as a Driver Licence & Turkey

Samsung A71, Android 10

I think this system works well, It rejected my card and warned me. 

![error](https://user-images.githubusercontent.com/16193634/96195367-45a4d800-0f55-11eb-84b9-2fd2311db58a.jpeg)

**Comment by tahacon** [comment]
passport - Finland
verification failed.
Device iPhone7 iOS 13.7
![IMG_4032](https://user-images.githubusercontent.com/72972420/96248351-1c676480-0fb4-11eb-83ab-92fc04190b2d.PNG)

**Comment by xaochuk** [comment]
Document type: Passport
Nationality: Portugal

Device: iPhone 8, iOS 14.0.1

Describe process: After 8 try, system accept passport photo(photo taken from monitor) from internet.

Screenshots:
![1](https://user-images.githubusercontent.com/48527184/96250598-639f2680-0faf-11eb-951f-6b200513cfe3.jpg)
![2](https://user-images.githubusercontent.com/48527184/96250607-6568ea00-0faf-11eb-9b7a-b713d14d3065.jpg)
![3](https://user-images.githubusercontent.com/48527184/96250611-6732ad80-0faf-11eb-8c2d-b190a87ec274.jpg)

**Comment by MehmetAliATLI** [comment]
Document type: Driver's License
Nationality: United Kingdom
device: iPhone11, iOS 14.0.1

Process: I used fake driver ID and fake selfie. Onfido said the verification continues for about 5 minutes.
Later driver ID and selfie were denied.

![test - identy](https://user-images.githubusercontent.com/4720414/96259724-b0dac280-0fc6-11eb-9f7c-48017dce7243.jpeg)

The verification process got full marks from me.

**Comment by TravelerAnu** [comment]
Document type : Driving License
Nationality : Turkey
Device : Samsung S8+ Android 9.0

Process : Being created identity from any invalid card instead of driving license, 2 different fake card used and toook photos of them. and put correct selfie. Proceesed nearly 4 minutes. Then;

![image](https://user-images.githubusercontent.com/59296825/96261803-935b2800-0fc9-11eb-9968-a7b03cef367f.png)

**Comment by Erdincgumus** [comment]
![2hatalı kyc](https://user-images.githubusercontent.com/52371559/96271177-3cf3e680-0fd5-11eb-97cf-db8815413203.jpg)
Document type: Driver's License
Nationality: Turkey
device:Samsung Galaxy S10 android10
Process: I used fake driver ID and fake selfie.

**Comment by omertfn** [comment]
ID: Turkey
iphone 7 plus /ios 14.01
node ıd: b17c5a0ccdff1ead
Verification failed


![IMG_7672](https://user-images.githubusercontent.com/32371976/96275449-6a8f5e80-0fda-11eb-9df2-1035d5f2dcf6.jpg)

**Comment by yusuftrl** [comment]
Driver Licence(bus card)
Nationality : Turkey
Xiaomi Redmi Note 9s Android 10
Node ID: 4ab86817b5259bf2
I tried to introduce the bus card as a driver's license. Verification failed
![WhatsApp Image 2020-10-16 at 15 16 24](https://user-images.githubusercontent.com/71350404/96281005-66b30a80-0fe1-11eb-9df2-ba6034b8ff7d.jpeg)

**Comment by yusuftrl** [comment]
Document type: Driver's License (bus card)
Nationality: Turkey
Xiaomi Redmi Note 9s
I introduced my bus card as a driver's license. He did not accept.
![WhatsApp Image 2020-10-16 at 15 16 24](https://user-images.githubusercontent.com/71350404/96283456-ea222b00-0fe4-11eb-93cd-d58173d33455.jpeg)

**Comment by mkaravelioglu** [comment]
* submit information about the document type and nationality : driver license, turkey
* submit device make and model and OS version : Iphone x, ios 14.0.1
* describe process/experience : I tried to verificate with student id instead of driver license but it was rejected after 10 minutes.
![IMG_3124](https://user-images.githubusercontent.com/72934474/96284462-45a0e880-0fe6-11eb-804d-507202d2acee.PNG)

**Comment by Supernode-s** [comment]
Document type: Passport
Nationality: Russia
Device: iPhone SE, iOS 14.0.1
Process: expired passport, was rejected after 3 minutes of verification. "Failed to create"
![PHOTO-2020-10-16-17-24-04](https://user-images.githubusercontent.com/72660226/96296202-8f45ff00-0ff7-11eb-902e-c16e927baa48.jpg)

**Comment by semihetci** [comment]
information about the document type and nationality
Passport - Turkey

device make and model and OS version
iPhone 6s Plus iOS 14.0.1

describe process/experience
Upload a scribbled passport photo and any portrait photo from web search. Verificaiton failed after 1-2 minutes.

screenshot of error message
![WhatsApp Image 2020-10-16 at 22 19 07](https://user-images.githubusercontent.com/72987336/96300822-e4d1da00-0ffe-11eb-97a3-c6be101a2d95.jpeg)

**Comment by berkesim** [comment]
Driving Licence, Turkey
iPhone 11, iOS 14.0.1
Old dated driving licence
![IMG_4327 2](https://user-images.githubusercontent.com/72994675/96301513-fb2c6580-0fff-11eb-9cd2-171554b28af5.PNG)

**Comment by darko313** [comment]
information about the document type and nationality
Passport - Turkey

device make and model and OS version
iPhone 7 iOS 13.6

describe process/experience
Upload an expired passport photo and upload selfie of me. Verificaiton failed in 3-5 minutes.

![WhatsApp Image 2020-10-16 at 23 21 29](https://user-images.githubusercontent.com/72935893/96305644-e30c1480-1006-11eb-9772-666d02d1b848.jpeg)

**Comment by BeytullahEVLENDI** [comment]
Driving Licence / TURKEY
GL G6 - Android 9
NB system works very well
![1](https://user-images.githubusercontent.com/17639707/96305967-6b8ab500-1007-11eb-94dc-1b24d81ddb80.png)
![2](https://user-images.githubusercontent.com/17639707/96305972-6e85a580-1007-11eb-9dc3-86f30ac09b6a.png)

**Comment by adali125** [comment]
Document type: passport
Nationality: Turkey
device:General mobile Gm8 android 9
Process: fake passport
 ID and fake selfie.

![c47b5e7c-46ac-4474-9c75-c6fbdb7b0eda](https://user-images.githubusercontent.com/35936707/96331594-357d1d80-1067-11eb-87ee-55ffee0c9f91.jpg)

**Comment by ftosun** [comment]
Document type : Passport

Nationality : Turkey

Device make and model and OS version: iPhone 6s; iOS 13.7

Describe process/experience : I tried with expired old passport and it was not approved

Error message : Verification failed
![IMG_B981B99D1B97-1](https://user-images.githubusercontent.com/51463702/96336130-1346c800-1086-11eb-8234-44c7f55a9c45.jpeg)

**Comment by coreman000** [comment]
submit information about the document type and nationality: 
Passport, Russia
submit device make and model and OS version
Samsung A50, Android10
describe process/experience 
I took my wife's passport, INVALID due to LAST NAME changed (marriage),
passport has a valid expiration date, but it has a part cutted off: 
![IMAGE 2020-10-17 18:56:30](https://user-images.githubusercontent.com/14929454/96347446-7a767380-10aa-11eb-8a26-3c3fc225658b.jpg)
![IMAGE 2020-10-17 18:56:49](https://user-images.githubusercontent.com/14929454/96347455-84987200-10aa-11eb-9c21-335a4fc9f00b.jpg)

I tried another old passport (mine, I corrected the expiry date with a pen). App asked me to remake the photo due to blur, and after dropped the identification:
submit screenshot of error message
![IMAGE 2020-10-17 19:05:00](https://user-images.githubusercontent.com/14929454/96347633-a9411980-10ab-11eb-93b7-e5c3bbe200bd.jpg)

**Comment by Kkemosabe** [comment]
Document type : Passport
Nationality : Ukraine
This is old passport and after few minutes its "Failed to create"

![96141995-87755480-0f3c-11eb-97cb-28c9ec374f3b](https://user-images.githubusercontent.com/48792235/96364676-75660280-1144-11eb-9211-50f1abca5c52.jpg)

**Comment by trmetan** [comment]
I wanted to issue a license document named "Zam"
For this, I used my workplace entrance card and selected Tunisia as nationality.
I chose a driver's license
Document not approved

Huawei mate 10 pro android 10.00
![Screenshot_20201018_153429_com concordium wallet](https://user-images.githubusercontent.com/67740304/96367872-0d6de700-1159-11eb-81c9-f57cce727e45.jpg)

**Comment by insomnium7** [comment]
Document type : Passport

Nationality : Turkey

Device make and model and OS version: OnePlus; Android v.10
Describe process/experience : I tried with expired old passport and it was not approved and fake selfie.

Error message : Verification failed

![WhatsApp Image 2020-10-19 at 19 43 08](https://user-images.githubusercontent.com/3042763/96481332-1091d180-1244-11eb-8f82-ddd12961b1d0.jpeg)

**Comment by erknfe** [comment]
Document type: Driver License
Nationality: Turkey
Iphone 7 - IOS 14.0.1
Describe process/experience: I tried with student ID

![1C2447A0-10E2-44ED-943E-5F453C17D2DD](https://user-images.githubusercontent.com/7534459/96499681-65d6de80-1256-11eb-84e0-ae156a50263f.png)

**Comment by h02051995** [comment]
Document type: ID National Card
Nationality: Viet Nam
device: Sam Sung A70
Process: use other people's information and take pictures of 
ID and fake selfie.

**Comment by htkubrat** [comment]
Document type: Driver License
Nationality: Turkey
Iphone 6s - IOS 14.0.1
Describe process/experience: I tried with a student id

![1c9bcd2b-9842-4eac-a595-a379ddb7aacd](https://user-images.githubusercontent.com/73245338/96750389-8e84e280-13d4-11eb-8484-712f858685e7.jpg)

**Comment by SymphonyQntm** [comment]
Document type: Driver License
Nationality: Turkey
Huawei P Smart - Android 9
Describe process/experience: I tried with student ID
![failed](https://user-images.githubusercontent.com/73124965/96756561-e7587900-13dc-11eb-8741-de89145c74b9.jpg)

**Comment by huseyinfe** [comment]
Driver Licence : Turkey

Device: Huawei p20 lite - Android 9

Verification failed
Took a driver licence from google search. It took much longer as previous verifications. After 5 minute, verification was rejected.

![errorLicence](https://user-images.githubusercontent.com/44346471/96829988-4b158d00-1443-11eb-892d-edc69b6914c9.jpeg)

**Comment by kubrafe** [comment]
Driver Licence : Turkey

Device: Huawei p20 pro - Android 10

Verification failed
Took a driver licence from google search. It took much longer as previous verifications. After 15 minute, verification was rejected.


![errorDriverLicemce](https://user-images.githubusercontent.com/73237024/96830118-8f089200-1443-11eb-87de-e5013a2c603e.jpeg)

**Comment by mertcan1007** [comment]
Driver's license: Turkey
xiaomi redmi note 8 android 9
I used an old student ID of mine but not accepted. Verification failed.
NODE Id: 42b4486e8b1aa5ab
![Screenshot_2020-10-23-04-14-28-094_com concordium wallet](https://user-images.githubusercontent.com/73318986/96946332-b9605b00-14e8-11eb-8c35-6c7ac37c736b.jpg)

**Comment by donadel01** [comment]
Document type: identy 
Nationality: Turkey
Reeder p13 blue  - Android 9
Describe process/experience: A different person was recorded by taking a selfie with a random ID on google.

![A0DCA5E1-0D28-4B0E-B61A-9B9C18A3316A](https://user-images.githubusercontent.com/73251385/97003239-d2e2c080-1543-11eb-8743-72f408bfeb86.jpeg)

**Comment by edrolu87** [comment]
submit information about the document type and nationality: Turkey, Passport
submit device make and model and OS version: Samsung, Galaxy S8 SM-G950F, Android 9.0
describe process/experience: I wanted to authenticate using a passport. However, I sent photos of my workplace identity document. As a result, authentication was not approved by the system.
![Failed KYC](https://user-images.githubusercontent.com/73315597/97011522-72598080-154f-11eb-991b-c9602564c104.jpg)

**Comment by edrolu87** [comment]
submit information about the document type and nationality: Turkey, Passport
submit device make and model and OS version: Samsung, Galaxy S8 SM-G950F, Android 9.0
describe process/experience: I wanted to authenticate using a passport. However, I sent photos of my workplace identity document. As a result, authentication was not approved by the system.

Node id:bd35a764b4caa77f
Account Adress: 34NxoctkrShnCWgLeEp25stva9VGwEkPNupqZuVqBUY87FCAaJ
![Failed KYC](https://user-images.githubusercontent.com/73315597/97012050-1f33fd80-1550-11eb-828b-356984b003db.jpg)

**Comment by hakkinen85** [comment]
Driver Licence: United Kingdom
Apple Iphone xr  IOS 14.1
Node Id: ad5432e806735cba
Baker id:898
Took a driver licence from google search. I entered a different driver's license picture.. After 5 minutes, verification was failed.
![WhatsApp Image 2020-10-23 at 20 52 25](https://user-images.githubusercontent.com/73037251/97038583-b5c5e600-1573-11eb-8451-72ce57f3b573.jpeg)

**Comment by burkay5** [comment]
Document type: National ID Card
Nationality: Turkey
Device make and model and OS version: Casper_VIA_G1_Plus - Android 8.1.0
Describe process/experience: Because I was taking a selfie in an environment where there was very little light, he couldn't compare it to the photo on the  National ID Card and made a mistake
![photo5807596993617441527](https://user-images.githubusercontent.com/43247689/97043864-d09c5880-157b-11eb-94a5-d37b997b9424.jpg)

**Comment by ilhamm24** [comment]
Passport Malaysia
Device : Redmi note 8, Android 9
Status : success, not rejected

**Comment by dursunalp** [comment]
Document type : driving license
Nationality : Turkey

Device make and model and OS version: İphone XS İOS 12
Describe process/experience : I tried with expired old passport and it was not approved and fake selfie.

Error message : Verification failed

![96364676-75660280-1144-11eb-9211-50f1abca5c52](https://user-images.githubusercontent.com/73360909/97092814-b2079180-164f-11eb-9f03-38ae07a1527a.jpg)

**Comment by esmirs** [comment]
submit information about the document type and nationality
DOCUMANT TYPE IS AMERICAN EXPRESS CREDIT CARD NATIONALITY CANADA

    submit device make and model and OS version
DEVICE: REDMI NOTE 7 - ANDROID 9

    describe process/experience
I tried to continue with an invalid document ( AMERICAN EXPRESS CREDIT CARD) and encountered an error message

    submit screenshot of error message, if applicable

![WhatsApp Image 2020-10-25 at 23 24 51](https://user-images.githubusercontent.com/34422585/97118125-530e4f00-1719-11eb-8c52-f6b6707a3ea0.jpeg)
