### ISSUE TITLE
sonerbo

### ISSUE THREAD

**Issue by sonerbo** [Concordium/Testnet3-Challenges#404]
4AsdEaWG5ftyFCEDSuq7PvePc8bzC7QVLbuVXqdGVZ156fVDRz

Xiaomi Note 6 Pro Android

**Comment by concordium-admin** [comment]
Hi sonerbo, please do not create issues for your submission but follow our [submission guidelines](https://github.com/Concordium/Testnet3-Challenges#submission-process) instead. This submission here will not be considered. Thx.
