### ISSUE TITLE
GRPC

### ISSUE THREAD

**Issue by ZaferGraph** [Concordium/Testnet3-Challenges#427]
When I restart the node on the Ubuntu 20.04.1, repeating this:

```
2020-10-16T23:11:07.915153265Z: ERROR: TreeState: Database invariant violation: Could not read last finalized block
2020-10-16 23:11:07,916 INFO success: p2p-client entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-16T23:11:07.917293130Z: ERROR: External: Database invariant violation: Could not read last finalized block
Error: ErrorMessage { msg: "Database invariant violation. See logs for details." }
```

On the client side shows:
**Oops, something went wrong: Unexpected HTTP response: 400: "Cannot establish connection to GRPC endpoint."**

**Comment by ZaferGraph** [comment]
I think it was sync issue, I had to flush the node then fixed.

**Comment by concordium-admin** [comment]
Hi ZaferGraph, 

if the node shut down gracefully, then this (probably) does not happen. So the circumstances in which the node shut down would be useful.

The only current workaround is flushing the database, as you did. 

Next time please upload the database together with the issue, or if it exceeds the size limit, please use testnet@concordium.com to send it to us. We would also be interested in the logs of the previous run.

We are currently looking into the issue.

**Comment by ZaferGraph** [comment]
FYI after a while when I said fixed, it was't actually, tried many times flushed periods but not fixed, I'm very sorry I destroyed the server without take the log.

**Comment by ZaferGraph** [comment]
I guess happent same on the new server, let the open issue, I may send the log soon.

**Comment by ab-concordium** [comment]
Are these failures happening on the same server as the one in #684 ? 

If the node is killed due to an out of memory problem than that is more likely to lead to a database corruption.

**Comment by ZaferGraph** [comment]
> 
> 
> Are these failures happening on the same server as the one in #684 ?
> 
> If the node is killed due to an out of memory problem than that is more likely to lead to a database corruption.

I guess so.
