### ISSUE TITLE
Buggy Alert on Baking

### ISSUE THREAD

**Issue by ZaferGraph** [Concordium/Testnet3-Challenges#478]
When I start another baking after stopped one, this below message has came on the client, pass is correct, but still baking started even though the alert.

Baker ID is 839

**Oops, something went wrong: Unexpected HTTP response: 401: "cannot decrypt signing key with index 0: decryption failure: wrong password"**

![resim](https://user-images.githubusercontent.com/9367891/96335532-f9a38180-1081-11eb-9754-afd92c59ad13.png)

**Comment by concordium-admin** [comment]
Yes, if you submit the wrong password, then submit the right password, you might still see the error message for a while.
