### ISSUE TITLE
Identity issuer up again

### ISSUE THREAD

**Issue by concordium-admin** [Concordium/Testnet3-Challenges#644]
Our identity issuer Notabene is down since 2020-10-18 before 20:00. That means that no new identities can be issued at the moment, neither with "Notabene" nor "Notabene development", and challenges (ID1) - (ID3) cannot be completed.

We have notified Notabene on several channels but haven’t heard back so far. We will communicate out, as soon as we hear back from them.

**Comment by concordium-admin** [comment]
Notabene is up again. New identities can be issued.

**Comment by supermario** [comment]
Update moved to the [status page](https://github.com/Concordium/Testnet3-Challenges/blob/main/status.md).
