### ISSUE TITLE
Node Reseted

### ISSUE THREAD

**Issue by ZaferGraph** [Concordium/Testnet3-Challenges#684]
Hello,
My B1 server has stopped today after 3 days later. This is what I seen

![resim](https://user-images.githubusercontent.com/9367891/96512408-1cdc5580-1269-11eb-86bf-ebee351b1ac7.png)

As you see there is no any error, I checked the kern.log there is no any too:

(I sent you the file)

Then I tried to concordium-node-retrieve-logs but it gave me empty log file as you see:

![resim](https://user-images.githubusercontent.com/9367891/96512685-85c3cd80-1269-11eb-9aae-4aef5250b3a9.png)

I tried to take log to times but same:

![resim](https://user-images.githubusercontent.com/9367891/96512716-95dbad00-1269-11eb-9704-8ec97568b670.png)

After all, I restarted the node for see what block it stopped, but what I see:

![resim](https://user-images.githubusercontent.com/9367891/96512830-c0c60100-1269-11eb-8f1d-3be2b442e8f4.png)

Node has totally reseted

I'm sorry can't give you log because it's empty.

But I'll send you (testnet@concordium.com) kern.log if you want to see.

**Comment by concordium-admin** [comment]
Thanks for the detailed info. I have received your log. We will look into it.

**Comment by ab-concordium** [comment]
Can you provide a bit more description of your system?

One thing that might be relevant is if you run `docker container list` and post the output of that. It might tell us what happened to the node and why the logs are not accessible.

**Comment by ZaferGraph** [comment]
![resim](https://user-images.githubusercontent.com/9367891/96597789-e77e4900-12f6-11eb-8a3f-ea61782c1fd7.png)

![resim](https://user-images.githubusercontent.com/9367891/96597934-07157180-12f7-11eb-875b-4cd3f764a7df.png)

![resim](https://user-images.githubusercontent.com/9367891/96597964-0d0b5280-12f7-11eb-8914-8838556cd74e.png)

**Comment by ZaferGraph** [comment]
I can pm ip and pass if you want, I'm thinking destroy already, no problem.

**Comment by ab-concordium** [comment]
Interesting. Based on the limited allocated RAM I suspect that your node got killed due to trying to allocate more than 512MB.

Is 3 days ago also when you started the node the first time? Can you run `docker logs 24e96815a720`?

**Comment by ZaferGraph** [comment]
Yes I can run, here: https://paste.ubuntu.com/p/MtQZKj4Tn3/

Yeah there it is, probably cache ram not enough because when I checked ram and disk after kill there both under usage. Yes the system is not enough but this reaction should't be like this, at least node stay stopped not purged.

Also my B2 killed same reason I think, same system spec. I just missed one step, this one happent both when I run the start command.

![resim](https://user-images.githubusercontent.com/9367891/96701395-3977ab00-1399-11eb-9d59-b489ff70c6fa.png)


I just started with a new server and node with these spec yesterday, let's see what's going on

![resim](https://user-images.githubusercontent.com/9367891/96703496-94120680-139b-11eb-9020-0a7a2b56fcac.png)

**Comment by ab-concordium** [comment]
Those specs should be sufficient now.

From the logs you just attached it looks like the cause of failure was actually lack of disk space, which led to partial database corruption, and thus your node could not restart. I can't see precisely what happened to the container you were running, but seeing that docker containers have some space overhead, it is likely that either it was partially corrupt, or deleted.

**Comment by iekmuby** [comment]
@ZaferGraph what is your zone in Vultr for this nodes? Silicon Valley?

**Comment by ZaferGraph** [comment]
> 
> 
> @ZaferGraph what is your zone in Vultr for this nodes? Silicon Valley?

It was NY, currently I'm in Netherland

**Comment by iekmuby** [comment]
Silicon Valley area is very unstable. One of my nodes was stopped and erased, so I lost all of my logs. I suppose this may happened with NY too. By the way, Amsterdam has one incident too, since I'm use it in Concordium.
