### ISSUE TITLE
Concordium Node Dashboard missing http cache control header

### ISSUE THREAD

**Issue by EmreNOP** [Concordium/Testnet3-Challenges#693]
Node Dashboard html page does not have required cache control parameter and due to lack of that parameter, browser showing cached content. at least below headers should be included.

    <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
    <META HTTP-EQUIV="Expires" CONTENT="-1">

view-source:http://localhost:8099/

**Comment by namekutuk** [comment]
I agree with Emre, due  the caching at some time, it takes too long to browse the page.

**Comment by supermario** [comment]
@EmreNOP I don't think the cached HTML should be an issue. Are you suggesting that something else is being cached that shouldn't be and thus causing problems? What problems are you seeing?

@namekutuk your comment seems to suggest the opposite, that caching is making it worse...? Can you also be clearer on what issue you're seeing?

**Comment by EmreNOP** [comment]
my recommendation is not just about cached html. so might be js, css etc. whatever in use. 
We talked a lot on the discord and tons of people noticed that, if you not open dashboard in incognito mode, dashboard showing old content about baking, (waiting time, join delegation queue button etc)

i have two example for instance. 
first one, 4 days a go, i joined stake delegation queue. (In Testnet stake delegation queue, waiting time 46h1m.) and after around 50mins, i noticed that "Testnet stake delegation pending, will become active in 1h31m" 

but it was already active and ive had joined queue. There was also some kind of inconstancy on the dashboard but i dont have ss for them. 

![photo_2020-10-16_10-38-17](https://user-images.githubusercontent.com/72916436/96607358-93746400-12f8-11eb-9abc-e1be939e66a2.jpg)
![2020-10-16_11-29](https://user-images.githubusercontent.com/72916436/96607397-9cfdcc00-12f8-11eb-86ae-42fc81975b92.png)

**Comment by supermario** [comment]
Okay, thanks for the detail. I don't think this has anything to do with asset caching, but will take a look.

**Comment by concordium-admin** [comment]
@EmreNOP, from your elaboration, it sounds like you experienced another instance of the browser's local storage status failing to automatically update. 

Please try to clear the local storage manually, by using the following keys while being on the node dashboard:
Windows/Linux: ctrl + delete
MacOS: ctrl + fn + backspace 
Once pressed, you will be prompted to confirm the action. You can also delete the entries in the browser's local storage manually and immediately refresh the webpage before it re-inserts the entries again.

There is a more detailed description and workarounds under [troubleshooting](https://developers.concordium.com/testnet/docs/troubleshooting#node-dashboard-shows-outdated-information-after-node-reset).

**Comment by EmreNOP** [comment]
im using brave on linux workstation. technically, im clearing all cached contents (cookie,js, images like static contents) at every restart of browser.(this is my default settings). how ever, if i notice again in same browser session, i'll try. 

but i guess ctrl+delete is useless in brave or chromium. could it be ctrl+f5 ?

Emre

**Comment by EmreNOP** [comment]
Here is the additional findings for this. 

I switched my ssh port mapping one node to another node. in first screenshot, my secondary node is looking like have assinged baker but its not. second ss from incognito brave session. everything is normal as expected. 

then i close my tab and open again with normal browser session. output was still same. new node, and other node baking output.
then i completely closed my browser (main one) and than everything is looking ok. im  not sure this is related with my clear cache settings but anyway. you can produce same thing from here that i believe.


![2020-10-21_13-11](https://user-images.githubusercontent.com/72916436/96712887-169cc500-13a0-11eb-944f-cf6bc193217f.png)
![2020-10-21_13-11_1](https://user-images.githubusercontent.com/72916436/96712897-18ff1f00-13a0-11eb-84bf-639246f4d788.png)

**Comment by supermario** [comment]
@EmreNOP it sounds like while you let a lot of stuff clear out, maybe your LocalStorage is still being retained (and only cleared for some reason when you close Brave completely).

If you see this again, please do try the steps from [troubleshooting](https://developers.concordium.com/testnet/docs/troubleshooting#node-dashboard-shows-outdated-information-after-node-reset) to clear LocalStorage specifically. Simply refreshing the tab after that should work to "unstick" things.

**Comment by concordium-admin** [comment]
Node dashboard to be reworked in future.
