### ISSUE TITLE
Memory allocation(core dumped) error while "retrieve-logs" command running 

### ISSUE THREAD

**Issue by greyheaven** [Concordium/Testnet3-Challenges#731]
I have 2 nodes running. One has been running for 4 days and the other one is 6. Today I run _**retrieve-logs**_ command on both of them and I realized something. Even though I run both of these nodes on devices with same features(4GB RAM, 80 GB disk), one log file was created successfully but I got memory allocation error on the other one. I wondered why this happened. Then I run commands again and watched RAM, disk and GPU usage graphics on both devices. After this, I found out how this **_retrieve-logs_** command works. Thus, I figured out why I got .log file successfully on one but I got this **_memory allocation/core dumped_** error on the other one. 
When **retrieve-logs** command is run, writing process starts and this process uses memory on RAM. All data is kept on RAM. After the whole writing/streaming  process completed, this log file that have been kept on RAM will be written and saved on disk and removed from RAM. This means when **_retrieve-logs_** command is run, if size of the .log file will be smaller than your device's free memory/RAM, .log file will be created and written successfully on disk. However if size of the log file will be larger than free RAM memory, RAM usage will increasingly go on and eventually RAM usage will be %100 and we will get memory allocation/core dumped error and .log file will not be saved successfully. **_retrieve-logs_** command will fail.

In my case, while size of my 4 days old node's log file is 2GB yet, it was approximately 3GB for 6 days old node(I can't say an exact size as I couldn't get the log file). When I run log command on both nodes, I could get my 2GB log file because it didn't exceed my free RAM space. However I couln't get the other one because of this RAM issue. Let's imagine I have 8GB RAM on my devices, I would have gotten both of these log files. But for example I have been running a node for 30 days(for B1 mission), I would have a log file sized around 20 GB. In this case, even 16 GB RAM wouldn't be enough to get the log file. Or let's think on macro sizes, how much free RAM space would we need to get the log file of a 6 months old node?

https://developers.concordium.com/testnet/docs/downloads In this official documantaion page,
 we have been told that 4 GB of RAM is enough on linux system. 
This is why I run these node on 4GB RAM. However with this current **_retrieve-logs_** command, 
I can't even get the log file of a 4 days node. 

I think this is a problem/bug need to be fixed.
 A problem that other people will face day by day when their log files' sizes will grow.

I think this can be fixed with the method I suggest below.
RAM usage should be checked while retrieving and stream processes should
 continue directly on disk when the memory is full. 
**_"Copying MemoryStream to FileStream"_** method should be applied.

**Comment by supermario** [comment]
Thanks for the detailed issue report @greyheaven! We're looking into this along with a solution for all the challenges requiring log file submission 👍 will close this issue with details when we've got a resolution.

**Comment by concordium-admin** [comment]
Log issues resolved; for more info, see https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md
