### ISSUE TITLE
concordium-client account import error

### ISSUE THREAD

**Issue by EmreNOP** [Concordium/Testnet3-Challenges#758]
After the solving the issue #692, my concordium-client elf is working but now i have another problem on same node. 
that might be related with #692 

i tried either with user or root account but output is still same. 
i also copied export.concordiumwallet file inside of container to /root directory. but return didnt changed at all.

xx@xx:~/Documents/concordium-software$ ./concordium-client -v config account import export.concordiumwallet
Base configuration:
- Verbose:            yes
- Account config dir: /var/lib/concordium/config/accounts
- Account name map:   none

Error: The given file 'export.concordiumwallet' does not exist.
xx@xx:~/Documents/concordium-software$ ls -la export.concordiumwallet 
-rwxrwxrwx 1 xxa xxa 277811 Oct 21 11:33 export.concordiumwallet

**Comment by concordium-js** [comment]
I was just able to complete the flow you mentioned without any problems as you can see by this log:
```
❯ cp ~/Downloads/export.concordiumwallet ./
❯ ./concordium-client config account import export.concordiumwallet
.... (it worked fine)
❯ docker exec -it  concordium-client ls /home/docker/concordium-client
concordium-client	       concordium-node-retrieve-logs-new
concordium-node		       concordium-node-stop
concordium-node-reset-data     export.concordiumwallet
concordium-node-retrieve-logs  third-party-licenses.html
```

Note that the path `~/Documents/concordium-software` is mapped inside the container to `/home/docker/concordium-client` which is the directory from which the `concordium-client` is invoked. Therefore, once you copy the file into your `~/Documents/concordium-software` folder, running the above docker command should show that the file is indeed in that directory.

The path provided to the `concordium-client` is the path *inside* the container, which means that for example if I move the file outside of `concordium-software` (therefore removing it from inside the container), it cannot find it:
```
❯ mv export.concordiumwallet ../
❯ ./concordium-client -v config account import ../export.concordiumwallet
Base configuration:
- Verbose:            yes
- Account config dir: /var/lib/concordium/config/accounts
- Account name map:
                ....

Error: The given file '../export.concordiumwallet' does not exist.
```

So in your case what I would do is check that the file is copied inside the docker container properly by listing the files in `/home/docker/concordium-client` inside the container. If not, as a hacky workaround you could manually `docker cp` the file into that directory.

I suspect you might be running the node with one user and calling the concordium client with another one, so the dir `/home/<user1>/Documents/concordium-software` is mapped into the container while you are later calling the concordium-client from `/home/<user2>/Documents/concordium-software` which is not mapped into the container. Docker inspecting the container should show you which directory is mapped:
```
❯ docker inspect concordium-client | grep ":/home/docker/concordium-client"
                "/home/<myUser>/Documents/concordium-software:/home/docker/concordium-client"
```

**Comment by EmreNOP** [comment]
Thank you for details. since i move wallet file inside of docker, concordium-client is working well. 
But ive noticed that i have no mapping under Documents.
Im not sure but i may have worked first time in another folder concordium-node and first initialization screwed up somehow. 
even i use under Document, still drift behind old initialization configs. 


xx@xx:~/Documents/concordium-software$  ./concordium-client -v config account import export.concordiumwallet
Base configuration:
- Verbose:            yes
- Account config dir: /var/lib/concordium/config/accounts
- Account name map:   none

Error: The given file 'export.concordiumwallet' does not exist.

xx@xx:~/Documents/concordium-software$ docker exec -ti 49815d8caf87 /bin/bash
root@49815d8caf87:/# ls -la /home/docker/concordium-client
total 8
drwxr-xr-x 2 root   root   4096 Oct 21 09:55 .
drwxr-xr-x 3 docker docker 4096 Oct 21 09:55 ..

root@49815d8caf87:/# read escape sequence
xx@xx:~/Documents/concordium-software$ docker cp export.concordiumwallet 49815d8caf87:/home/docker/concordium-client/
xx@xx:~/Documents/concordium-software$ docker exec -ti 49815d8caf87 /bin/bash

root@49815d8caf87:/# ls -la /home/docker/concordium-client
total 280
drwxr-xr-x 2 root   root     4096 Oct 23 11:54 .
drwxr-xr-x 3 docker docker   4096 Oct 21 09:55 ..
-rwxrwxrwx 1 docker docker 277811 Oct 21 11:33 export.concordiumwallet
root@49815d8caf87:/# read escape sequence

xx@xx:~/Documents/concordium-software$ ./concordium-client -v config account import export.concordiumwallet
Base configuration:
- Verbose:            yes
- Account config dir: /var/lib/concordium/config/accounts
- Account name map:   none

Enter encryption password:


Output from docker inspect. 
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/xx/.local/share/concordium",
                "Destination": "/var/lib/concordium/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/xx/.config/concordium",
                "Destination": "/var/lib/concordium/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
