### ISSUE TITLE
My node miss from dashboard often, but running

### ISSUE THREAD

**Issue by iekmuby** [Concordium/Testnet3-Challenges#812]
My node was online 14 days. Today I start receiving notifications from my custom monitor script, that node miss from dashboard list. This is not a browser cache issue, because I get info from your api. At the same time, my node output from console shows me normal node output. Also, last fin value 2 times higher than other nodes:

![Image](https://media.discordapp.net/attachments/687313907500449849/768529176336400445/Screenshot_2020-10-21_20-39-23.png?width=609&height=416)

On the first restart I also get following message on the initial screen:

`error sending request for url (https://auth.testnet.concordium.com/token/create): operation timed out
Failed to post to authentication server`

**Comment by ab-concordium** [comment]
Did the message go away? If so it looks like a temporary network issue.

Could you provide us with logs around (i.e., before, and possibly after) the time your node got behind in finalization, as well as with system information (e.g., memory, disk space). If you have monitoring for the resource usage that will be helpful in narrowing the cause of failure as well.

It could be a number of things, and with the information you provided we can only guess.

**Comment by concordium-admin** [comment]
Probably a temporary issue; no further user data provided.
