### ISSUE TITLE
FAILURE Client has not been run ERROR

### ISSUE THREAD

**Issue by myasin59** [Concordium/Testnet3-Challenges#945]
I am getting this error when trying to log. What is the reason?
![ERR](https://user-images.githubusercontent.com/73083527/96945288-fe36c280-14e5-11eb-9542-cf5abbd641ef.png)

**Comment by concordium-admin** [comment]
Hi myasin59, reading the error message you got, I have to ask you as a first thing: Are you sure that you have ever started your node (with `./concordium-node` and filling in the necessary info when prompted)? What is your nodeID and node name?

**Comment by myasin59** [comment]
yes, it has been working for 9 days.Also, the node I set up for the b2
task is getting logs, but it fails.

Name: myasin55

Node ID:  f1e4dd1102609918



concordium-admin <notifications@github.com>, 23 Eki 2020 Cum, 10:27
tarihinde şunu yazdı:

**Comment by ab-concordium** [comment]
The log retrieval tool is a bit wasteful with memory at the moment. A new one should be available next week. To debug your issue, I would need the following information
- did your node get killed due to, say, running out of disk space, or memory?
- can you run `docker container list` and post the results here?

That should output a CONTAINER ID that you can then use to get the logs via `docker logs`. If docker container list does not output any container related to concordium then your node is not running.

**Comment by myasin59** [comment]
![cont](https://user-images.githubusercontent.com/73083527/97086981-63e29600-162f-11eb-8586-8675704a66a8.png)

no problem with storage we have enough space.

**Comment by ab-concordium** [comment]
And what does `docker container inspect concordium-client` produce?

**Comment by myasin59** [comment]
![errr](https://user-images.githubusercontent.com/73083527/97110250-29d5ca80-16e9-11eb-8c1f-c6ec3516f9c0.png)
client gives this error when I want to run it. also I don't understand what you mean, could be a bit more specific you know.

**Comment by ab-concordium** [comment]
My question was, if you run `docker container inspect concordium-client`, what is the result. I don't think I can be more specific than that. There's clearly something unusual about your configuration that is causing these failures.

What user are your running these commands under? Are any of the environment variables XDG_DOCUMENTS_DIR or HOME set?

**Comment by myasin59** [comment]
"HostIp": "",
                        "HostPort": "8888"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
c6384808c4318a982c04d3c/diff:/var/lib/docker/overlay2/df245efe8feab3894b9ff0cb28d35254316c7c096a27f600cc768f42a1865a00/diff:/var/lib/docker/overlay2/54a755991a88cc62beab56200694cb16fdbe893dfd0184ca1290b51599213b49/diff:/var/lib/docker/overlay2/c93278140e36f6c6b8c0949cb527f6f7a0a916f4117bc50afa7754509140b44c/diff:/var/lib/docker/overlay2/46f631d70a50d6e0ba516377859c979cf94df26da2aac4dadad14d8015adb489/diff:/var/lib/docker/overlay2/a3b959bd6a10fe0c991df578d9ebe5f53034ef706437cdb4a968bef268ed4609/diff:/var/lib/docker/overlay2/78fa845e5f69c1451f3583c09b5b68e7060805ab233dd0d9b5a5c7cf3f593305/diff:/var/lib/docker/overlay2/6aa97daf47f2ae11ea5e09714a9e150e8b17d0a042c33278686d9bd0c628561f/diff:/var/lib/docker/overlay2/904d15848fcc56bf44a5f16d4549476d98d60456bf040eb744e8e25c88c21f75/diff:/var/lib/docker/overlay2/74488d5c40426ea1bc643f1b83304ecb71f8875d47404a43598220c22778bc91/diff:/var/lib/docker/overlay2/b950373293adab2dc81c9ff855a05fafa67e8603f93cf0390b86e93268df3997/diff:/var/lib/docker/overlay2/deb4e598711b05e0fdc651103af514007e1029fa5d4b37e304c469cf98af8a67/diff:/var/lib/docker/overlay2/6f5dbfc7ba13c4f584bff95c16b789c4728fffd14d7b4ed196b67ef506a50667/diff:/var/lib/docker/overlay2/898262d064fe1f615b7108ba8f808152f29d8e6dd2c03045eee88bf007fbf34e/diff:/var/lib/docker/overlay2/60574ada1cece51dd230007caae81cdae02cc54e6e7989af3c7051972dc43157/diff:/var/lib/docker/overlay2/cecdd4a2425d96fdcc85fed5f513cbf5a65bf2d7af4ba33786b27f35eac6a6f8/diff:/var/lib/docker/overlay2/0d686565b891d027f2b5bd5e20b138d308d4d4e33c37bedf6eb914f96b3a7ebb/diff",
                "MergedDir": "/var/lib/docker/overlay2/7f35312999453f78c6f0b8a8e46098baba377e30cb7765b588cb6165bf5e0a6a/merged",
                "UpperDir": "/var/lib/docker/overlay2/7f35312999453f78c6f0b8a8e46098baba377e30cb7765b588cb6165bf5e0a6a/diff",
                "WorkDir": "/var/lib/docker/overlay2/7f35312999453f78c6f0b8a8e46098baba377e30cb7765b588cb6165bf5e0a6a/work"
            },
            "Name": "overlay2"
        },
                ],
                "8888/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8888"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/80afbdf1c61e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "fe9df201f6886027020642f9bdae051221a015b444c79ef912baa495c3d8389f",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5fde9ee1332e47b790f8cb81472cf5afdcef1e4b76189dd6dbb94e199c26ff8b",
                    "EndpointID": "fe9df201f6886027020642f9bdae051221a015b444c79ef912baa495c3d8389f",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
